### ISSUE TITLE
Debug spam: "not setting proxy config because Proxy status is empty"

### ISSUE THREAD

**Issue by sgreene570** [openshift/machine-config-operator#1001]
**Description**
When a proxy is not configured, the MCO pod really let's you know.
Ideally, this logging call only happens once (or maybe the function `createDiscoveredControllerConfigSpec` is being called too often, I'm not sure).

**Steps to reproduce the issue:**
1. Spin up new cluster
2. Check `machine-config-operator` pod logs

**Describe the results you received:**
The `glog.Info` message "Not setting proxy config because Proxy status is empty" is printed to the pod logs every ~45 seconds if a proxy is not configured.  This seems excessive. 

**Additional information you deem important (e.g. issue happens only occasionally):**
We should confirm that the `createDiscoveredControllerConfigSpec` should be called repetitively. 

```
...
I0722 23:12:16.854507       1 render.go:96] Not setting proxy config because Proxy status is empty
I0722 23:13:20.274771       1 render.go:96] Not setting proxy config because Proxy status is empty
I0722 23:13:51.474132       1 render.go:96] Not setting proxy config because Proxy status is empty
I0722 23:13:56.700352       1 render.go:96] Not setting proxy config because Proxy status is empty
I0722 23:18:26.279714       1 render.go:96] Not setting proxy config because Proxy status is empty
I0722 23:23:48.274809       1 render.go:96] Not setting proxy config because Proxy status is empty
I0722 23:24:34.896527       1 render.go:96] Not setting proxy config because Proxy status is empty
I0722 23:24:40.160432       1 render.go:96] Not setting proxy config because Proxy status is empty
keeps going...
...

```

**Comment by sgreene570** [comment]
This is the LOC where the message is printed to the log

https://github.com/openshift/machine-config-operator/blob/master/pkg/operator/render.go#L96

**Comment by runcom** [comment]
Uhm, yeah, let's lower down the verbosity to v2 at least
