### ISSUE TITLE
Documentation on how to work with heterogeneous nodes is needed

### ISSUE THREAD

**Issue by yrobla** [openshift/machine-config-operator#1005]
**Description**

Currently machine configs can be applied to a machine config pool, that is associated to a node with a certain node. But there is a need of having some nodes, with a similar role, but with special configuration needs.
To do that, a different machine config pool needs to be created, but then it needs to inherit all the machine configs from the original role (let's say infra needs to inherit configs from worker).
This is possible to do with something like: https://github.com/openshift/machine-config-operator/issues/429#issuecomment-499458138

But it is not trivial and not documented. So there could be a section in documentation explaining how to do it.

**Comment by runcom** [comment]
cc @chrisnegus

**Comment by runcom** [comment]
related to https://url.corp.redhat.com/c3fff94
