### ISSUE TITLE
Better Error Handling for NewClientSet 

### ISSUE THREAD

**Issue by iamemilio** [openshift/machine-config-operator#1019]
**Description**
#### (Low Severity Issue)

 https://github.com/openshift/machine-config-operator/blob/fcd80d34dcd9dbef012d85e58972bde510cb343e/test/e2e/framework/clientset.go#L25
The function NewClientSet Panics when one of its sub functions returns an error, rather than logging the error and exiting non zero. This creates hard to trace panic dumps rather than clear error logs.

Rather than panic, this line should return: nil, error
https://github.com/openshift/machine-config-operator/blob/fcd80d34dcd9dbef012d85e58972bde510cb343e/test/e2e/framework/clientset.go#L41

That error should be tested for here, and then potentially trigger a t.Fatalf()
https://github.com/openshift/machine-config-operator/blob/fcd80d34dcd9dbef012d85e58972bde510cb343e/test/e2e/etcdquorumguard_test.go#L38

**Steps to reproduce the issue:**
1. Run make test in an env without kubernetes env variables exported

**Describe the results you received:**
```
--- FAIL: TestEtcdQuorumGuard (0.00s)
panic: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined [recovered]
	panic: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined

goroutine 8 [running]:
testing.tRunner.func1(0xc000274a00)
	/usr/lib/golang/src/testing/testing.go:792 +0x387
panic(0x110c960, 0xc0002738a0)
	/usr/lib/golang/src/runtime/panic.go:513 +0x1b9
github.com/openshift/machine-config-operator/test/e2e/framework.NewClientSet(0x0, 0x0, 0x26)
	/home/egarcia/go/src/github.com/openshift/machine-config-operator/test/e2e/framework/clientset.go:41 +0x33c
github.com/openshift/machine-config-operator/test/e2e.TestEtcdQuorumGuard(0xc000274a00)
	/home/egarcia/go/src/github.com/openshift/machine-config-operator/test/e2e/etcdquorumguard_test.go:38 +0x3e
testing.tRunner(0xc000274a00, 0x1302a88)
	/usr/lib/golang/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:878 +0x35c
FAIL	github.com/openshift/machine-config-operator/test/e2e	0.011s
make: *** [Makefile:108: test-e2e] Error 1
```

**Comment by kikisdeliveryservice** [comment]
This panic is in the e2e that is run in CI. A panic seems like it would be correct here since this failure would be totally unexpected and unrecoverable in the course of running the e2e.

**Comment by iamemilio** [comment]
Fair enough. Closing.
