### ISSUE TITLE
mastersSchedulable: true not working when set at install time

### ISSUE THREAD

**Issue by russellb** [openshift/machine-config-operator#1024]
**Description**

This is related to issue #763 and PR #937 

On a running cluster, I was able to change `mastersSchedulable` to `true` and observe the right things happening.

I just deployed a new 3-node cluster with https://github.com/openshift/installer/pull/2004 included, which sets `mastersSchedulable: true` at install time.  In this case, the MCO did not properly reconcile the master Nodes based on this setting.  After the install timed out because ingress never came up, I manually changed the `mastersSchedulable` setting to `false` and then back to `true`.  This triggered reconciliation and I observed that the Nodes correcting had the worker role applied to them.

**Steps to reproduce the issue:**
1. Deploy a 3-node cluster
2. Observe that `mastersSchedulable: true` is set at install time in the scheduler config
3. Observe that the Nodes are not properly reconciled by MCO

**Comment by ravisantoshgudimetla** [comment]
@russellb - Can you provide mco logs after increasing the loglevel to 5 or above? I think, the scheduler informer is somehow missing the scheduler object creation event. https://github.com/openshift/machine-config-operator/blob/master/pkg/controller/node/node_controller.go#L167. I need to look more, if this the case.

You can disable CVO and update the mco log-level here https://github.com/openshift/machine-config-operator/blob/88147c9a50342ee9177ff513970757fa0cf34120/manifests/machineconfigcontroller/deployment.yaml#L22

**Comment by russellb** [comment]
2 updates:

1) This is not consistent.  It seems to happen in roughly half of my deployments.

2) I adjusted the `-v` level on the `machine-config-controller` deployment, and it reconciled the Nodes on restart

**Comment by cgwalters** [comment]
This should be fixed by https://github.com/openshift/machine-config-operator/pull/1029 - please reopen if I'm mistaken.  And thanks for the fixes!
