### ISSUE TITLE
e2e-aws-op timeouts

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#1039]
A lot of our recent PRs are timing out; [this one](https://github.com/openshift/machine-config-operator/pull/1025) is a good example.  Some are getting in - I think we're floating close to the timeout.

Looking at historical PRs, for example [this old PR](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/982/pull-ci-openshift-machine-config-operator-master-e2e-aws-op/2989/artifacts/e2e-aws-op/must-gather/namespaces/openshift-machine-config-operator/pods/machine-config-controller-58cbf4cc95-pp2rd/machine-config-controller/machine-config-controller/logs/current.log) we are taking 3-4 minutes to roll out a change to all 3 workers.

Whereas in [the above PR](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/982/pull-ci-openshift-machine-config-operator-master-e2e-aws-op/2989/artifacts/e2e-aws-op/must-gather/namespaces/openshift-machine-config-operator/pods/machine-config-controller-58cbf4cc95-pp2rd/machine-config-controller/machine-config-controller/logs/current.log) it's closer to 6-7.

Some internal chat we had about this theorized it's a result of the recent fixes to draining and the pod disruption budget for the router.   I also filed https://github.com/openshift/machine-config-operator/issues/1038 related to this.

That said, this issue is about whatever we need to fix to get our e2e-aws-op back to regularly green.  We may suck it up and just bump the timeout?

Alternatively...I don't think we need to run that on every PR - we could just choose to make it opt in?

**Comment by kikisdeliveryservice** [comment]
Notes: the e2e-aws-op started failing more frequently around ~ July 26th according to the job runs:
https://prow.svc.ci.openshift.org/job-history/origin-ci-test/pr-logs/directory/pull-ci-openshift-machine-config-operator-master-e2e-aws-op

**Comment by runcom** [comment]
I'd bump the timeout to make it reliable for the time being
