### ISSUE TITLE
MC updates could cause unexpected results for static pod manifests.

### ISSUE THREAD

**Issue by hexfusion** [openshift/machine-config-operator#1074]
I am seeing circumstances[1] where when MC updates are made to static pod manifests it appears the original file supersede the new file.  

kubelet logs
```
Aug 14 12:08:11 ip-10-0-144-177 hyperkube[1491]: I0814 12:08:11.923936    1491 file.go:200] Reading config file "/etc/kubernetes/manifests/etcd-member.yaml"
Aug 14 12:08:11 ip-10-0-144-177 hyperkube[1491]: I0814 12:08:11.925976    1491 file.go:200] Reading config file "/etc/kubernetes/manifests/etcd-member.yaml.mcdorig"
```

The change was made here[2], while I understand its usefulness I am surprised that kubelet will read any file in manifest dir apparently regardless of extension. Still digging but wanted to get this in front of maintainers eyes early for input.

[1] https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1056/pull-ci-openshift-machine-config-operator-master-e2e-restore-cluster-state/16
[2] https://github.com/openshift/machine-config-operator/pull/797

/cc @runcom @kikisdeliveryservice

**Comment by runcom** [comment]
> The change was made here[2], while I understand its usefulness I am surprised that kubelet will read any file in manifest dir apparently regardless of extension. Still digging but wanted to get this in front of maintainers eyes early for input.

ouch, guess that's a real bug then, maybe we shouldn't use $PWD for the `.mcdorig` backup file, I'll fix that.

**Comment by runcom** [comment]
@hexfusion do we have a BZ for this?

**Comment by hexfusion** [comment]
> @hexfusion do we have a BZ for this?

@runcom I will verify my claim and file bug if that is the case. I am just going from logs at the moment but will test shortly.

**Comment by runcom** [comment]
> @runcom I will verify my claim and file bug if that is the case. I am just going from logs at the moment but will test shortly.

thanks a lot Sam

**Comment by hexfusion** [comment]
@runcom https://bugzilla.redhat.com/show_bug.cgi?id=1744580
