### ISSUE TITLE
Races in mco when 2 roles are assigned

### ISSUE THREAD

**Issue by yrobla** [openshift/machine-config-operator#1094]
I need to have 2 different types of roles for my workers: worker and worker-rt (realtime nodes). So following advice, i created a worker-rt machineconfigpool with the following config:

apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: worker-rt
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,worker-rt]}
  maxUnavailable: null
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker-rt: ""
  paused: false

I also have my node labelled with worker and worker-rt roles:
test-worker-0   Ready    worker,worker-ran,worker-rt   97m    v1.13.4+af45cda
test-worker-1   Ready    worker                        99m    v1.13.4+509f0153f

So initially everything seems to be ok. Node joins the cluster, it picks the rt machineconfigs from the machineconfigpool/worker-rt, and installs realtime kernel.
But over 30 minutes later, i start to see races, and continuous reboots:

ago 30 09:36:29 test-worker-0 root[38492]: machine-config-daemon[10106]: Starting update from rendered-worker-rt-8ee097f3e621df9e22178f682958324c to rendered-worker-dad2c8e5559f2ab6e5793b3100de7c12
ago 30 09:36:29 test-worker-0 root[38493]: {"MESSAGE": "rendered-worker-dad2c8e5559f2ab6e5793b3100de7c12", "BOOT_ID": "b0147223-3c5e-431e-a1ad-faefe0779bb2", "PENDING": "1", "OPENSHIFT_MACHINE_CONFIG_DAEMON_LEGACY_LOG_HACK": "1"}
ago 30 09:36:29 test-worker-0 root[38494]: machine-config-daemon[10106]: Update prepared; beginning drain

ago 30 09:38:44 test-worker-0 root[14540]: machine-config-daemon[11201]: Starting update from rendered-worker-dad2c8e5559f2ab6e5793b3100de7c12 to rendered-worker-rt-8ee097f3e621df9e22178f682958324c
ago 30 09:38:45 test-worker-0 root[14541]: {"MESSAGE": "rendered-worker-rt-8ee097f3e621df9e22178f682958324c", "BOOT_ID": "a9bcd354-d97d-4726-a3bc-b8b2cc5f7242", "PENDING": "1", "OPENSHIFT_MACHINE_CONFIG_DAEMON_LEGACY_LOG_HACK": "1"}
ago 30 09:38:45 test-worker-0 root[14542]: machine-config-daemon[11201]: Update prepared; beginning drain
ago 30 09:38:45 test-worker-0 root[14543]: machine-config-daemon[11201]: drain complete
ago 30 09:38:45 test-worker-0 root[14544]: machine-config-daemon[11201]: initiating reboot: Node will reboot into config rendered-worker-rt-8ee097f3e621df9e22178f682958324c

See how it is just changing between worker and worker-rt all the time, with a reboot per change. Also machineconfigpool is changing, with worker and worker-rt updating all the time:

NAME        CONFIG                                                UPDATED   UPDATING   DEGRADED
master      rendered-master-ec3c3465746828af87b66ea870f4fac4      True      False      False
worker      rendered-worker-dad2c8e5559f2ab6e5793b3100de7c12      False     True       False
worker-rt   rendered-worker-rt-8ee097f3e621df9e22178f682958324c   True      False      False

This means i cannot use this system to add my realtime config, because it causes a continuous reboot on my worker.

I tested with 4.1.13 version: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.1.13/openshift-install-linux-4.1.13.tar.gz . But i'm seeing this behaviour since i started to test with 4.1.3

**Comment by runcom** [comment]
> I tested with 4.1.13 version: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.1.13/openshift-install-linux-4.1.13.tar.gz . But i'm seeing this behaviour since i started to test with 4.1.3

please test with 4.2 - 4.1 wasn't meant for custom pools, and I'm not surprised at all you're experiencing this kind of behavior.

Please re-test with 4.2 and let us know.

**Comment by runcom** [comment]
On 4.2, nothing is happening on my cluster:

```
12:38:06 [github.com/openshift/installer] ‹master*› date
Fri 30 Aug 2019 12:38:29 PM CEST
12:39:17 [github.com/openshift/installer] ‹master*› date
Fri 30 Aug 2019 01:43:37 PM CEST
13:43:37 [github.com/openshift/installer] ‹master*›
```

```
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED
infra    rendered-infra-905aa6afab4242efe964ed3d0c0ceb2c    True      False	 False
master   rendered-master-16b963ac5f308e7e6360d64014589212   True      False	 False
worker   rendered-worker-ebeb1981d5598b1530859088bf5247d0   True      False	 False
```

```
NAME                           STATUS   ROLES          AGE   VERSION
ip-10-0-130-219.ec2.internal   Ready    infra,worker   80m   v1.14.0+1b115d2f2
ip-10-0-142-171.ec2.internal   Ready    master         85m   v1.14.0+1b115d2f2
ip-10-0-146-113.ec2.internal   Ready    master         85m   v1.14.0+1b115d2f2
ip-10-0-156-175.ec2.internal   Ready    worker         80m   v1.14.0+1b115d2f2
ip-10-0-161-212.ec2.internal   Ready    master         86m   v1.14.0+1b115d2f2
ip-10-0-175-129.ec2.internal   Ready    worker         80m   v1.14.0+1b115d2f2
```

```
I0830 10:34:43.916746       1 status.go:82] Pool infra: All nodes are updated with rendered-infra-905aa6afab4242efe964ed3d0c0ceb2c
```

Please don't use 4.1 for custom pools, they're not supported and thus not properly working.

If you can reproduce this on 4.2, please comment again, but otherwise my testing was successful - I'll leave the cluster running for some more hours but hardly anything will happen.

**Comment by yrobla** [comment]
I am testing now with 4.2 but there seems to be some issue. Machineconfigpool are degraded: 
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED
master                                                      False     True       True
worker   rendered-worker-fcdc5a2f9165afac8f8fee297bd765f0   False     True       True

Either on master and workers i have: Node test-master-0 is reporting: "during bootstrap: failed to run pivot: failed to start pivot.service: exit status 5"

**Comment by runcom** [comment]
> Either on master and workers i have: Node test-master-0 is reporting: "during bootstrap: failed to run pivot: failed to start pivot.service: exit status 5"

this is another issue not related to this one - can you provide more info on that also, ideally, if you can run must-gather on that 4.2 cluster, we can understand more on that issue as well. That pivot.service failure can be lots of stuff, also provide the payload name that you're using for 4.2

**Comment by yrobla** [comment]
I took the images from https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest/rhcos-42.80.20190828.2-metal-bios.raw.gz , rhcos-42.80.20190828.2-installer-initramfs.img, https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/latest/rhcos-42.80.20190828.2-installer-initramfs.img .
The installer is from https://mirror.openshift.com/pub/openshift-v4/clients/ocp/unreleased/4.2.0-0.nightly-2019-06-03-135056/

**Comment by runcom** [comment]
> if you can run must-gather on that 4.2 cluster, we can understand more on that issue as well

that will help us understand more - journal logs from the nodes that are experiencing that pivot issue might be helpful as well

**Comment by yrobla** [comment]
Ok i was using an old installer/images. Testing with latest 4.2 ones fixed the pivot issue. But on machineconfigpool, i still see a weird behaviour. Now i see the worker-rt machineconfigpool is just stuck on updating:

[root@vip installer]# oc get machineconfigpool
NAME        CONFIG                                             UPDATED   UPDATING   DEGRADED
master      rendered-master-6e3b5b22b80103f5f0e86b68b3e8cc21   True      False      False
worker      rendered-worker-c1d538c229f94842b220c1fb567740b8   True      False      False
worker-rt                                                      False     True       False

It has been more than an hour in that state. In logs i can see:
Status:
  Conditions:
    Last Transition Time:  2019-09-03T05:08:56Z
    Message:               
    Reason:                
    Status:                False
    Type:                  RenderDegraded
    Last Transition Time:  2019-09-03T05:09:01Z
    Message:               
    Reason:                
    Status:                False
    Type:                  Updated
    Last Transition Time:  2019-09-03T05:09:01Z
    Message:               All nodes are updating to rendered-worker-rt-4de3cf72ff7e6c40d7b7c418ce7a8be0
    Reason:                
    Status:                True
    Type:                  Updating
    Last Transition Time:  2019-09-03T05:44:53Z
    Message:               
    Reason:                
    Status:                False
    Type:                  NodeDegraded
    Last Transition Time:  2019-09-03T05:44:53Z
    Message:               
    Reason:                
    Status:                False
    Type:                  Degraded

It applied the worker-rt config properly, but machineconfigpool does not report an end of the update.

machine-config-daemon pod inside worker reports ok as well:
I0903 08:11:49.010325    7063 daemon.go:949] In desired config rendered-worker-rt-4de3cf72ff7e6c40d7b7c418ce7a8be0

If that helps, initially the node was not reporting properly because it is a Centos 7 machine with an older logger version. I had to manually install rpms with a new logger version and then machine-config-daemon started to work and report properly, until it arrived to my described behaviour.

**Comment by yrobla** [comment]
I can confirm that it fails with CentOS 7 and RHEL 8, and works with RHEL 7
