### ISSUE TITLE
MCO fails when an MCP is applied to a CentOS 7 node

### ISSUE THREAD

**Issue by yrobla** [openshift/machine-config-operator#1096]
I added a Centos 7 worker using the openshift-ansible procedure, node is ok and reports as ready. Then i try to apply an specific machine config pool (to add real time support) on this node. As soon as it starts applying, i see this error in the MCP logs:

```Node test-worker-0 is reporting: "failed to log pending config: logger: unrecognized option '--journald'\n\nUsage:\n logger [options] [message]\n\nOptions:\n -T, --tcp             use TCP only\n -d, --udp             use UDP only\n -i, --id              log the process ID too\n -f, --file <file>     log the contents of this file\n -h, --help            display this help text and exit\n -S, --size <num>      maximum size for a single message (default 1024)\n -n, --server <name>   write to this remote syslog server\n -P, --port <port>     use this port for UDP or TCP connection\n -p, --priority <prio> mark given message with this priority\n -s, --stderr          output message to standard error as well\n -t, --tag <tag>       mark every line with this tag\n -u, --socket <socket> write to this Unix socket\n -V, --version         output version information and exit\n\n: exit status 1" ```

The issue there, is that the logger version of CentOS 7 is too old (2.23) and does not have the --journal flag. There doesn't seem any public repos that offer a newer logger version for Centos 7. I had to manually download and install a list of rpms from koji.

Aren't Centos 7 workers supported? If they are, how can this be fixed, could we avoid the --journal flag, or do a check for the version of logger before trying to use it?

**Comment by runcom** [comment]
> Aren't Centos 7 workers supported?

I'm not sure who to route this, my impression is they're not supported

**Comment by runcom** [comment]
PM confirmed CentOS workers are not supported.
