### ISSUE TITLE
Cannot create custom kubelet config when using UPI

### ISSUE THREAD

**Issue by yrobla** [openshift/machine-config-operator#1156]
I followed this documentation in order to setup static cpu policy: https://docs.openshift.com/container-platform/4.1/scalability_and_performance/using-cpu-manager.html.
But i found that, when i created the custom kubelet config (exactly the same as the one showed in that link), i'm getting:
  - lastTransitionTime: "2019-10-07T18:45:18Z"
    message: 'could not generate the original Kubelet config: could not generate the
      original Kubelet config: %v'
    status: "False"
    type: Failure

I'm using UPI for that, so platform is 'none'. I also have a custom config-pool, called worker-rt.

**Comment by yrobla** [comment]
Description of machineconfigpool:
oc get machineconfigpool/worker-rt -o yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"machineconfiguration.openshift.io/v1","kind":"MachineConfigPool","metadata":{"annotations":{},"labels":{"custom-kubelet":"cpumanager-enabled"},"name":"worker-rt"},"spec":{"machineConfigSelector":{"matchExpressions":[{"key":"machineconfiguration.openshift.io/role","operator":"In","values":["worker","worker-rt"]}]},"maxUnavailable":null,"nodeSelector":{"matchLabels":{"node-role.kubernetes.io/worker-rt":""}},"paused":false}}
  creationTimestamp: "2019-10-07T14:43:49Z"
  generation: 3
  labels:
    custom-kubelet: cpumanager-enabled
  name: worker-rt
  resourceVersion: "143942"
  selfLink: /apis/machineconfiguration.openshift.io/v1/machineconfigpools/worker-rt
  uid: dfc5dee3-e910-11e9-ae5e-ac1f6b7bea24
spec:
  configuration:
    name: rendered-worker-rt-58636fd0f7f101864b3ac86d801a0282
    source:
    - apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      name: 00-worker
    - apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      name: 01-worker-container-runtime
    - apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      name: 01-worker-kubelet
    - apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      name: 99-worker-efa8ae62-e8ef-11e9-802d-52540082683d-registries
    - apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      name: 99-worker-ssh
    - apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      name: machine-config-worker-rt
    - apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      name: machine-config-worker-rt-env-vars
  machineConfigSelector:
    matchExpressions:
    - key: machineconfiguration.openshift.io/role
      operator: In
      values:
      - worker
      - worker-rt
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/worker-rt: ""
  paused: false
status:
  conditions:
  - lastTransitionTime: "2019-10-07T14:43:54Z"
    message: ""
    reason: ""
    status: "False"
    type: RenderDegraded
  - lastTransitionTime: "2019-10-07T17:02:27Z"
    message: All nodes are updated with rendered-worker-rt-58636fd0f7f101864b3ac86d801a0282
    reason: ""
    status: "True"
    type: Updated
  - lastTransitionTime: "2019-10-07T17:02:27Z"
    message: ""
    reason: ""
    status: "False"
    type: Updating
  - lastTransitionTime: "2019-10-07T17:02:27Z"
    message: ""
    reason: ""
    status: "False"
    type: NodeDegraded
  - lastTransitionTime: "2019-10-07T17:02:27Z"
    message: ""
    reason: ""
    status: "False"
    type: Degraded
  configuration:
    name: rendered-worker-rt-58636fd0f7f101864b3ac86d801a0282
    source:
    - apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      name: 00-worker
    - apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      name: 01-worker-container-runtime
    - apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      name: 01-worker-kubelet
    - apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      name: 99-worker-efa8ae62-e8ef-11e9-802d-52540082683d-registries
    - apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      name: 99-worker-ssh
    - apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      name: machine-config-worker-rt
    - apiVersion: machineconfiguration.openshift.io/v1
      kind: MachineConfig
      name: machine-config-worker-rt-env-vars
  degradedMachineCount: 0
  machineCount: 1
  observedGeneration: 3
  readyMachineCount: 1
  unavailableMachineCount: 0
  updatedMachineCount: 1

**Comment by kikisdeliveryservice** [comment]
Please include a must-gather for this cluster

**Comment by kikisdeliveryservice** [comment]
Pending must-gather is this related to: https://github.com/openshift/machine-config-operator/issues/429#issuecomment-524092635

cc: @runcom @rphillips

**Comment by kikisdeliveryservice** [comment]
as per @runcom comment isn't this here: https://github.com/openshift/machine-config-operator/blob/92ae68da006d09b2c55c3b0425ba242d8e2232d1/pkg/controller/kubelet-config/kubelet_config_controller.go#L434 an issue? and we'd need to check if it's a custom role before trying to grab the originalkubeletconfig?

**Comment by yrobla** [comment]
> as per @runcom comment isn't this here:
> 
> https://github.com/openshift/machine-config-operator/blob/92ae68da006d09b2c55c3b0425ba242d8e2232d1/pkg/controller/kubelet-config/kubelet_config_controller.go#L434
> an issue? and we'd need to check if it's a custom role before trying to grab the originalkubeletconfig?

I'm using a custom role, worker-rt. See the paste of mcp before...

**Comment by kikisdeliveryservice** [comment]
i know. hence my comment :)

**Comment by kikisdeliveryservice** [comment]
i think if it's a custom role maybe return the worker original kubeletconfig instead of trying to return the worker-rt original kubeletconfig that doesn't exist?

will let @runcom and @rphillips tell me if my wild speculation is correct or not

**Comment by yrobla** [comment]
https://drive.google.com/file/d/18c-0iyr0KMR-WRhvrJQIMYukuY60-lMJ/view?usp=sharing

**Comment by kikisdeliveryservice** [comment]
if the pool is not worker or master but custom check the pool here: 
`"matchExpressions":[{"key":"machineconfiguration.openshift.io/role","operator":"In","values":["worker","worker-rt"]} `

to verify that worker is in there then ruse the worker OriginalKubeletConfig for the custom pool

**Comment by runcom** [comment]
> i think if it's a custom role maybe return the worker original kubeletconfig instead of trying to return the worker-rt original kubeletconfig that doesn't exist?
> 
> will let @runcom and @rphillips tell me if my wild speculation is correct or not

yes, that was a shortcoming with custom role support indeed - I will keep an eye on this and follow up as soon as possible

**Comment by runcom** [comment]
oh so, the reason for CRI-O and Kubelet configs to stick with what the parent worker role has is to avoid drift between kubelets and runtime on the same cluster - I think we'll need to sit down and carefully plan any change in that to allow custom-pools to also have different kube/runtime configs.

**Comment by kikisdeliveryservice** [comment]
> oh so, the reason for CRI-O and Kubelet configs to stick with what the parent worker role has is to avoid drift between kubelets and runtime on the same cluster - I think we'll need to sit down and carefully plan any change in that to allow custom-pools to also have different kube/runtime configs.

makes sense - thank you!
