### ISSUE TITLE
consider making config changes truly transactional on RHCOS

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#1190]
With ostree, each deployment (bootable target) has its own copy of `/etc`.

Today, the MCD writes into the *current* `/etc`.  This has weird side effects; for example, it means that we may be affecting running static pods for kubelet.  We may rewrite the pull secret.

It also means we don't have rollback at the ostree level.

It'd be fairly easy to change the MCD to (on RHCOS) create a *new* deployment for pure config changes, and write the new changes to `/etc` there - leaving the booted system untouched.

This would mean that config changes would be fully transactional and offline, the same way OS updates are.

**Comment by cgwalters** [comment]
Another way to look at this is, it'd enforce that config changes require a reboot.  

We could drop the hacks around using journald for which config we're in, because `/etc` becomes transactional.  (And much closer to being immutable - see also https://github.com/projectatomic/rpm-ostree/issues/702 )

**Comment by cgwalters** [comment]
Also a prerequisite is moving the pull secret from `/var` into `/etc` - and in general, all MachineConfig changes.

**Comment by mrunalp** [comment]
:+1: IIUC, this would prevent new static pod manifests to take effect until we reboot.

**Comment by sinnykumari** [comment]
This proposal looks interesting!
 One question though - will this apply on firstboot of node as well? This question is because today mcd available on host reads MachineConfig and writes `/etc/ignition-machine-config-encapsulated.json` during firstboot which is later used by mcd to apply kargs in firstboot.

**Comment by cgwalters** [comment]
> One question though - will this apply on firstboot of node as well?

I don't see a blocker to doing this on firstboot too.

**Comment by sinnykumari** [comment]
> > One question though - will this apply on firstboot of node as well?
> 
> I don't see a blocker to doing this on firstboot too.

Looks like I might have misunderstood little bit making /etc/ changes  transactional.

What will happen with this proposal in place during firstboot? Most likely during firstboot we will have config changes (like new file to be added in /etc/ignition-machine-config-encapsulated.json ) and also new machine-os-content. Today, we create new deployment for mchine-os-content changes which gets applied after reboot. What will happen to files like /etc/ignition-machine-config-encapsulated.json, will it be written to current deployment or in new deployment?

**Comment by cgwalters** [comment]
The motivation for filing this issue was the [etcd upgrade bug](https://bugzilla.redhat.com/show_bug.cgi?id=1761557).

However, we're also now seeing this [for kubelet config](https://bugzilla.redhat.com/show_bug.cgi?id=1786993).

And see also a related [podman config bug](https://bugzilla.redhat.com/show_bug.cgi?id=1768879).

One comment I had on the podman bug was:

> The problem is that doing the naive thing and always doing an OS update *before* config changes would force double reboots for every upgrade.
> We could try to detect "major version" upgrades and force doing the OS update first there...wouldn't be terribly hard, but would add noticeable latency to upgrades.

**Comment by cgwalters** [comment]
> What will happen with this proposal in place during firstboot?
...
> What will happen to files like /etc/ignition-machine-config-encapsulated.json, will it be written to current deployment or in new deployment?

That's a good question.  Note that today, it's Ignition which writes the initial files, *not* the MCD.  So unless we changed how Ignition works too, the answer would be that the files are written in the current root.

And in fact, we *need* this to happen because we need the pull secret `/var/lib/kubelet/config.json` in the *current* root so that `podman` can pull the oscontainer.  (In general, we need other configs for that too too, such as any image content source policy, certificates, proxy config etc.)

I think it's OK if we only do this "transactional /etc" for MCD upgrades, because that's where we're actually doing an upgrade, and we have a workload running on the cluster.

**Comment by cgwalters** [comment]
> Also a prerequisite is moving the pull secret from /var into /etc - and in general, all MachineConfig changes.

Eh, thinking about this more it's not a hard dependency - we can just make changes to `/etc` transactional, and say that things outside of it aren't.  In practice, the pull secret doesn't change often or in an incompatible way.  What we need is transactional changes for the static pods etc. which should be in `/etc`.

**Comment by sinnykumari** [comment]
> That's a good question. Note that today, it's Ignition which writes the initial files, _not_ the MCD. So unless we changed how Ignition works too, the answer would be that the files are written in the current root.

Ah right, makes sense to me now. thanks for the explanation.

**Comment by cgwalters** [comment]
Dropping this here for lack of a better place: A much bigger path we could take would be to have the MCO build a *derived* OSTree commit from the rendered MachineConfig (like as a build process) and serve that to other nodes in the cluster.  This means we're not going into each node and changing config files (or things like the `kernel-rt` overrides) and also leads more strongly towards having `/etc` mounted read-only by default.

But going this path takes us entirely away from supporting traditional RHEL - so we'd also need to do https://github.com/openshift/machine-config-operator/issues/1592

**Comment by cgwalters** [comment]
xref https://github.com/ostreedev/ostree/issues/2220

**Comment by cgwalters** [comment]
Also of note, rpm-ostree is getting closer to stabilizing our "apply-live" code, xref https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/MQWBKRFCYH2GB3CW5CG722RGQAEPHHAN/ - once that happens we can also support e.g. live-applying a subset of the changes to `/etc` - and as well potentially things like "just cherry pick the new kubelet package" and take the kernel update downtime later.
