### ISSUE TITLE
Booting in FIPS mode day-1 causes errors on firstboot

### ISSUE THREAD

**Issue by jlebon** [openshift/machine-config-operator#1250]
```
Nov 07 17:12:13 fips-test-k7v7d-master-0.fips-test.jlebon.testing systemd[1]: Starting Machine Config Daemon Firstboot...
Nov 07 17:12:13 fips-test-k7v7d-master-0.fips-test.jlebon.testing machine-config-daemon[2031]: I1107 17:12:13.508185    2031 rpm-ostree.go:365] Running captured: rpm-ostree status --json
Nov 07 17:12:14 fips-test-k7v7d-master-0.fips-test.jlebon.testing machine-config-daemon[2031]: I1107 17:12:14.133618    2031 daemon.go:209] Booted osImageURL:  (43.81.201911071657.0)
Nov 07 17:12:14 fips-test-k7v7d-master-0.fips-test.jlebon.testing machine-config-daemon[2031]: I1107 17:12:14.134321    2031 update.go:233] Checking Reconcilable for config mco-empty-mc to rendered-master-db1384e29eb0129eab71e6600e7f291f
Nov 07 17:12:14 fips-test-k7v7d-master-0.fips-test.jlebon.testing machine-config-daemon[2031]: I1107 17:12:14.134370    2031 update.go:1065] Starting update from mco-empty-mc to rendered-master-db1384e29eb0129eab71e6600e7f291f: &{osUpdate:true kargs:false fips:true passwd:>
Nov 07 17:12:14 fips-test-k7v7d-master-0.fips-test.jlebon.testing machine-config-daemon[2031]: I1107 17:12:14.149312    2031 update.go:592] Updating files
Nov 07 17:12:14 fips-test-k7v7d-master-0.fips-test.jlebon.testing machine-config-daemon[2031]: I1107 17:12:14.149331    2031 update.go:611] Deleting stale data
Nov 07 17:12:14 fips-test-k7v7d-master-0 machine-config-daemon[2031]: I1107 17:12:14.296912    2031 update.go:592] Updating files
Nov 07 17:12:14 fips-test-k7v7d-master-0 machine-config-daemon[2031]: I1107 17:12:14.296935    2031 update.go:611] Deleting stale data
Nov 07 17:12:14 fips-test-k7v7d-master-0 machine-config-daemon[2031]: error: Cannot enable FIPS after firstboot
Nov 07 17:12:14 fips-test-k7v7d-master-0 systemd[1]: machine-config-daemon-firstboot.service: Main process exited, code=exited, status=1/FAILURE
Nov 07 17:12:14 fips-test-k7v7d-master-0 systemd[1]: machine-config-daemon-firstboot.service: Failed with result 'exit-code'.
Nov 07 17:12:14 fips-test-k7v7d-master-0 systemd[1]: Failed to start Machine Config Daemon Firstboot.
Nov 07 17:12:14 fips-test-k7v7d-master-0 systemd[1]: machine-config-daemon-firstboot.service: Consumed 143ms CPU time
```

I think the issue here is that we're comparing against an empty MC, so `oldConfig.Spec.FIPS` will always be `false`.

Seems like we want the MCD to actually read the FIPS state from the node. There's `fips-mode-setup --check` which would be nice, though it needs patches that I haven't pushed upstream yet.

**Comment by jlebon** [comment]
Probably safer anyway to do:

1. check for `fips=1` karg
2. check that `/proc/sys/crypto/fips_enabled` is `1`
3. check that `update-crypto-policies --show` is `FIPS` (or read it from its config in `/etc`)

**Comment by cgwalters** [comment]
Hmm...I think we shouldn't do the fips check here in firstboot.

**Comment by cgwalters** [comment]
> Seems like we want the MCD to actually read the FIPS state from the node. 

Yes...this has come up before.  Similar with kernel arguments.  One reason we don't do this right now for *files* is because https://github.com/openshift/machine-config-operator/pull/245

Basically the MCD is oriented around transitioning between state A and state B - if we're not in state A, then something deeper went wrong.

**Comment by yuqi-zhang** [comment]
In the day 1 setup we're aiming for, would we even want to have FIPS managed by the MCD?

I think the actual error above is because we removed the `coreos-fips` package. Which I assume means that we don't want the MCO messing with fips? In which case why have MCO touch FIPS at all

**Comment by jlebon** [comment]
Right yeah, we should nuke all references to `coreos-fips`.

> Basically the MCD is oriented around transitioning between state A and state B - if we're not in state A, then something deeper went wrong.

Ahh OK, I was looking at #904. Do I understand correctly that the firstboot service is meant to handle everything that is *not* pure Ignition? (So basically, OS image + kargs + FIPS?)

> Hmm...I think we shouldn't do the fips check here in firstboot.

But we do effectively check that the OS image and kargs match right? Why wouldn't we do the same for FIPS?

**Comment by cgwalters** [comment]
> Do I understand correctly that the firstboot service is meant to handle everything that is not pure Ignition? (So basically, OS image + kargs + FIPS?)

Exactly.  (Now not FIPS because that's done in the initramfs, but this circles back to...conceptually RHCOS has "builtin MachineConfig" handling)

**Comment by cgwalters** [comment]
> But we do effectively check that the OS image and kargs match right? 

Checking for osimage match is easy, so yeah we do that.  We also don't expect anything else to be modifying the osimage.

But, we don't today inspect the "active" kargs, just look at current+desired MCs.  (Where "current" is what the node annotations say, not what e.g. `rpm-ostree kargs` outputs)

**Comment by jlebon** [comment]
OK, so I think this ties into the discussions from https://github.com/openshift/installer/issues/2634. The question is essentially "should FIPS mode be something the MCO cares about at all" ? I think the messy part about this is that machine configs are also used by sysadmins, so we're exposing a knob but don't want anyone to touch it.

**Comment by yuqi-zhang** [comment]
Right I'm in favour of the installer passing the knob to the bootstrap + served machines. My original intention was that the MCD should no longer have any knowledge at all of FIPS (i.e. we no longer check for FIPs during updates/firstboot/anywhere). But now thinking about it a bit more, maybe it should be there to sanity check, and for sysadmins to view?

Anyways let me fix up the monkey patch and we can discuss further in the installer thread.

**Comment by ericavonb** [comment]
I noticed this earlier, but was about to close the pr since I thought we were moving away from MCO mutating FIPs on already booted nodes.

https://github.com/openshift/machine-config-operator/pull/1013

**Comment by cgwalters** [comment]
> But now thinking about it a bit more, maybe it should be there to sanity check, and for sysadmins to view?

That's what I was [arguing here](https://github.com/openshift/installer/issues/2634#issuecomment-551107660) yes.

But to be clear if people think it's simpler for the MCO to just ignore FIPS...OK.  But I personally would prefer the direction this PR is going.

**Comment by ericavonb** [comment]
> But now thinking about it a bit more, maybe it should be there to sanity check, and for sysadmins to view?

Surfacing this kind of info (fips enabled or not on node) to admins seems to fit very well with the purpose for the node-feature-discovery operator:
- https://github.com/kubernetes-sigs/node-feature-discovery
- https://github.com/openshift/cluster-nfd-operator

Using the nfd would decouple the MCO any the specifics, should be a simple plugin to build (or literally just dropping a file in the right format), and is upstream-first!
