### ISSUE TITLE
Modification of kargs generates an invalid command

### ISSUE THREAD

**Issue by yrobla** [openshift/machine-config-operator#1265]
I am using a machineconfig with kernel args feature. I have one setting that is to add number of huge pages, and i wanted to modify it. To do that, i modified a manifest from:
spec:
    kernelArguments:
        - default_hugepagesz=1G
        - hugepagesz=1G
        - hugepages=32

To:
spec:
    kernelArguments:
        - default_hugepagesz=1G
        - hugepagesz=1G
        - hugepages=4

When machine config applies that, it generates this command:
rpm-ostree kargs --delete=hugepages=32 --delete=idle=poll --append=hugepages=4

That is throwing the error:
 Cannot specify both --delete and --append

Machineconfig should be aware of that, and generate those delete/append commands in different calls.

**Comment by cgwalters** [comment]
Thanks for reporting this!  Seems clearly and rpm-ostree bug.

**Comment by cgwalters** [comment]
PR at https://github.com/coreos/rpm-ostree/pull/1940

**Comment by slintes** [comment]
Hi @cgwalters, can you please give an update on this? We are still running into this on OCP 4.4 nightly, even though it was fixed in rpm-ostree quite a while ago.

**Comment by cgwalters** [comment]
This is waiting on a RHEL8.2 rebase for RHCOS currently.

**Comment by slintes** [comment]
thx... according to another source that won't happen for OCP 4.4 anymore :/

**Comment by sinnykumari** [comment]
From the [ci run](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/2000/pull-ci-openshift-machine-config-operator-release-4.4-e2e-gcp-op/1293162919424430080/artifacts/e2e-gcp-op/pods/openshift-machine-config-operator_machine-config-daemon-5zdjh_machine-config-daemon.log) , it seems we are using 8.2 content in 4.4 

```
* pivot://registry.svc.ci.openshift.org/ci-op-30sidti8/stable@sha256:8422282bd6e47b02de64895de15aa866a7c53cd78738a907553800363569849e
              CustomOrigin: Managed by machine-config-operator
                   Version: 44.82.202008110146-0 (2020-08-11T01:52:01Z)
```
`44.82.202008110146-0` version has `rpm-ostree-2019.6-8.el8` which contains the fixes from https://github.com/coreos/rpm-ostree/pull/1940 .

Can you please confirm if kargs works as expected on your 4.4 updated cluster?

**Comment by sinnykumari** [comment]
@slintes @yrobla https://github.com/openshift/machine-config-operator/issues/1265#issuecomment-675449897

**Comment by slintes** [comment]
Hey @sinnykumari, I switched projects and don't use this anymore.
@cynepco3hahue can you have a look please?

**Comment by fromanirh** [comment]
@dshchedr maybe we can retry to see if the fix is working for us?

**Comment by dshchedr** [comment]
Yep, it works on OCP 4.4.15:

```
[root@worker-0 ~]# cat /proc/cmdline 
... default_hugepagesz=1G

[root@worker-0 ~]# rpm-ostree kargs --delete=default_hugepagesz=1G --append=default_hugepagesz=2M
Checking out tree 179286c... done
Resolving dependencies... done
Applying 4 overrides and 3 overlays
Processing packages... done
Running pre scripts... done
Running post scripts... done
Running posttrans scripts... done
Writing rpmdb... done
Generating initramfs... done
Writing OSTree commit... done
Staging deployment... done
Kernel arguments updated.
Run "systemctl reboot" to start a reboot
.
[root@worker-0 ~]# systemctl reboot
.
[root@worker-0 ~]# cat /proc/cmdline 
..... default_hugepagesz=2M

```

**Comment by sinnykumari** [comment]
Thanks Denys for confirming!
