### ISSUE TITLE
MCD: pods are crashlooping

### ISSUE THREAD

**Issue by abhinavdahiya** [openshift/machine-config-operator#127]
@sallyom reported that all the mcd pods are crashlooping.

```console
installer(master)$ oc logs machine-config-daemon-5d862 -n openshift-machine-config-operator
I1015 15:56:56.802774    5350 start.go:42] Version: 3.11.0-152-g0fe65acd-dirty
I1015 15:56:56.828854    5350 run.go:22] Running captured: chroot /rootfs rpm-ostree status --json
W1015 15:56:56.884945    5350 rpm-ostree.go:88] Working around "://dummy" OS image URL until installer ➰ pivots
I1015 15:56:56.885256    5350 daemon.go:81] Booted osImageURL: ://dummy (4.0.6844)
I1015 15:56:56.885341    5350 start.go:85] Calling chroot("/rootfs")
I1015 15:56:56.885424    5350 daemon.go:101] Starting MachineConfigDaemon
I1015 15:56:56.893192    5350 daemon.go:110] Shutting down MachineConfigDaemon
F1015 15:56:56.893217    5350 start.go:99] failed to run: Node is degraded; exiting loudly...
```

/cc @sdemos

**Comment by jlebon** [comment]
Hmm, OK just had reports of this internally as well. Odd though, since that logic hasn't changed recently. Will look into it.

**Comment by ashcrow** [comment]
Looks related to https://github.com/openshift/machine-config-operator/pull/121

**Comment by ashcrow** [comment]
I could see this happening if the [node was previously marked degraded](https://github.com/openshift/machine-config-operator/pull/121/files#diff-06b532a2a5a5d3ad1d5341b3e00945efR105)

**Comment by jlebon** [comment]
Ahh OK, sorry for the confusion. This is indeed not the same thing as was reported internally with handling of `://dummy` URLs.

> If so the exit is expected, but since Openshift is rescheduling over and over it's crash looping.

Right, though right now aren't we the only operators that set the degraded label? So it must have encountered an error in a previous run. Will try to reproduce this though `oc logs -p` from someone who's hitting this would help.

**Comment by sdemos** [comment]
> Right, though right now aren't we the only operators that set the degraded label?

We should be, I'm pretty sure that the MCD owns the node status field entirely so if anything else is writing to it it's a problem. However, even if that is the case, (unfortunately) right now crash-looping is the name of the game until we get the work described in #109.

Is the issue that they are crashlooping like this on nodes that aren't currently set to degraded? I'm confused about what the bug is.

**Comment by jlebon** [comment]
Hmm, maybe the correct behaviour here until we actually use taints is to just sleep instead of exiting immediately so that we don't clobber `logs -p` output on the real failure.

**Comment by ashcrow** [comment]
Yeah. I think `time.Sleep` (see pastebins from earlier) would be a good workaround for now.

**Comment by jlebon** [comment]
So, I can reproduce this. But the issue is that the logs indeed are clobbered. So it's still not clear what the actual error is. #129 should help but until that makes it to the latest installer image, I'm trying to figure out how to point the installer at a custom container containing that patch.

**Comment by jlebon** [comment]
This should be fixed by https://github.com/openshift/machine-config-operator/pull/131.
