### ISSUE TITLE
Split rendered machineconfigs from users provided

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#1286]
(I failed at finding a similar issue in the repo but I can swear I saw one at some point, that's why I'm creating this so if you're aware of an already existing issue open, let's close this)

As an openshift administrator I don't want `oc get machineconfigs` to include `rendered-` MCs as they cannot be directly modified and are MCC generated.

Acceptance criteria:

- verify `rendered-` MCs aren't included in `oc get machineconfigs`
- verify a new CRD (or something else?) owns them
- verify everything works correctly as before ofc

**Comment by kikisdeliveryservice** [comment]
how will a user actually see the rendered-config?  bc the rendered-config is the source of truth of the state of the mcp?

**Comment by kikisdeliveryservice** [comment]
couldn't we just skip allowing edits of the rendered config instead and display a message that that config is autogenerated and cannot be modified?

**Comment by kikisdeliveryservice** [comment]
we could also add to the new rendered-XXX yamls a comment header saying that this is autogenerated and to not modify

**Comment by sinnykumari** [comment]
Responding with my current understanding, correct me if it's not right.

I was thinking, maybe we can have a new CRD with spec:name:kind RenderedMachineConfig and user can see it with `oc get renderedmachineconfig` .

Another advantage of separating Rendered MachineConfig could be - over a period of time, I think rendered config in a cluster will keep on growing, unless MCO cleans up older one(not sure if we do that?). Showing both editable and MCC generated config can make list long when you run `oc get machineconfig`. Keeping them separate makes things cleaner.

**Comment by runcom** [comment]
> I was thinking, maybe we can have a new CRD with spec:name:kind RenderedMachineConfig and user can see it with `oc get renderedmachineconfig` .

this is indeed a suggestion that came from Alex as well, might be worth syncing with him as well

**Comment by sinnykumari** [comment]
@crawford thoughts?

**Comment by cgwalters** [comment]
One potentially tricky thing with this is handling upgrades - and further, downgrades may become much harder.

**Comment by ericavonb** [comment]
@cgwalters thinking about it, since the rendered MCs can always be recreated from the other MCs (which should continue to be the case whether the rendered mcs are made their own type or not), I think it may be less of a problem than other resources. there may be a transient failure period where an MCD tries to pull the wrong type but I think it'll "just" start working once the MCC gets upgraded/downgraded appropriately.

**Comment by crawford** [comment]
We could also throw the rendered MachineConfigs into another namespace. This _feels_ like it's a low priority though, so I'm not sure if we should worry about this right now. We might be able to solve it as a part of the move to a more abstract (human friendly) configuration.

**Comment by ericavonb** [comment]
MCs aren't namespaced currently

**Comment by kikisdeliveryservice** [comment]
> This _feels_ like it's a low priority though, so I'm not sure if we should worry about this right now. We might be able to solve it as a part of the move to a more abstract (human friendly) configuration.
Agree and would be onboard with this approach.
