### ISSUE TITLE
centos 7 node goes in continuous reboots

### ISSUE THREAD

**Issue by yrobla** [openshift/machine-config-operator#1294]
This is an issue i had with rhel8/centos8 nodes, but now i hit the same with centos7. The problem is that node is continuously rebooting due to machineconfig.
From what i could see, the issue is that update on a non-rhcos node is never marked as done, node is rebooted in Working state, and is never changing its currentConfig annotation.
The way i manage to stop the reboots is to manually edit the node, and set:
machineconfiguration.openshift.io/state: Done
machineconfiguration.openshift.io/currentConfig -> same as machineconfiguration.openshift.io/desiredConfig

I attach the logs of the first and second run of the machineconfigdaemon, where you can see that clearly the second run is bad:
Checking Reconcilable for config rendered-worker-rt-69b2580891eabb9c50effa32987f0a29 to rendered-worker-rt-69b2580891eabb9c50effa32987f0a29

What i also can see is that node is never marked as Done, as happens with rhcos workers:
I1128 10:19:46.911792    4290 daemon.go:268] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"testing-worker-1", UID:"4e3c1d54-11c2-11ea-b824-ac1f6b7bea24", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeDone' Setting node testing-worker-1, currentConfig rendered-worker-1986e3aa30ed6b0de18aca154f7797cb to Done

That is never seen on non-rhcos

**Comment by yrobla** [comment]
[root@testing-worker-0 core]# crictl logs -f 395b180b9a588
I1128 11:00:24.083429    4211 start.go:65] Options parsed: {kubeconfig: nodeName: rootMount:/rootfs onceFrom: skipReboot:false fromIgnition:false kubeletHealthzEnabled:true kubeletHealthzEndpoint:http://localhost:10248/healthz}
I1128 11:00:24.085398    4211 start.go:68] Version: v4.2.8-201911190952-dirty (55bb5fc17da0c3d76e4ee6a55732f0cba93e8520)
I1128 11:00:24.104001    4211 start.go:78] Calling chroot("/rootfs")
I1128 11:00:24.104025    4211 start.go:83] Moving to / inside the chroot
I1128 11:00:24.104573    4211 builder.go:72] Using in-cluster kube client config
I1128 11:00:24.108243    4211 update.go:984] Starting to manage node: testing-worker-0
I1128 11:00:24.110170    4211 daemon.go:542] Detected a new login session: New session 1 of user core.
I1128 11:00:24.110184    4211 daemon.go:543] Login access is discouraged! Applying annotation: machineconfiguration.openshift.io/ssh
I1128 11:00:24.111861    4211 rpm-ostree.go:356] Running captured: journalctl --list-boots
I1128 11:00:24.114016    4211 daemon.go:722] journalctl --list-boots:
 0 79196def98c84a76ac6c0a7cd778f051 Thu 2019-11-28 10:59:57 UTC—Thu 2019-11-28 11:00:24 UTC
I1128 11:00:24.114028    4211 daemon.go:480] Starting MachineConfigDaemon
I1128 11:00:24.114111    4211 daemon.go:487] Enabling Kubelet Healthz Monitor
E1128 11:00:30.122012    4211 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Node: Get https://172.30.0.1:443/api/v1/nodes?limit=500&resourceVersion=0: dial tcp 172.30.0.1:443: connect: no route to host
E1128 11:00:30.122046    4211 reflector.go:126] github.com/openshift/machine-config-operator/pkg/generated/informers/externalversions/factory.go:101: Failed to list *v1.MachineConfig: Get https://172.30.0.1:443/apis/machineconfiguration.openshift.io/v1/machineconfigs?limit=500&resourceVersion=0: dial tcp 172.30.0.1:443: connect: no route to host
W1128 11:00:31.214264    4211 daemon.go:508] Got an error from auxiliary tools: error: cannot apply annotation for SSH access due to: unable to update node "nil": node "testing-worker-0" not found
I1128 11:00:31.332893    4211 daemon.go:1010] Updating Node testing-worker-0
I1128 11:00:32.333207    4211 daemon.go:332] Started syncing node "testing-worker-0" (2019-11-28 11:00:32.33316697 +0000 UTC m=+8.346251976)
I1128 11:00:32.337811    4211 daemon.go:678] Current config: rendered-worker-1986e3aa30ed6b0de18aca154f7797cb
I1128 11:00:32.337824    4211 daemon.go:679] Desired config: rendered-worker-rt-69b2580891eabb9c50effa32987f0a29
I1128 11:00:32.340081    4211 daemon.go:418] Detected a login session before the daemon took over on first boot
I1128 11:00:32.340096    4211 daemon.go:419] Applying annotation: machineconfiguration.openshift.io/ssh
I1128 11:00:32.348463    4211 update.go:984] Disk currentConfig rendered-worker-rt-69b2580891eabb9c50effa32987f0a29 overrides node annotation rendered-worker-1986e3aa30ed6b0de18aca154f7797cb
I1128 11:00:32.351032    4211 daemon.go:892] Validating against current config rendered-worker-rt-69b2580891eabb9c50effa32987f0a29
I1128 11:00:32.351062    4211 daemon.go:1183] Not booted into Red Hat CoreOS, ignoring target OSImageURL quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:410778c1c5375c3a9cc7cbe23c12fdafe2a1b702d09a3ec8376a7d5e009b4d08
I1128 11:00:32.354204    4211 daemon.go:902] Validated on-disk state
I1128 11:00:32.354226    4211 daemon.go:949] In desired config rendered-worker-rt-69b2580891eabb9c50effa32987f0a29
I1128 11:00:32.354236    4211 daemon.go:334] Finished syncing node "testing-worker-0" (21.06542ms)
I1128 11:00:35.037082    4211 daemon.go:1010] Updating Node testing-worker-1
I1128 11:00:36.037311    4211 daemon.go:332] Started syncing node "testing-worker-1" (2019-11-28 11:00:36.03730036 +0000 UTC m=+12.050385327)
I1128 11:00:36.037343    4211 daemon.go:334] Finished syncing node "testing-worker-1" (40.4µs)
I1128 11:00:38.771976    4211 daemon.go:1010] Updating Node testing-worker-0
I1128 11:00:38.781454    4211 daemon.go:1010] Updating Node testing-worker-0
I1128 11:00:39.013397    4211 daemon.go:1010] Updating Node testing-worker-0
I1128 11:00:39.772146    4211 daemon.go:332] Started syncing node "testing-worker-0" (2019-11-28 11:00:39.772135926 +0000 UTC m=+15.785220875)
I1128 11:00:39.779109    4211 update.go:196] Checking Reconcilable for config rendered-worker-rt-69b2580891eabb9c50effa32987f0a29 to rendered-worker-rt-69b2580891eabb9c50effa32987f0a29
I1128 11:00:39.783713    4211 update.go:419] Configs are reconcilable
I1128 11:00:39.783907    4211 update.go:984] Starting update from rendered-worker-rt-69b2580891eabb9c50effa32987f0a29 to rendered-worker-rt-69b2580891eabb9c50effa32987f0a29: &{osUpdate:false kargs:false fips:false passwd:false files:false units:false}
I1128 11:00:39.786603    4211 update.go:512] Updating files
I1128 11:00:39.786621    4211 update.go:720] Writing file "/etc/pki/ca-trust/source/anchors/openshift-config-user-ca-bundle.crt"
I1128 11:00:39.789599    4211 update.go:720] Writing file "/etc/tmpfiles.d/cleanup-cni.conf"
I1128 11:00:39.791845    4211 update.go:720] Writing file "/etc/systemd/system/crio.service.d/10-default-env.conf"
I1128 11:00:39.794219    4211 update.go:720] Writing file "/etc/systemd/system/kubelet.service.d/10-default-env.conf"
I1128 11:00:39.796315    4211 update.go:720] Writing file "/etc/systemd/system/machine-config-daemon-host.service.d/10-default-env.conf"
I1128 11:00:39.798242    4211 update.go:720] Writing file "/etc/systemd/system/pivot.service.d/10-default-env.conf"
I1128 11:00:39.800297    4211 update.go:720] Writing file "/etc/kubernetes/kubelet-ca.crt"
I1128 11:00:39.802969    4211 update.go:720] Writing file "/etc/systemd/system.conf.d/kubelet-cgroups.conf"
I1128 11:00:39.805281    4211 update.go:720] Writing file "/var/lib/kubelet/config.json"
I1128 11:00:39.807708    4211 update.go:720] Writing file "/etc/kubernetes/ca.crt"
I1128 11:00:39.810072    4211 update.go:720] Writing file "/etc/sysctl.d/forward.conf"
I1128 11:00:39.812231    4211 update.go:720] Writing file "/etc/sysctl.d/inotify.conf"
I1128 11:00:39.814157    4211 update.go:720] Writing file "/etc/kubernetes/kubelet-plugins/volume/exec/.dummy"
I1128 11:00:39.816517    4211 update.go:720] Writing file "/etc/containers/registries.conf"
I1128 11:00:39.818542    4211 update.go:720] Writing file "/etc/containers/storage.conf"
I1128 11:00:39.822067    4211 update.go:720] Writing file "/etc/crio/crio.conf"
I1128 11:00:39.824683    4211 update.go:720] Writing file "/etc/containers/policy.json"
I1128 11:00:39.827075    4211 update.go:720] Writing file "/etc/kubernetes/cloud.conf"
I1128 11:00:39.830570    4211 update.go:720] Writing file "/etc/kubernetes/kubelet.conf"
I1128 11:00:39.832748    4211 update.go:720] Writing file "/etc/NetworkManager/conf.d/10-worker-nm-disable-auto-config.conf"
I1128 11:00:39.835194    4211 update.go:720] Writing file "/etc/sysconfig/network-scripts/ifcfg-eno1"
I1128 11:00:39.837907    4211 update.go:720] Writing file "/etc/sysconfig/network-scripts/ifcfg-eno2"
I1128 11:00:39.841201    4211 update.go:720] Writing file "/etc/kubernetes/kubelet.conf"
I1128 11:00:39.843553    4211 update.go:720] Writing file "/opt/setup_rt.sh"
I1128 11:00:39.848681    4211 update.go:720] Writing file "/etc/tuned/realtime-variables.conf"
I1128 11:00:39.852932    4211 update.go:675] Writing systemd unit "machine-config-daemon-host.service"
I1128 11:00:39.854896    4211 update.go:682] Successfully wrote systemd unit "machine-config-daemon-host.service": 
I1128 11:00:39.854911    4211 update.go:692] Enabling systemd unit "machine-config-daemon-host.service"
I1128 11:00:39.854939    4211 update.go:613] /etc/systemd/system/multi-user.target.wants/machine-config-daemon-host.service already exists. Not making a new symlink
I1128 11:00:39.854945    4211 update.go:704] Enabled systemd unit "machine-config-daemon-host.service"
I1128 11:00:39.854951    4211 update.go:675] Writing systemd unit "kubelet.service"
I1128 11:00:39.856977    4211 update.go:682] Successfully wrote systemd unit "kubelet.service": 
I1128 11:00:39.856991    4211 update.go:692] Enabling systemd unit "kubelet.service"
I1128 11:00:39.857011    4211 update.go:613] /etc/systemd/system/multi-user.target.wants/kubelet.service already exists. Not making a new symlink
I1128 11:00:39.857017    4211 update.go:704] Enabled systemd unit "kubelet.service"
I1128 11:00:39.857022    4211 update.go:675] Writing systemd unit "install_realtime.service"
I1128 11:00:39.858943    4211 update.go:682] Successfully wrote systemd unit "install_realtime.service": 
I1128 11:00:39.858958    4211 update.go:692] Enabling systemd unit "install_realtime.service"
I1128 11:00:39.858981    4211 update.go:613] /etc/systemd/system/multi-user.target.wants/install_realtime.service already exists. Not making a new symlink
I1128 11:00:39.858987    4211 update.go:704] Enabled systemd unit "install_realtime.service"
I1128 11:00:39.858993    4211 update.go:531] Deleting stale data
I1128 11:00:39.859021    4211 update.go:812] Writing SSHKeys at "/home/core/.ssh/authorized_keys"
I1128 11:00:39.860955    4211 update.go:818] Wrote SSHKeys at /home/core/.ssh/authorized_keys
I1128 11:00:39.863711    4211 update.go:847] Updating of non RHCOS nodes are not supported
I1128 11:00:39.866023    4211 update.go:984] Update prepared; beginning drain
I1128 11:00:39.866106    4211 daemon.go:268] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"testing-worker-0", UID:"3c9b6b4f-11c7-11ea-b824-ac1f6b7bea24", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'PendingConfig' Written pending config rendered-worker-rt-69b2580891eabb9c50effa32987f0a29
I1128 11:00:39.868526    4211 daemon.go:268] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"testing-worker-0", UID:"3c9b6b4f-11c7-11ea-b824-ac1f6b7bea24", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'Drain' Draining node to update config.
I1128 11:00:40.695620    4211 update.go:93] ignoring DaemonSet-managed pods: virt-handler-69tg6, ocp4x-ptp-ngrx8, dns-default-cwgsf, node-ca-pbgz9, machine-config-daemon-8llj2, node-exporter-wsj9c, multus-wv5wp, nfd-worker-2vj4g, ovs-79rxm, sdn-7gqfb, csi-cephfsplugin-h9w4l, csi-rbdplugin-8bkqc, rook-ceph-agent-26cfh, rook-discover-hphw5
I1128 11:00:40.695642    4211 update.go:89] drained node "testing-worker-0"
I1128 11:00:40.695671    4211 update.go:984] drain complete
I1128 11:00:40.698391    4211 update.go:984] initiating reboot: Node will reboot into config rendered-worker-rt-69b2580891eabb9c50effa32987f0a29
I1128 11:00:40.698560    4211 daemon.go:268] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"testing-worker-0", UID:"3c9b6b4f-11c7-11ea-b824-ac1f6b7bea24", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'Reboot' Node will reboot into config rendered-worker-rt-69b2580891eabb9c50effa32987f0a29
Connection to testing-worker-0.testing.baremetal.edge-sites.net closed by remote host.
Connection to testing-worker-0.testing.baremetal.edge-sites.net closed.



 crictl logs -f 01705154ed682
I1128 11:06:03.569888    5793 start.go:65] Options parsed: {kubeconfig: nodeName: rootMount:/rootfs onceFrom: skipReboot:false fromIgnition:false kubeletHealthzEnabled:true kubeletHealthzEndpoint:http://localhost:10248/healthz}
I1128 11:06:03.569996    5793 start.go:68] Version: v4.2.8-201911190952-dirty (55bb5fc17da0c3d76e4ee6a55732f0cba93e8520)
I1128 11:06:03.575323    5793 start.go:78] Calling chroot("/rootfs")
I1128 11:06:03.575342    5793 start.go:83] Moving to / inside the chroot
I1128 11:06:03.575827    5793 builder.go:72] Using in-cluster kube client config
I1128 11:06:03.582030    5793 update.go:984] Starting to manage node: testing-worker-0
I1128 11:06:03.584356    5793 daemon.go:542] Detected a new login session: New session 1 of user core.
I1128 11:06:03.584371    5793 daemon.go:543] Login access is discouraged! Applying annotation: machineconfiguration.openshift.io/ssh
I1128 11:06:03.586227    5793 rpm-ostree.go:356] Running captured: journalctl --list-boots
I1128 11:06:03.588506    5793 daemon.go:722] journalctl --list-boots:
 0 cd3a7b9c7c2b4cfc819ebfc6fbc71cc8 Thu 2019-11-28 11:05:36 UTC—Thu 2019-11-28 11:06:03 UTC
I1128 11:06:03.588520    5793 daemon.go:480] Starting MachineConfigDaemon
I1128 11:06:03.588683    5793 daemon.go:487] Enabling Kubelet Healthz Monitor
E1128 11:06:09.596768    5793 reflector.go:126] github.com/openshift/machine-config-operator/pkg/generated/informers/externalversions/factory.go:101: Failed to list *v1.MachineConfig: Get https://172.30.0.1:443/apis/machineconfiguration.openshift.io/v1/machineconfigs?limit=500&resourceVersion=0: dial tcp 172.30.0.1:443: connect: no route to host
E1128 11:06:09.596768    5793 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Node: Get https://172.30.0.1:443/api/v1/nodes?limit=500&resourceVersion=0: dial tcp 172.30.0.1:443: connect: no route to host
W1128 11:06:10.688826    5793 daemon.go:508] Got an error from auxiliary tools: error: cannot apply annotation for SSH access due to: unable to update node "nil": node "testing-worker-0" not found
I1128 11:06:16.382050    5793 daemon.go:1010] Updating Node testing-worker-0
I1128 11:06:16.398567    5793 daemon.go:1010] Updating Node testing-worker-0
I1128 11:06:17.382209    5793 daemon.go:332] Started syncing node "testing-worker-0" (2019-11-28 11:06:17.382187279 +0000 UTC m=+13.904377972)
I1128 11:06:17.386806    5793 daemon.go:678] Current config: rendered-worker-1986e3aa30ed6b0de18aca154f7797cb
I1128 11:06:17.386820    5793 daemon.go:679] Desired config: rendered-worker-rt-69b2580891eabb9c50effa32987f0a29
I1128 11:06:17.389051    5793 daemon.go:418] Detected a login session before the daemon took over on first boot
I1128 11:06:17.389069    5793 daemon.go:419] Applying annotation: machineconfiguration.openshift.io/ssh
I1128 11:06:17.398102    5793 update.go:984] Disk currentConfig rendered-worker-rt-69b2580891eabb9c50effa32987f0a29 overrides node annotation rendered-worker-1986e3aa30ed6b0de18aca154f7797cb
I1128 11:06:17.400805    5793 daemon.go:892] Validating against current config rendered-worker-rt-69b2580891eabb9c50effa32987f0a29
I1128 11:06:17.400840    5793 daemon.go:1183] Not booted into Red Hat CoreOS, ignoring target OSImageURL quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:410778c1c5375c3a9cc7cbe23c12fdafe2a1b702d09a3ec8376a7d5e009b4d08
I1128 11:06:17.404710    5793 daemon.go:902] Validated on-disk state
I1128 11:06:17.404751    5793 daemon.go:949] In desired config rendered-worker-rt-69b2580891eabb9c50effa32987f0a29
I1128 11:06:17.404767    5793 daemon.go:334] Finished syncing node "testing-worker-0" (22.574641ms)
I1128 11:06:19.510446    5793 daemon.go:1010] Updating Node testing-worker-0
I1128 11:06:20.510613    5793 daemon.go:332] Started syncing node "testing-worker-0" (2019-11-28 11:06:20.510602542 +0000 UTC m=+17.032793232)
I1128 11:06:20.518302    5793 update.go:196] Checking Reconcilable for config rendered-worker-rt-69b2580891eabb9c50effa32987f0a29 to rendered-worker-rt-69b2580891eabb9c50effa32987f0a29
I1128 11:06:20.521014    5793 update.go:419] Configs are reconcilable
I1128 11:06:20.521192    5793 update.go:984] Starting update from rendered-worker-rt-69b2580891eabb9c50effa32987f0a29 to rendered-worker-rt-69b2580891eabb9c50effa32987f0a29: &{osUpdate:false kargs:false fips:false passwd:false files:false units:false}
I1128 11:06:20.523765    5793 update.go:512] Updating files
I1128 11:06:20.523789    5793 update.go:720] Writing file "/etc/pki/ca-trust/source/anchors/openshift-config-user-ca-bundle.crt"
I1128 11:06:20.526569    5793 update.go:720] Writing file "/etc/tmpfiles.d/cleanup-cni.conf"
I1128 11:06:20.528745    5793 update.go:720] Writing file "/etc/systemd/system/crio.service.d/10-default-env.conf"
I1128 11:06:20.530972    5793 update.go:720] Writing file "/etc/systemd/system/kubelet.service.d/10-default-env.conf"
I1128 11:06:20.532987    5793 update.go:720] Writing file "/etc/systemd/system/machine-config-daemon-host.service.d/10-default-env.conf"
I1128 11:06:20.535029    5793 update.go:720] Writing file "/etc/systemd/system/pivot.service.d/10-default-env.conf"
I1128 11:06:20.537208    5793 update.go:720] Writing file "/etc/kubernetes/kubelet-ca.crt"
I1128 11:06:20.539683    5793 update.go:720] Writing file "/etc/systemd/system.conf.d/kubelet-cgroups.conf"
I1128 11:06:20.541836    5793 update.go:720] Writing file "/var/lib/kubelet/config.json"
I1128 11:06:20.544349    5793 update.go:720] Writing file "/etc/kubernetes/ca.crt"
I1128 11:06:20.546752    5793 update.go:720] Writing file "/etc/sysctl.d/forward.conf"
I1128 11:06:20.548972    5793 update.go:720] Writing file "/etc/sysctl.d/inotify.conf"
I1128 11:06:20.551154    5793 update.go:720] Writing file "/etc/kubernetes/kubelet-plugins/volume/exec/.dummy"
I1128 11:06:20.553565    5793 update.go:720] Writing file "/etc/containers/registries.conf"
I1128 11:06:20.555742    5793 update.go:720] Writing file "/etc/containers/storage.conf"
I1128 11:06:20.557980    5793 update.go:720] Writing file "/etc/crio/crio.conf"
I1128 11:06:20.560723    5793 update.go:720] Writing file "/etc/containers/policy.json"
I1128 11:06:20.563181    5793 update.go:720] Writing file "/etc/kubernetes/cloud.conf"
I1128 11:06:20.565163    5793 update.go:720] Writing file "/etc/kubernetes/kubelet.conf"
I1128 11:06:20.567280    5793 update.go:720] Writing file "/etc/NetworkManager/conf.d/10-worker-nm-disable-auto-config.conf"
I1128 11:06:20.569773    5793 update.go:720] Writing file "/etc/sysconfig/network-scripts/ifcfg-eno1"
I1128 11:06:20.572015    5793 update.go:720] Writing file "/etc/sysconfig/network-scripts/ifcfg-eno2"
I1128 11:06:20.573919    5793 update.go:720] Writing file "/etc/kubernetes/kubelet.conf"
I1128 11:06:20.576135    5793 update.go:720] Writing file "/opt/setup_rt.sh"
I1128 11:06:20.578630    5793 update.go:720] Writing file "/etc/tuned/realtime-variables.conf"
I1128 11:06:20.580775    5793 update.go:675] Writing systemd unit "machine-config-daemon-host.service"
I1128 11:06:20.582830    5793 update.go:682] Successfully wrote systemd unit "machine-config-daemon-host.service": 
I1128 11:06:20.582844    5793 update.go:692] Enabling systemd unit "machine-config-daemon-host.service"
I1128 11:06:20.582872    5793 update.go:613] /etc/systemd/system/multi-user.target.wants/machine-config-daemon-host.service already exists. Not making a new symlink
I1128 11:06:20.582879    5793 update.go:704] Enabled systemd unit "machine-config-daemon-host.service"
I1128 11:06:20.582885    5793 update.go:675] Writing systemd unit "kubelet.service"
I1128 11:06:20.584850    5793 update.go:682] Successfully wrote systemd unit "kubelet.service": 
I1128 11:06:20.584866    5793 update.go:692] Enabling systemd unit "kubelet.service"
I1128 11:06:20.584887    5793 update.go:613] /etc/systemd/system/multi-user.target.wants/kubelet.service already exists. Not making a new symlink
I1128 11:06:20.584892    5793 update.go:704] Enabled systemd unit "kubelet.service"
I1128 11:06:20.584898    5793 update.go:675] Writing systemd unit "install_realtime.service"
I1128 11:06:20.586899    5793 update.go:682] Successfully wrote systemd unit "install_realtime.service": 
I1128 11:06:20.586914    5793 update.go:692] Enabling systemd unit "install_realtime.service"
I1128 11:06:20.586934    5793 update.go:613] /etc/systemd/system/multi-user.target.wants/install_realtime.service already exists. Not making a new symlink
I1128 11:06:20.586940    5793 update.go:704] Enabled systemd unit "install_realtime.service"
I1128 11:06:20.586946    5793 update.go:531] Deleting stale data
I1128 11:06:20.586982    5793 update.go:812] Writing SSHKeys at "/home/core/.ssh/authorized_keys"
I1128 11:06:20.588912    5793 update.go:818] Wrote SSHKeys at /home/core/.ssh/authorized_keys
I1128 11:06:20.591973    5793 update.go:847] Updating of non RHCOS nodes are not supported
I1128 11:06:20.594962    5793 update.go:984] Update prepared; beginning drain
I1128 11:06:20.595094    5793 daemon.go:268] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"testing-worker-0", UID:"3c9b6b4f-11c7-11ea-b824-ac1f6b7bea24", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'PendingConfig' Written pending config rendered-worker-rt-69b2580891eabb9c50effa32987f0a29
I1128 11:06:20.597575    5793 daemon.go:268] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"testing-worker-0", UID:"3c9b6b4f-11c7-11ea-b824-ac1f6b7bea24", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'Drain' Draining node to update config.
I1128 11:06:21.428418    5793 update.go:93] ignoring DaemonSet-managed pods: virt-handler-69tg6, ocp4x-ptp-ngrx8, dns-default-cwgsf, node-ca-pbgz9, machine-config-daemon-8llj2, node-exporter-wsj9c, multus-wv5wp, nfd-worker-2vj4g, ovs-79rxm, sdn-7gqfb, csi-cephfsplugin-h9w4l, csi-rbdplugin-8bkqc, rook-ceph-agent-26cfh, rook-discover-hphw5
I1128 11:06:21.428462    5793 update.go:89] drained node "testing-worker-0"
I1128 11:06:21.428473    5793 update.go:984] drain complete
I1128 11:06:21.431211    5793 update.go:984] initiating reboot: Node will reboot into config rendered-worker-rt-69b2580891eabb9c50effa32987f0a29
I1128 11:06:21.431277    5793 daemon.go:268] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"testing-worker-0", UID:"3c9b6b4f-11c7-11ea-b824-ac1f6b7bea24", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'Reboot' Node will reboot into config rendered-worker-rt-69b2580891eabb9c50effa32987f0a29
I1128 11:06:21.817508    5793 daemon.go:505] Shutting down MachineConfigDaemon
Connection to testing-worker-0.testing.baremetal.edge-sites.net closed by remote host.
Connection to testing-worker-0.testing.baremetal.edge-sites.net closed.

**Comment by runcom** [comment]
can you check

```
journalctl -o cat _UID=0 | grep OPENSHIFT_MACHINE_CONFIG_DAEMON_LEGACY_LOG_HACK
```

Might be an issue with the pendingConfig if the node is never marked Done

**Comment by yrobla** [comment]
Nothing there, i don't get any result

**Comment by runcom** [comment]
> Nothing there, i don't get any result

so that's why, can you try on a centos7 box the following (followed again by the previous command I pasted earlier):

```
$ logger '{"test": "1", "OPENSHIFT_MACHINE_CONFIG_DAEMON_LEGACY_LOG_HACK": "1"}'
```

**Comment by yrobla** [comment]
logger '{"test": "1", "OPENSHIFT_MACHINE_CONFIG_DAEMON_LEGACY_LOG_HACK": "1"}'
[root@testing-worker-0 core]# journalctl -o cat _UID=0 | grep OPENSHIFT_MACHINE_CONFIG_DAEMON_LEGACY_LOG_HACK
{"test": "1", "OPENSHIFT_MACHINE_CONFIG_DAEMON_LEGACY_LOG_HACK": "1"}

**Comment by yrobla** [comment]
Code does not even enter there, because logger is supporting journal. So it must be some problem with the other logger:
        logger := exec.Command("logger", "--journald")

        var pendingState bytes.Buffer
        pendingState.WriteString(fmt.Sprintf(`MESSAGE_ID=%s
MESSAGE=%s
BOOT_ID=%s
PENDING=%d`, pendingStateMessageID, pending.GetName(), dn.bootID, isPending))

        logger.Stdin = &pendingState
        return logger.CombinedOutput()

**Comment by yrobla** [comment]
If i use journal to find those entries i can see:

{ "__CURSOR" : "s=d6565d31c3ee4008ba13309e94ae7487;i=13a4a;b=6e09cd9a881a4a54ad20a1d764b4086d;m=2d315535c;t=5986aaf9c90ce;x=6fadc1f57db3aa9", "__REALTIME_TIMESTAMP" : "1574958863782094", "__MONOTONIC_TIMESTAMP" : "12131324764", "_BOOT_ID" 
: "6e09cd9a881a4a54ad20a1d764b4086d", "_UID" : "0", "_GID" : "0", "_MACHINE_ID" : "8f98df4d9e2740faa8a864ee20f89c78", "_TRANSPORT" : "journal", "_CAP_EFFECTIVE" : "1fffffffff", "_SYSTEMD_CGROUP" : "/", "_HOSTNAME" : "testing-worker-0", "_C
OMM" : "logger", "_AUDIT_LOGINUID" : "1000", "_AUDIT_SESSION" : "21", "TEST" : "1", "CODE_FILE" : "misc-utils/logger.c", "CODE_LINE" : "360", "CODE_FUNC" : "journald_entry", "SYSLOG_IDENTIFIER" : "logger", "MESSAGE_ID" : "machine-config-da
emon-pending-state", "_PID" : "12738", "_SOURCE_REALTIME_TIMESTAMP" : "1574958863781754" }
{ "__CURSOR" : "s=d6565d31c3ee4008ba13309e94ae7487;i=13d4f;b=6e09cd9a881a4a54ad20a1d764b4086d;m=2da3f501f;t=5986ab6c68d91;x=e97a2674da44c29f", "__REALTIME_TIMESTAMP" : "1574958983974289", "__MONOTONIC_TIMESTAMP" : "12251516959", "_BOOT_ID"
 : "6e09cd9a881a4a54ad20a1d764b4086d", "_UID" : "0", "_GID" : "0", "_MACHINE_ID" : "8f98df4d9e2740faa8a864ee20f89c78", "_TRANSPORT" : "journal", "_CAP_EFFECTIVE" : "1fffffffff", "_HOSTNAME" : "testing-worker-0", "_COMM" : "logger", "TEST" 
: "1", "CODE_FILE" : "misc-utils/logger.c", "CODE_LINE" : "360", "CODE_FUNC" : "journald_entry", "SYSLOG_IDENTIFIER" : "logger", "MESSAGE_ID" : "machine-config-daemon-pending-state", "_PID" : "15715", "_SOURCE_REALTIME_TIMESTAMP" : "157495
8983973964" }
{ "__CURSOR" : "s=d6565d31c3ee4008ba13309e94ae7487;i=14cca;b=6e09cd9a881a4a54ad20a1d764b4086d;m=2ffd320ab;t=5986adc5a5e1d;x=cc927a4f7ae7da12", "__REALTIME_TIMESTAMP" : "1574959614418461", "__MONOTONIC_TIMESTAMP" : "12881961131", "_BOOT_ID" : "6e09cd9a881a4a54ad20a1d764b4086d", "_UID" : "0", "_GID" : "0", "_MACHINE_ID" : "8f98df4d9e2740faa8a864ee20f89c78", "_TRANSPORT" : "journal", "_CAP_EFFECTIVE" : "1fffffffff", "_HOSTNAME" : "testing-worker-0", "_COMM" : "logger", "_AUDIT_LOGINUID" : "1000", "_AUDIT_SESSION" : "21", "CODE_FILE" : "misc-utils/logger.c", "CODE_LINE" : "360", "CODE_FUNC" : "journald_entry", "SYSLOG_IDENTIFIER" : "logger", "MESSAGE_ID" : "machine-config-daemon-pending-state", "MESSAGE" : "washereruncom", "_PID" : "31265", "_SOURCE_REALTIME_TIMESTAMP" : "1574959614418153" }

**Comment by yrobla** [comment]
Looks to me that is never detecting that pending state: https://github.com/openshift/machine-config-operator/blob/release-4.2/pkg/daemon/daemon.go#L801
Looking at the code and logs, it's falling under https://github.com/openshift/machine-config-operator/blob/release-4.2/pkg/daemon/daemon.go#L892 , that means it's not detecting any PendingConfig

**Comment by yrobla** [comment]
if i look at the code i see it writes logs in the format:
MESSAGE_ID=machine-config-daemon-pending-state
MESSAGE=rendered-worker-rt-543729153cb0c57057dcff83f990432f
BOOT_ID=fb852dde-7a01-4ea7-8e2a-739fa55a2764
PENDING=1

for example
then it is retrieved with journalctl -o json _UID=0 MESSAGE_ID=machine-config-daemon-pending-state
if i try to retrieve these entries when i send the commands manually to journal with logger --journald , it works
however, if i rely on the code to write it, it doesn't
seems that for some reason the call is not really executed
        logger := exec.Command("logger", "--journald")
        var pendingState bytes.Buffer
        pendingState.WriteString(fmt.Sprintf(`MESSAGE_ID=%s
MESSAGE=%s
BOOT_ID=%s
PENDING=%d`, pendingStateMessageID, pending.GetName(), dn.bootID, isPending))
        logger.Stdin = &pendingState
        return logger.CombinedOutput()
does not seem to work

**Comment by yrobla** [comment]
Ok i found the issue. As machineconfig is relying on journal for communication, it needs that logs in journal are stored across reboots. And by default , the non-rhcos nodes come with volatile journal.
So that was causing that system could never find a pending state in journal, and going over continuous reboots.
Persistent storage can be configured on: https://access.redhat.com/solutions/696893
