### ISSUE TITLE
The replicas of etcd-quorum-guard should match the number of etch-member Pods

### ISSUE THREAD

**Issue by williamcaban** [openshift/machine-config-operator#1307]
When using replicas = 1 in the install-config.yaml
```
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 1
```

The installation properly deploy a single `etcd-member` Pod but the MCO keep trying to deploy 3 `etcd-quorum-guard` Pods. In that case, one of the Pods comes up okay but, obviously, the other two keep failing because there are no additional master nodes.

The number of etcd-quorum-guard should be equal to the number of etcd Pods. Currently the Deployment definition (https://github.com/openshift/machine-config-operator/blob/master-4.3/install/0000_80_machine-config-operator_07_etcdquorumguard_deployment.yaml) hardcode this to 3 replicas.

**Comment by kikisdeliveryservice** [comment]
cc: @hexfusion @alaypatel07

**Comment by kikisdeliveryservice** [comment]
Afaik, etcd quorum guard (and a host of other ocp things) require a minimum of 3 masters / 2 workers to have everything working correctly. I would imagine that a single master/ single etcd pod deployment will not function correctly as there is no etcd quorum to be had.

cced Etcd team above to allow them to chime in.

**Comment by sinnykumari** [comment]
https://github.com/openshift/machine-config-operator/blob/master/docs/etcd-quorum-guard.md doc explains well why having at least 3 replicas of etcd-quorum-guard are important

**Comment by williamcaban** [comment]
A cluster size of 1 master or even all-in-one, has a majority of 1 and it is a valid odd number for etcd. (yes, without failure tolerance). That is the scenario I'm working here not the one with even numbers. It might be the case this operator might not be relevant for those scenarios but I wanted to confirm.

**Comment by ArvinB** [comment]
Is there a workaround for this issue? I am facing the exact same problem using OpenShift 4.3.13

**Comment by kikisdeliveryservice** [comment]
etcd quorum guard has migrated to its own repo & operator: 
https://github.com/openshift/cluster-etcd-operator
