### ISSUE TITLE
Mirroring images to the local OCP registry not working

### ISSUE THREAD

**Issue by huizengaJoe** [openshift/machine-config-operator#1345]
## Bug Report

I had originally reported this in the operator-lifecycle-manager repo but I think this is probably the right place, please redirect me if I am wrong, I closed the original.

https://github.com/operator-framework/operator-lifecycle-manager/issues/1184

**What did you do?**

I am trying to follow this document https://docs.openshift.com/container-platform/4.2/operators/olm-restricted-networks.html but am NOT able to deploy a pod.
I am running on an aws 4.2.7 cluster build using the tryopenshift installation path

- I have used the oc image mirror command to mirror an image from the quay.io to the internal registry
```
oc image mirror quay.io/huizenga/test2-mirror-registry:latest image-registry.openshift-image-registry.svc:5000/joeolm/test2-mirror-registry:latest  --insecure=true -a ./joedockerconfig.json
```
- I have setup my ImageContentSourcePolicy
```
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: ibm-cloudpak-registry
spec:
  repositoryDigestMirrors:
  - mirrors:
    - default-route-openshift-image-registry.apps.joeocp4.purple-chesterfield.com/joeolm/test2-mirror-registry
    - image-registry.openshift-image-registry.svc:5000/joeolm/test2-mirror-registry 
    source: quay.io/huizenga/test2-mirror-registry  
```
- I have verified via podman that when I pull quay.io/huizenga/test2-mirror-registry by sha digest it is actually using my mirror
```
podman pull quay.io/huizenga/test2-mirror-registry@sha256:28e00e1805176ca333f6e9827e9c77f76782fd7fa594caf97b6629b96b0d1a1f --log-level=debug

DEBU[0000] reference rewritten from 'quay.io/huizenga/test2-mirror-registry@sha256:28e00e1805176ca333f6e9827e9c77f76782fd7fa594caf97b6629b96b0d1a1f' to 'default-route-openshift-image-registry.apps.joeocp4.purple-chesterfield.com/joeolm/test2-mirror-registry@sha256:28e00e1805176ca333f6e9827e9c77f76782fd7fa594caf97b6629b96b0d1a1f'
DEBU[0000] reference rewritten from 'quay.io/huizenga/test2-mirror-registry@sha256:28e00e1805176ca333f6e9827e9c77f76782fd7fa594caf97b6629b96b0d1a1f' to 'image-registry.openshift-image-registry.svc:5000/joeolm/test2-mirror-registry@sha256:28e00e1805176ca333f6e9827e9c77f76782fd7fa594caf97b6629b96b0d1a1f
```

- But I am NOT able to deploy a pod that references the quay.io/huizenga/test2-mirror-registry by sha within my pod manifest file. I am doing a simple oc apply -f mypod.yaml as a simple test and I always get ImagePullBackOff, shouldn't this work?

I trying all of this within my own project/namespace, the image was mirrored to my namespace and I am deploying the pod in the same namespace using the default service account

Here is a snippet from mypod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: nsibmcloudpakcatalog
  namespace: joeolm
spec:
  containers:
  - image: quay.io/huizenga/test2-mirror-registry@sha256:28e00e1805176ca333f6e9827e9c77f76782fd7fa594caf97b6629b96b0d1a1f
    imagePullPolicy: Always
```

```
Events:
  Type     Reason     Age              From                                                 Message
  ----     ------     ----             ----                                                 -------
  Normal   Scheduled  13s              default-scheduler                                    Successfully assigned joeolm/nsibmcloudpakcatalog to ip-10-0-163-160.us-east-2.compute.internal
  Normal   Pulling    6s               kubelet, ip-10-0-163-160.us-east-2.compute.internal  Pulling image "quay.io/huizenga/test2-mirror-registry@sha256:28e00e1805176ca333f6e9827e9c77f76782fd7fa594caf97b6629b96b0d1a1f"
  Warning  Failed     5s               kubelet, ip-10-0-163-160.us-east-2.compute.internal  Failed to pull image "quay.io/huizenga/test2-mirror-registry@sha256:28e00e1805176ca333f6e9827e9c77f76782fd7fa594caf97b6629b96b0d1a1f": rpc error: code = Unknown desc = Error reading manifest sha256:28e00e1805176ca333f6e9827e9c77f76782fd7fa594caf97b6629b96b0d1a1f in quay.io/huizenga/test2-mirror-registry: unauthorized: access to the requested resource is not authorized
  Warning  Failed     5s               kubelet, ip-10-0-163-160.us-east-2.compute.internal  Error: ErrImagePull
  Normal   BackOff    4s (x2 over 5s)  kubelet, ip-10-0-163-160.us-east-2.compute.internal  Back-off pulling image "quay.io/huizenga/test2-mirror-registry@sha256:28e00e1805176ca333f6e9827e9c77f76782fd7fa594caf97b6629b96b0d1a1f"
  Warning  Failed     4s (x2 over 5s)  kubelet, ip-10-0-163-160.us-east-2.compute.internal  Error: ImagePullBackOff
```
- As another data point I am also NOT able get the following command to run either
```
oc image info quay.io/huizenga/test2-mirror-registry@sha256:28e00e1805176ca333f6e9827e9c77f76782fd7fa594caf97b6629b96b0d1a1f -a /root/joedockerconfig.json  --loglevel=8
```

**What did you expect to see?**
I expected that the pod referencing the quay.io image would use the mirrored image from the OCP internal image repo.

Is the internal image repo supported for mirroring?

**What did you see instead? Under which circumstances?**
I see an imagepullBackOff error

**Comment by runcom** [comment]
@umohnani8 @mtrmac @mrunalp ptal

**Comment by shawn-hurley** [comment]
There is a bug for this here:

https://bugzilla.redhat.com/show_bug.cgi?id=1773806

The gist is that you have to provide credentials to the internal registry to the global pull secret. 

I am working on verifying all the steps needed now and will update this thread when I know the exact steps to take.

**Comment by cdjohnson** [comment]
@shawn-hurley Looks like the doc on how to update the global pull secret is here:
https://docs.openshift.com/container-platform/4.3/openshift_images/managing-images/using-image-pull-secrets.html#images-update-global-pull-secret_using-image-pull-secrets

But still not seeing doc for the ImageContentSourcePolicy yet:
https://docs.openshift.com/container-platform/4.3/openshift_images/image-configuration.html

**Comment by shawn-hurley** [comment]
> docs.openshift.com/container-platform/4.3/openshift_images/image-configuration.html

I do see https://docs.openshift.com/container-platform/4.3/openshift_images/image-configuration.html#images-configuration-registry-mirror_image-configuration Does have the documentation on using and creating the ImageContentSourcePolicy, are you looking for something different?

**Comment by cdjohnson** [comment]
@shawn-hurley There isn't any mention in that page on how to configure the Global Image Pull Secret to access the mirrored registry.  

So:
1. Configure the ImageContentSourcePolicy
2.  If the mirrored registry requires authentication, add the credentials for that registry to the global image pull secret.  The pull secrets in the namespace are NOT used for mirrored registries.

**Comment by mtrmac** [comment]
> @shawn-hurley There isn't any mention in that page on how to configure the Global Image Pull Secret to access the mirrored registry.

For the record, that is tracked in https://github.com/openshift/openshift-docs/issues/19440 .

/close
