### ISSUE TITLE
fcos-BUG - Go-Panic when updating to next release

### ISSUE THREAD

**Issue by Reamer** [openshift/machine-config-operator#1378]
**Description**

Go-Panic in fcos branch, while updating configuration

**Steps to reproduce the issue:**
1. Install 4.4.0-0.okd (https://origin-release.svc.ci.openshift.org/)
2. Update to next release from e.g`oc adm upgrade --allow-explicit-upgrade --force --to-image=registry.svc.ci.openshift.org/origin/release:4.4.0-0.okd-2020-01-20-231545`

**Describe the results you received:**

When machine-config-daemon tries to update the system, it will change all "normal" files (e.g. `/etc/kubernetes/manifests/etcd-member.yaml`, `/usr/local/bin/etcd-member-add.sh`, `/usr/local/bin/etcd-snapshot-backup.sh`, `/etc/crio/crio.conf` ...). After that unit files should be update, but a panic raised.
https://gist.githubusercontent.com/Reamer/10c2158ea2f63671807fa3f4058080bc/raw/a225e088963933f54f5a47b0d1300ab1f72e7350/machine-config-daemon.log

**Describe the results you expected:**
Update should go smooth.

**Output of `oc adm release info --commits | grep machine-config-operator`:**

```
machine-config-operator                        https://github.com/openshift/machine-config-operator                        d0ff651e69ab94a948501652ea59c5f7a9494118
```

**Additional environment details (platform, options, etc.):**
- Plattform vsphere

**Comment by LorbusChris** [comment]
Not sure what causes this with a quick glance.

The `fcos` branch will be rebased very shortly - I'd kindly as you to re-try this once that's done.

**Comment by gtema** [comment]
Have the same with fcos and 4.3. Cluster stuck when trying to bring it out of degraded state (crio can't start with /usr/share/containers/oci/hooks.d in hooks_dir)

**Comment by vrutkovs** [comment]
>Have the same with fcos and 4.3

That's https://github.com/openshift/okd/issues/42

**Comment by LorbusChris** [comment]
Fixed by https://github.com/openshift/machine-config-operator/pull/1498
