### ISSUE TITLE
Provide useful logs and/or events when sub-controllers generate MachineConfig(s)

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#1386]
We came across a pretty nasty bug where we suspect manual intervention on the node has been performed but we can't fully prove it. Further it seems that the ContainerRuntimeConfig controller ran at least once but at the time we investigated the bug we did not have any `ctrcfg` objects to back that claim up.

It would be beneficial to provide some sort of logs and possible kubernetes events to signal that MachineConfigs have been generated from the sub-controllers to ease bugs investigation when it happens (we only got 1 (one) bug report about this and again, we're not sure it's a bug or users manually patched the nodes which led to a broken situation).

**Comment by kikisdeliveryservice** [comment]
@haircommander @umohnani8 this is an old issue - wondering if this is still applicable to current ctrcfg/kubeletcfg?
