### ISSUE TITLE
baremetal: ipv6 non_virtual_ip for workers is empty

### ISSUE THREAD

**Issue by hardys** [openshift/machine-config-operator#1420]
In https://github.com/openshift/machine-config-operator/commit/0c74358b7d9ca77c78bf23e3cfcc6bcf6c03dbc3#diff-9cbee0e66919c61dc7ca33846ae316ce I reworked the prepender script, but maintained the existing code to check the non_virtual_ip

```
       NON_VIRTUAL_IP=$(/usr/local/bin/non_virtual_ip \
            "{{.Infra.Status.PlatformStatus.BareMetal.APIServerInternalIP}}" \
            "{{.Infra.Status.PlatformStatus.BareMetal.NodeDNSIP}}" \
            "{{.Infra.Status.PlatformStatus.BareMetal.IngressIP}}")
```

When running this in an ipv6 environment we see this:

```
[root@worker-0 dispatcher.d]# foo=$(/usr/local/bin/non_virtual_ip "fd2e:6f44:5dd8:c956::5" "fd2e:6f44:5dd8:c956:0:0:0:2" "fd2e:6f44:5dd8:c956::4")
Is fd2e:6f44:5dd8:c956::5 between 172.22.0.0 and 172.22.0.255
Is fd2e:6f44:5dd8:c956::5 between fe80:: and fe80::ffff:ffff:ffff:ffff
Is fd2e:6f44:5dd8:c956::5 between fd2e:6f44:5dd8:c956::17 and fd2e:6f44:5dd8:c956::17
Is fd2e:6f44:5dd8:c956::5 between fe80:: and fe80::ffff:ffff:ffff:ffff
[root@worker-0 dispatcher.d]# echo $foo

```

The APIServerInternalIP references the API VIP, the IngressIP is also a VIP, and the NodeDNSIP resolves to the DNS VIP - so these are *all* VIPs.

I think the IP we want (on the workers, which don't point to the DNS VIP) is `fd2e:6f44:5dd8:c956::17` which is the ULA for the external network on the worker node.

```
3: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:0b:bb:d1:05:56 brd ff:ff:ff:ff:ff:ff
    inet6 fd2e:6f44:5dd8:c956::17/128 scope global dynamic noprefixroute 
       valid_lft 3026sec preferred_lft 3026sec
    inet6 fe80::9cab:71d3:d6fe:10da/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

I suspect we can't template that IP via the go variables, so we'll need to discover it at runtime, and remove the non_virtual_ip script completely?

**Comment by bcrochet** [comment]
What I've gathered so far is that the addresses are /128. Therefore, it doesn't see the API VIP as being in the same subnet as the non-VIP. I am investigating using a newer, higher-level, python 3 library for this. (ipaddress)
