### ISSUE TITLE
Phase out special bootstrap machine-config components

### ISSUE THREAD

**Issue by abhinavdahiya** [openshift/machine-config-operator#1427]
**Description**

Currently we have special machine-config components for bootstrap host. There was need for these special code paths because machine-config configured the etcd on the control plane hosts before the kubernetes API could be started on the bootstrap host and therefore we had to design code paths around files on disk. 

But with the addition of cluster etcd operator, the bootstrap host can host kubernetes API independently, allowing even the machine-config components on bootstrap host to work against a kubernetes API.

This would allow us to run full fedged cluster machine-config-controller _with all it's sub controllers_, cluster machine-config-server as static pods on the bootstrap host.

Another benefit is that we can transition the control plane hosts to service account based bootstrap kubeconfig.

**Risks**

1. Previously the controller would create the complete machine-configuration before starting the server, there was no possibility of the control-plane hosts getting _partial_ configuration. but running the cluster controller+server means that machine-config-controller and user-provided objects might be pushed at different times making it difficult to know when the work is done to serve the control plane hosts.

**Proposal**

We update the bootstrap-machine-config-operator to render static pods of _cluster_ machine-config-{operator, controller, server} and other objects that would allow us to run complete ecosystem from the bootstrap host.

The machineconfigpools are created with `paused: true` i.e
- The combination to generated is paused
- Since there is no generated configuration the server will not serve the control plane any partials

The bootstrap-machine-config-operator adds a marker object to render with _last_ prefix such that we can be sure that the cluster-bootstrap on bootstrap host has pushed all user CRs (runtime or kubelet CRs)

When does operator know if work is done for bootstrap?
- The operator waits for controller to create the _in-built_ machine configuration to be pushed.
- The operator sees the marker previously rendered
- All machine configs from high level CRDs like runtimeconfig, kubeletconfig etc. have been created.

The allows the operator to mark machineconfigpools `pasued: false` allowing the hosts to get correct configuration.

/cc @runcom

**Comment by cgwalters** [comment]
It'd be *awesome* to get rid of that special case; it was the cause of [this bug](https://github.com/openshift/installer/pull/2939) for example which involved a lot of time from a lot of people debugging it.

Overall; I think the design seems sane, but there's a lot of details here.
