### ISSUE TITLE
[FCOS] openstack: workers don't join the cluster due to python scripts

### ISSUE THREAD

**Issue by vrutkovs** [openshift/machine-config-operator#1430]
Openstack / oVirt are using a python script to find IPs: https://github.com/openshift/machine-config-operator/blob/fcos/templates/worker/00-worker/openstack/files/openstack-non-virtual-ip.yaml#L6

FCOS doesn't provide python (and most likely never will), so it needs to be rewritten

**Comment by cgwalters** [comment]
Today, we also ship `/usr/libexec/machine-config-daemon` in the host by default which comes from this repo.  So, a useful pattern could be to add arbitrary subcommands to that binary.

Note though when submitting PRs to this repo, the binary in CI will *not* be updated - that currently only happens after code lands in master and goes through the main RHCOS build process.

**Comment by cgwalters** [comment]
> Today, we also ship /usr/libexec/machine-config-daemon in the host by default which comes from this repo. So, a useful pattern could be to add arbitrary subcommands to that binary.

And to elaborate this is used today by e.g. [this unit](https://github.com/openshift/machine-config-operator/blob/master/templates/common/_base/units/machine-config-daemon-firstboot.service).

> Note though when submitting PRs to this repo, the binary in CI will not be updated - that currently only happens after code lands in master and goes through the main RHCOS build process.

Hence today unfortunately one would have to "ratchet" a change here by landing the Go code in master, wait for it to propagate into an updated `machine-os-content`, then delete the other code and switch the calling code to use the new code.

**Comment by vrutkovs** [comment]
The PR can be tested on `fcos` branch - since FCOS doesn't ship MCD (and RHCOS shouldn't too really) it fetches the binary from the release payload and pivots early - thus MCD is always consistent across all nodes

**Comment by LorbusChris** [comment]
New approach:
[Add a baremetal-runtimecfg-ubi8 image](https://github.com/openshift/release/pull/7537) and use that to run the python scripts in a containerized way, exclusively in OKD.
