### ISSUE TITLE
Baremetal: Incorrect config.hcl generated when master fqdn doesnt match pattern *-master-*

### ISSUE THREAD

**Issue by karmab** [openshift/machine-config-operator#1437]
**Description**

incorrect config.hcl generated when master fqdn doesnt match pattern *-master-*

**Steps to reproduce the issue:**
1. deploy baremetal ipi with random fqdns for the master nodes
2.
3.

**Describe the results you received:**
the config.hcl created by the rendering initcontainer in mdns-publisher static pod lacks entries necessary for etcd operator to help etcd cluster come up

**Describe the results you expected:**
control plane should come up fine

**Additional information you deem important (e.g. issue happens only occasionally):**

this is the config.hcl generated in this case, where we can see that the host_name lack etcd-$num at the beginning

```
bind_address = "10.19.135.200"
collision_avoidance = "hostname"
service {
    name = "hendrix Etcd"
    host_name = ".local."
    type = "_etcd-server-ssl._tcp"
    domain = "local."
    port = 2380
    ttl = 3200
}
service {
    name = "hendrix Workstation"
    host_name = "dhcp-19-130-200.local."
    type = "_workstation._tcp"
    domain = "local."
    port = 42424
    ttl = 3200
}
service {
    name = "hendrix EtcdWorkstation"
    host_name = ".local."
    type = "_workstation._tcp"
    domain = "local."
    port = 42424
    ttl = 300
}
```

Additionally, those nodes were showing up in oc get node with an incorrect provisioning ip as node ip, which is also something that will cause trouble for the etcd operator (assumption is etcd will have IP address of hostIP because this is the network peers communicate across together).

**Output of `oc adm release info --commits | grep machine-config-operator`:**

```
(paste your output here)
```

**Additional environment details (platform, options, etc.):**

**Comment by karmab** [comment]
@celebdor

**Comment by cybertron** [comment]
Now that we have cluster-etcd-operator I think we need to change the SRV record to point at the regular hostname record directly and remove the etcd-specific record. I'm looking into that now.

**Comment by cybertron** [comment]
Should be fixed by #1461

**Comment by kikisdeliveryservice** [comment]
Can someone confirm that this was fixed by the above PR (which has merged). If so can you please close this?

**Comment by cybertron** [comment]
I had tested this successfully when I last commented, but I don't have permission to close it.

**Comment by kikisdeliveryservice** [comment]
> I had tested this successfully when I last commented, but I don't have permission to close it.

Thanks for the update @cybertron !! :smile:
