### ISSUE TITLE
Validate units in MCs

### ISSUE THREAD

**Issue by ericavonb** [openshift/machine-config-operator#1467]
Systemd provides the command `systemd-analyze verify` to validate systemd units. It would be nice to validate the units provided in MCs for correctness using something like that. This sort of validation would catch small small typos and errors in units before invalid files make their way onto a node.

Some ways we could add this validation:
1. Dynamic validation webhook on `MachineConfig` resources. This would be ideal since it gives the user feedback on the issue immediately and prevents any invalid MCs from ever getting created. However, maintaining the webhook adds complexity and latency to the MCO.
2. As a `status` field on `MachineConfig` resources. Currently, MCs have no status. We could add one that gives the user back information on validity or allow automatic standardization, e.g. removing duplicate file entries or ignition v2/3 conversion (eventually).
3. A git pre-commit hook for units provided in templates. While this doesn't help users creating custom MCs, it is easy and straight forward to do.

cc @celebdor

**Comment by celebdor** [comment]
I like all three options. Specially 2 and 3 :-)
