### ISSUE TITLE
BYOH: MCD crashes "An unsupported OS is being used: centos"

### ISSUE THREAD

**Issue by vrutkovs** [openshift/machine-config-operator#161]
MCD fails on a CentOS cluster deployed on GCP
```
# oc logs -f machine-config-daemon-frq6h -n openshift-machine-config-operator
I1109 14:28:25.824759   14757 start.go:46] Version: 3.11.0-222-g393cc444-dirty
F1109 14:28:25.826242   14757 start.go:50] Error found when checking operating system: An unsupported OS is being used: centos:
```

I'm not sure if it should necessary fail if it has encountered an unsupported OS. In any case, RHEL and CentOS should be whitelisted so that BYOH team could proceed

**Comment by ashcrow** [comment]
OK, we can add CentOS to the white list. PR will be up for you to review shortly.

**Comment by lucab** [comment]
@ashcrow PR looks good to me. I did a quick skim through the code and it seems that except for the boolean gate about we are not actually consuming the string-value of OS detection, just passing it through several constructors.

**Comment by ashcrow** [comment]
That's correct. It's there to ensure we jump out on anything that isn't BYO*.

**Comment by ashcrow** [comment]
Though I believe we'll start to use it as time goes on.
