### ISSUE TITLE
Resize machines bug

### ISSUE THREAD

**Issue by rphillips** [openshift/machine-config-operator#167]
I initially instantiated a libvirt cluster with the default 2048 of RAM and 1 vcpu. I then edited the machineset via:
```
oc edit machineset --namespace openshift-cluster-api
```
and changed the vcpu to 4, the memory to 4096, and the replica count to 3. I expected to see all the workers get replaced with the higher requirements, but the original worker stayed at the default 2048 MB of RAM. The two new workers did get created correctly with the memory and vcpu requirements.

**Comment by cgwalters** [comment]
This is a bug for https://github.com/openshift/cluster-api right?

**Comment by ashcrow** [comment]
@cgwalters I believe you're correct. (EX: https://github.com/openshift/cluster-api/tree/fd68ff1f9a70c09db561216f5e2abfe8cb28487a/pkg/apis/cluster/v1alpha1).

@rphillips do you mind moving the issue over to the `cluster-api` repo?

**Comment by rphillips** [comment]
Moved. Thanks!
