### ISSUE TITLE
Design for osImageURL updates - integration with CVO/release payload

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#183]
I wanted to elaborate here on the current status of this.  We have a PR in https://github.com/openshift/machine-config-operator/pull/363 which will finally close the loop and inject `machine-os-content` from the release payload all the way into the MachineConfig objects, which will result in the MCD updating.

The final architecture will be:

New kernel errata, turns into RPM, converted into ostree then oscontainer.  A bit more information on the [build system side here](https://github.com/openshift/origin/pull/21998#issuecomment-461943604).  The oscontainer makes it into a new release payload published on quay.io.

At some point the release payload pulled down by CVO, which includes a [osimageurl ConfigMap](https://github.com/openshift/machine-config-operator/pull/305) that references that container (same thing as the `machine-os-content` ImageStream).  The CVO updates the ConfigMap, which you can see via

`oc -n openshift-machine-config-operator get configmap/machine-config-osimageurl`

The operator notices the change to the configmap and updates the "controllerconfig" which is an internal CRD that is used as the primary input to the MCC.  See `oc get -o yaml controllerconfig`.

The "template" sub-controller of the MCC then updates `machineconfigs/00-master` and `machineconfigs/00-worker`.

The "render" sub-controller of the MCC generates new "rendered" MCs that look like `machineconfigs/master-<hash>` and `machineconfigs/worker-<hash>` and updates the MachineConfigPools to target them.  For more information on this, see the MCC docs.

On each node the MCD will get the new osimageurl, and if it's different than what's booted, it will pull down the container and rebase to it and reboot. This is also the same as any other config change.

**Comment by jlebon** [comment]
For completeness, one alternative is to make it a `MachineConfig` object instead, which is then used as the base config containing the `osImageURL` in which all other (Ignition) configs are merged into. I think this maps slightly more closely to what's currently done today.

That said, using a separate `ConfigMap` allows us to have richer metadata. E.g. pkg lists & diffs, OSTree commits & versions, etc... The idea being that an "Update available" button can show all that stuff without having to hunt down the osImage.

**Comment by ashcrow** [comment]
Remember, this data will need to flow one way or another down into a `MachineConfig`. If it's easier we could add some more information to MCs themselves.

**Comment by jlebon** [comment]
Strawman:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: rhcos-release-info
data:
  metadata.json: '{"osImageUrl": "registry.svc.ci.openshift.org/rhcos/os-maipo@sha256:4efb36f476405f8e30256733ac900e11b70833dc6a6b54179db60a501fa47124", "ostree-version": "47.115", "ostree-checksum": "b0edcc594e65ccebcc917b0ead76ea6894c0d4d672a63ceee5bdc59976c55bf9", "pkgdiff": [["origin-clients", 2, {"NewPackage": ["origin-clients", "4.0.0-0.alpha.0.610.98ebf23", "x86_64"], "PreviousPackage": ["origin-clients", "4.0.0-0.alpha.0.607.49e9f08", "x86_64"]}], ...], "pkglist": ["GeoIP-1.5.0-13.el7.x86_64", "NetworkManager-1:1.12.0-7.el7_6.x86_64", ...]}'
```

Basically, we can include a subset of what coreos-assembler already outputs. Or maybe just a link to *that* `meta.json` instead?

**Comment by jlebon** [comment]
> Remember, this data will need to flow one way or another down into a MachineConfig. If it's easier we could add some more information to MCs themselves.

I think it shouldn't be too hard to adapt the MCC either way so we shouldn't constrain ourselves too much on what's easier.

**Comment by ashcrow** [comment]
> I think it shouldn't be too hard to adapt the MCC either way so we shouldn't constrain ourselves too much on what's easier.

Fair. Rephrased: what's doable and consumable within specific constraints :smiley:

**Comment by cgwalters** [comment]
> Basically, we can include a subset of what coreos-assembler already outputs. 

Do we need anything other than the `"registry.svc.ci.openshift.org/rhcos/os-maipo@sha256:4efb36f476405f8e30256733ac900e11b70833dc6a6b54179db60a501fa47124",` string?

**Comment by jlebon** [comment]
> Yeah, though...a tricky part about this is that the pkgdiff is against the previous version, which may not be the one they're updating to...

Yeah, I think to do this correctly, the pkg diff would have to be done from the pkg lists instead rather than precomputed. Anyway, those are things that could easily come later. We just have to make sure we leave the door open for it.

> Mmm. I'm OK stuffing the whole `meta.json` in there for now, but I suspect we're going to need to add something smarter later.

Yeah, that sounds fine to me.

**Comment by smarterclayton** [comment]
Be aware you’re going to eventually need to have a distinction between “the config says this is the latest” and “I’m ready to roll that out to the nodes”.  Design with that in mind because new kubeelts are going to happen ~ 1/week

**Comment by smarterclayton** [comment]
Pkgdiff is useless.  There is no guarantee it has any relevance.  Think package manifest instead of diffs.  Our errata and higher level tools will calculate the diff

**Comment by jlebon** [comment]
> Be aware you’re going to eventually need to have a distinction between “the config says this is the latest” and “I’m ready to roll that out to the nodes”. Design with that in mind because new kubeelts are going to happen ~ 1/week

Can you elaborate on that? Do you mean making sure we actually upgrade to the selected release instead of whatever happens to now be the latest at the time we're actually ready to upgrade? I think that should be covered yeah. The metadata includes the full sha256 of the oscontainer.

> Pkgdiff is useless. There is no guarantee it has any relevance. Think package manifest instead of diffs. Our errata and higher level tools will calculate the diff

Yup, see https://github.com/coreos/coreos-assembler/pull/226.

**Comment by smarterclayton** [comment]
Expectation is that you will build an image and push it to the openshift origin integration image stream, then reference the component “os” from this operator and have the dummy value substituted.

In OCP, we do something similar where the OS content gets built via whatever process and shows up in the prerelease list, and is processed the same way.

You can build anywhere - we just need you to push/be imported to the right place

**Comment by smarterclayton** [comment]
Note the dummy value can be real - but since we need to mirror the content you have to be referenced in the operator list which means you need to be sucked into the right place.

Push vs scheduled import is also possible, but if we do scheduled import the source location has to be appropriately gated like a push would (only changes if you test against latest in an install)

**Comment by wking** [comment]
> ... but if we do scheduled import the source location has to be appropriately gated like a push would (only changes if you test against latest in an install)

That breaks the sceduled-import model, doesn't it?  How do you know the "latest" test used for the gate hadn't been surpassed by further release-payload work?  Or will errors there be caught by post-testing?

**Comment by cgwalters** [comment]
My notes from playing around with MCD state so far;

I am still a bit confused as to the current flow of the `osImageURL`; should `oc edit machineconfig/00-worker` work to render or a new one?  Currently I edit the generated one.

Next, currently our oscontainers are uploaded to api.ci under the `rhcos/` namespace and they require a separate pull secret, and we don't have a defined way to upload that to nodes.  Actually I am a bit confused by pull secrets today, there is https://github.com/openshift/installer/pull/775 which merged but I don't see `/root/.docker` being created on my master/worker?

For some reason it's not working to `podman login` manually, need to trace that.

**Comment by kikisdeliveryservice** [comment]
@cgwalters machineconfigs are generated in the MCC, I believe that `edit` is editing the current config not generating a new one.

**Comment by cgwalters** [comment]
Looked at that PR more carefully and it's only about the bootstrap.  The pull secret goes into the main `oc get configmap -n kube-system cluster-config-v1` (thanks Kirsten for mentioning that one earlier!).

What I don't understand yet is where that pull secret ends up on the nodes.

**Comment by kikisdeliveryservice** [comment]
@cgwalters Pull secret gets written into the machineconfigs here:
https://github.com/openshift/machine-config-operator/blob/4b28c96a225bbd9711c98c73a6d83f1c4ed9653a/lib/resourcemerge/machineconfig.go

**Comment by jlebon** [comment]
> I am still a bit confused as to the current flow of the osImageURL; should oc edit machineconfig/00-worker work to render or a new one? Currently I edit the generated one.

Hmm, I think you're right that that should trigger a regeneration of a new machineconfig. I'm trying that here, but my MCC now is hitting:

```
E1206 15:14:13.341864       1 reflector.go:322] github.com/openshift/machine-config-operator/vendor/k8s.io/client-go/informers/factory.go:130: Failed to watch *v1.Node: Get https://172.30.0.1:443/api/v1/nodes?resourceVersion=9818&timeoutSeconds=360&watch=true: dial tcp 172.30.0.1:443: connect: connection refused
E1206 15:14:13.341972       1 reflector.go:322] github.com/openshift/machine-config-operator/pkg/generated/informers/externalversions/factory.go:101: Failed to watch *v1.ControllerConfig: Get https://172.30.0.1:443/apis/machineconfiguration.openshift.io/v1/controllerconfigs?resourceVersion=4441&timeoutSeconds=365&watch=true: dial tcp 172.30.0.1:443: connect: connection refused
E1206 15:14:13.342012       1 reflector.go:322] github.com/openshift/machine-config-operator/pkg/generated/informers/externalversions/factory.go:101: Failed to watch *v1.MachineConfigPool: Get https://172.30.0.1:443/apis/machineconfiguration.openshift.io/v1/machineconfigpools?resourceVersion=7665&timeoutSeconds=503&watch=true: dial tcp 172.30.0.1:443: connect: connection refused
E1206 15:14:13.342044       1 reflector.go:322] github.com/openshift/machine-config-operator/pkg/generated/informers/externalversions/factory.go:101: Failed to watch *v1.MachineConfig: Get https://172.30.0.1:443/apis/machineconfiguration.openshift.io/v1/machineconfigs?resourceVersion=7316&timeoutSeconds=387&watch=true: dial tcp 172.30.0.1:443: connect: connection refused
```

which is a flavour of some of the errors people were hitting in #199. Will try to dig deeper there.

> Next, currently our oscontainers are uploaded to api.ci under the rhcos/ namespace and they require a separate pull secret, and we don't have a defined way to upload that to nodes. Actually I am a bit confused by pull secrets today, there is openshift/installer#775 which merged but I don't see /root/.docker being created on my master/worker?

I will admit the hacky way I've been testing upgrades so far includes prepending the `machine-config-daemon` invocation in the daemonset config with `oc login ... &&`. Fixing that to use secrets would be awesome!

**Comment by cgwalters** [comment]
Yep, I missed it somehow, I see it now, it goes to `/var/lib/kubelet/config.json`.  Adding the secret there works.

**Comment by kikisdeliveryservice** [comment]
@jlebon those timeouts are related to the openshift apiserver: https://github.com/openshift/origin/issues/21612

**Comment by aaronlevy** [comment]
> I am still a bit confused as to the current flow of the osImageURL; should oc edit machineconfig/00-worker work to render or a new one? Currently I edit the generated one.

My understanding is that the *source* should be edited (which should result in a new generated config). We should not be in the habit of editing the generated config (and if that happened, the MCC should actually roll-out a non-edited config to all nodes -- as that is built from the canonical source(s)).

It might help to add docs along the lines of, "As a user, how do I modify host configuration?" and it points to creating a new (source) machine config (as a layer that will be merged with config we control), and outlining that you should not be editing generated configs (that will ultimately be stomped on by MCC rolled-out source-generated configs anyway).

cc @abhinavdahiya these assumptions are still correct.

**Comment by jlebon** [comment]
>> I am still a bit confused as to the current flow of the osImageURL; should oc edit machineconfig/00-worker work to render or a new one? Currently I edit the generated one.
>
> Hmm, I think you're right that that should trigger a regeneration of a new machineconfig.

OK yeah, this does work for me. After sorting out the MCC issue (@kikisdeliveryservice thanks! I tried out the workaround there and it seems like it worked), and doing `oc edit machineconfig 00-worker`, the daemon shows:

```
I1206 19:46:08.991607    4369 update.go:486] Updating OS to http://example.com
I1206 19:46:08.991616    4369 run.go:13] Running: /bin/pivot http://example.com
pivot version 0.0.2
...
```

**Comment by jlebon** [comment]
> My understanding is that the source should be edited (which should result in a new generated config).

Yeah, this is mostly for testing stuff out.

> It might help to add docs along the lines of, "As a user, how do I modify host configuration?" and it points to creating a new (source) machine config (as a layer that will be merged with config we control), and outlining that you should not be editing generated configs (that will ultimately be stomped on by MCC rolled-out source-generated configs anyway).

The issue is that when the MCC merges configs, it doesn't replace the base `osImageURL`: https://github.com/openshift/machine-config-operator/blob/20c1299a831fdc65335b101530ea7b6d60a0ba71/pkg/apis/machineconfiguration.openshift.io/v1/helpers.go#L14. (And IIUC, the first config is that `00` generated from the baked in template currently, though the osImageURL part of it comes from: https://github.com/openshift/machine-config-operator/blob/20c1299a831fdc65335b101530ea7b6d60a0ba71/pkg/controller/template/render.go#L220).

Eventually, testing an OS update for hacking could be done by changing the configmap directly (or whatever we settle on in this ticket). (Or at an even higher level, pointing at a custom release payload).

**Comment by jlebon** [comment]
To add some context to the previous comment: this is strictly for testing changes to `osImageURL`. Other filesystem updates that are part of the Ignition spec are merged in, so can be done indeed by creating a new source machine config that gets squashed into a new generated machine config.

**Comment by cgwalters** [comment]
One thing that wasn't obvious to me until I dug into this again is that the `OSImageURL: ""` bits today in e.g. `00-worker` come from simply synthesizing the machineconfig objects from the template Ignition fragments by `generateMachineConfigs()`.

For some reason...I had it in my head that the update payload today contained the `OSImageURL` but that's not true.

Now, then where this intersects with https://github.com/openshift/machine-config-operator/pull/258 is that PR is including a way for the machine-config-operator repository to have a reference to the oscontainer, which...we could then define new code in the MCC which parses that image from the configmap and injects it into the master/worker MCs.

**Comment by cgwalters** [comment]
How about we change the semantics of MC objects so that a MC can either have Ignition or osImageURL, but not *both*?  They're really very different things and this would help discourage admins who are generating Ignition configs to somehow accidentally change `osImageURL`.

This would also force us to clearly split out our `osImageURL` that was ultimately derived from the release payload into a place shared by both master/workers.

**Comment by ashcrow** [comment]
I'm not sure I fully understand what splitting would do for us. If we do split out `oSImageURL` and Ignition information we'd essentially have and`ign` "file" with ignition content, and an MC "file" with a single OSImageURL field. I'm not against the idea, I fear I'm not following though.

**Comment by jlebon** [comment]
> we could then define new code in the MCC which parses that image from the configmap and injects it into the master/worker MCs

:+1: Yeah, those were my thoughts.

> How about we change the semantics of MC objects so that a MC can either have Ignition or osImageURL, but not both?

Though the MC has this powerful property of fully describing the host. I guess we could do a variant of what you're suggesting by only having the final generated MC contain both?

**Comment by cgwalters** [comment]
> If we do split out oSImageURL and Ignition information we'd essentially have and ign "file" with ignition content, and an MC "file" with a single OSImageURL field. I'm not against the idea, I fear I'm not following though

Hm, which files?  Are you talking about the MC objects?  

> I guess we could do a variant of what you're suggesting by only having the final generated MC contain both?

Sorry that *is* what I meant - the rendered one would have both.  I'm talking about the "input" versions.

**Comment by ashcrow** [comment]
> Sorry that is what I meant - the rendered one would have both. I'm talking about the "input" versions.

That clears it up for me. :+1:

**Comment by cgwalters** [comment]
PR in https://github.com/openshift/machine-config-operator/pull/273

**Comment by cgwalters** [comment]
If anyone wants to play around with doing a pivot in the *current* master, i.e.:

```
$ oc get clusterversion
NAME      VERSION                           AVAILABLE   PROGRESSING   SINCE     STATUS
version   4.0.0-0.alpha-2019-01-10-120623   True        False         19m       Cluster version is 4.0.0-0.alpha-2019-01-10-120623
```

Here's an object you can `oc create`:

```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 00-0walters-worker-osimageurl
spec:
  osImageURL: registry.svc.ci.openshift.org/rhcos/maipo@sha256:61dc83d62cfb5054c4c5532bd2478742a0711075ef5151572e63f94babeacc1a
  config:
    ignition:
      version: 2.2.0
```

(The requirement to specify the ignition/version is a bug)

But this will change shortly when #273 lands.

**Comment by kikisdeliveryservice** [comment]
@cgwalters I just tried an update on `bin/openshift-install unreleased-master-78-g63bdb7fce105c6a5f0422b055b8c1164dddc53fd` using the config above and it worked as expected.

Logs for ref: http://pastebin.test.redhat.com/696135

**Comment by kikisdeliveryservice** [comment]
@cgwalters is there a specific order the MCs for the osUrlUpdates need to adhere to? Because applying a 2nd and 3rd config I'm running into errors. Must the newest config come first or last?

**Comment by kikisdeliveryservice** [comment]
Ok tried the second config with name: `00-0valters-worker-osimageurl` :rofl: to land in the first spot and it updated as I expected.

**Comment by cgwalters** [comment]
If today one wants to test an os update, here's an object you can `oc create`:

```
apiVersion: v1
kind: List
items:
- apiVersion: machineconfiguration.openshift.io/v1
  kind: MachineConfig
  metadata:
    labels:
      machineconfiguration.openshift.io/role: master
    name: 00-0walters-master-osimageurl
  spec:
    osImageURL: registry.svc.ci.openshift.org/rhcos/maipo@sha256:ffe6873d7e322da2c3fc56f49347f2aac264812fcd652b58d54142e1fdc9cecb
    config:
      ignition:
        version: 2.2.0
- apiVersion: machineconfiguration.openshift.io/v1
  kind: MachineConfig
  metadata:
    labels:
      machineconfiguration.openshift.io/role: worker
    name: 00-0walters-worker-osimageurl
  spec:
    osImageURL: registry.svc.ci.openshift.org/rhcos/maipo@sha256:ffe6873d7e322da2c3fc56f49347f2aac264812fcd652b58d54142e1fdc9cecb
    config:
      ignition:
        version: 2.2.0
```

**Comment by cgwalters** [comment]
This finally landed in https://github.com/openshift/machine-config-operator/pull/426
