### ISSUE TITLE
also do GCP routes on bootstrap

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#1883]
Moving this from https://github.com/coreos/fedora-coreos-config/pull/502#issuecomment-652003853

Phase 1: Move from shell-injected-via MC to our binary:

1. Move the shell code from https://github.com/openshift/machine-config-operator/pull/1670 into bindata as part of our binary
1. Change the MCD to run that entrypoint from the host via `systemd-run` - this can work nicely now that we have https://github.com/openshift/machine-config-operator/pull/1766/

Phase 2:

- Change `bootkube.sh` in the installer to detect if we're on GCP and run that binary also as a systemd unit

**Comment by cgwalters** [comment]
Step 1.2 to could still use the systemd unit injected via Ignition, but it feels cleaner to have it as part of our binary - among other things it helps pave the path towards not writing in shell script by default for host services.

**Comment by LorbusChris** [comment]
Summarizing the current situation again after discussion with @sohankunkerkar:

Right now the GCP routes script exists in two locations for each OpenShift flavour:
- For OCP, in the RHCOS base OS for use on the bootstrap node, as well as here in the MCO for masters/workers
- For OKD, in the installer for use on the bootstrap node, as well as here in the MCO for masters/workers

It looks like `nm-cloud-setup` will support all the functionality we require here with regard to configuring the LBs on the bootstrap node in the upcoming 1.26 version. That version has however not landed yet, neither in Fedora nor in RHEL packages, and won't land at least until Fedora 33.

As the current situation (i.e. adding the GCP routes script to bootstrap nodes via installer) is not a release blocker for OKD, it might be feasible to wait until we have NM 1.26 with the new `nm-cloud-setup` features available in both FCOS and RHCOS images. We could then switch to using `nm-cloud-setup` during bootstrap for the LBs, and remove the GCP routes script duplicates from installer and RHCOS base, leaving only one canonical version of the GCP routes script here in the MCO for use masters/workers. This way, no changes would have to be made in the MCO.

@cgwalters @runcom @miabbott @sohankunkerkar WDYT about this approach?

**Comment by cgwalters** [comment]
Sure, I'm also fine waiting until we have the new `nm-cloud-setup`.

**Comment by cgwalters** [comment]
I was going to suggest moving it into say the machineAPI codebase just to keep up the fun game of "hot potato" but...fine!

**Comment by LorbusChris** [comment]
I think we still want `nm-cloud-setup` to do GCP routes on the bootstrap node.
/remove-lifecycle rotten
