### ISSUE TITLE
Fails to report leader election event

### ISSUE THREAD

**Issue by ctron** [openshift/machine-config-operator#1932]
**Description**

On startup the operator fails to report the leader election:

~~~
E0717 13:37:34.037747       1 event.go:316] Could not construct reference to: '&v1.ConfigMap{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"machine-config", GenerateName:"", Namespace:"openshift-machine-config-operator", SelfLink:"/api/v1/namespaces/openshift-machine-config-operator/configmaps/machine-config", UID:"2422c2c1-a89f-11e9-8d22-00163e6b49f3", ResourceVersion:"227943344", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63698970507, loc:(*time.Location)(0x2530700)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"control-plane.alpha.kubernetes.io/leader":"{\"holderIdentity\":\"machine-config-operator-594c89d579-ngcq5_47cd3e80-de8f-499a-b7ea-59662967813b\",\"leaseDurationSeconds\":90,\"acquireTime\":\"2020-07-17T13:37:34Z\",\"renewTime\":\"2020-07-17T13:37:34Z\",\"leaderTransitions\":154}"}, OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Immutable:(*bool)(nil), Data:map[string]string(nil), BinaryData:map[string][]uint8(nil)}' due to: 'no kind is registered for the type v1.ConfigMap in scheme "github.com/openshift/machine-config-operator/cmd/common/helpers.go:30"'. Will not report event: 'Normal' 'LeaderElection' 'machine-config-operator-594c89d579-ngcq5_47cd3e80-de8f-499a-b7ea-59662967813b became leader'
~~~

**Steps to reproduce the issue:**
1. Start up operator
2.
3.

**Describe the results you received:**

Fails to report.

**Describe the results you expected:**

Should report.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `oc adm release info --commits | grep machine-config-operator`:**

```
$ oc adm release info --commits | grep machine-config-operator
  machine-config-operator                        https://github.com/openshift/machine-config-operator                        4173030d89fbf4a7a0976d1665491a4d9a6e54f1
```

**Additional environment details (platform, options, etc.):**

**Comment by jasonbrooks** [comment]
I'm seeing this, too, during a cluster upgrade from 4.4.12 to 4.5.2. 

I'm getting this "could not construct" error, followed by `Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)` and the pod crashloops. This is blocking my upgrade.

```
$ oc adm release info --commits | grep machine-config-operator
  machine-config-operator                        https://github.com/openshift/machine-config-operator                        4173030d89fbf4a7a0976d1665491a4d9a6e54f1
```

[machine-config-operator-594c89d579-9qnq5-machine-config-operator.log](https://github.com/openshift/machine-config-operator/files/4939739/machine-config-operator-594c89d579-9qnq5-machine-config-operator.log)

**Comment by kikisdeliveryservice** [comment]
@jasonbrooks please see: https://bugzilla.redhat.com/show_bug.cgi?id=1858026 and add your must gather

**Comment by kikisdeliveryservice** [comment]
The original error is addressed by:
https://github.com/openshift/machine-config-operator/pull/1518

**Comment by kikisdeliveryservice** [comment]
Closing this issue since it has been fixed. 

For Jason's separate, unrelated issue we will track via the linked BZ.
