### ISSUE TITLE
Q: is it possible that bootstrap node provide its IP address when generating the templates?

### ISSUE THREAD

**Issue by yboaron** [openshift/machine-config-operator#1950]
To support unicast keepalived for baremetal-ipi, we need to find a way to add the bootstrap IP address to the masters template files [1]. 

In the current implementation, master nodes retrieve the bootstrap IP address from a TCP server running on the bootstrap node, and we would like to delete this server.

Is there a way that the bootstrap node itself could provide its IP address when generating the templates?

[1] https://github.com/openshift/machine-config-operator/blob/master/templates/master/00-master/baremetal/files/baremetal-keepalived-keepalived.yaml#L35

**Comment by runcom** [comment]
you can grab (somehow) the bootstrap IP, pass it to the MCO bootstrap through bootkube.sh [1] and have it used in the render routines within the MCO - that will still hold true with https://github.com/openshift/machine-config-operator/issues/1427 I think

[1] https://github.com/openshift/installer/blob/master/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template

**Comment by yboaron** [comment]
Thanks for the feedback  @runcom
