### ISSUE TITLE
inconsistency between osimageurl and digest comparisons

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#1964]
I was looking at some recent e2e-gcp-upgrade jobs (e.g. [this one](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1941/pull-ci-openshift-machine-config-operator-master-e2e-gcp-upgrade/1288897683385225216)) and I noticed:

```
I0730 19:53:35.758111   94185 update.go:1430] Starting update from rendered-worker-427e9f6f5393fffc56bdeddc50f8a33f to rendered-worker-e95dec12126dfcd3937bbfde60933d8c: &{osUpdate:true kargs:false fips:false passwd:false files:true units:true kernelType:false extensions:false}
```

Notice `osUpdate: true`, because the way the job works is that it makes a "synthetic" upgrade by changing the URL for most things but not the digest.  For regular containers in Kube that will still trigger a redeployment, but a while ago we added special casing for "matching digest".

The [MCD in this PR](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/1941/pull-ci-openshift-machine-config-operator-master-e2e-gcp-upgrade/1288897683385225216/artifacts/e2e-gcp-upgrade/pods/openshift-machine-config-operator_machine-config-daemon-9lscc_machine-config-daemon.log) for example still runs:

```
I0730 19:56:06.879041   94185 run.go:18] Running: oc image extract --path /:/run/mco-machine-os-content/os-content-227367051 --registry-config /var/lib/kubelet/config.json registry.svc.ci.openshift.org/ci-op-hzcly6m9/stable@sha256:3a53c55db7ba5b45732ca410bf3edbbc277b03fc2044aa977b2e341e63f1d996
```

But then we do nothing with it because the digest matches.

What would probably make the most sense is to change that CI job to actually synthesize an OS update.  And we should debate whether we keep this special "matching digest" code. 

I'd have to dig through git history but I think it was trying to optimize the "avoid initial reboot if bootimage == target" case but that never happens today.

**Comment by cgwalters** [comment]
Another option of course could be
```
diff --git a/pkg/daemon/update.go b/pkg/daemon/update.go
index c052e099..924bfc62 100644
--- a/pkg/daemon/update.go
+++ b/pkg/daemon/update.go
@@ -430,8 +430,13 @@ func newMachineConfigDiff(oldConfig, newConfig *mcfgv1.MachineConfig) (*machineC
 	// consider them as equal while comparing KernelArguments in both MachineConfigs
 	kargsEmpty := len(oldConfig.Spec.KernelArguments) == 0 && len(newConfig.Spec.KernelArguments) == 0
 
+	osUpdate, err := compareOSImageURL(oldConfig.Spec.OSImageURL, newConfig.Spec.OSImageURL)
+	if err != nil {
+		return nil, err
+	}
+
 	return &machineConfigDiff{
-		osUpdate:   oldConfig.Spec.OSImageURL != newConfig.Spec.OSImageURL,
+		osUpdate:   osUpdate,
 		kargs:      !(kargsEmpty || reflect.DeepEqual(oldConfig.Spec.KernelArguments, newConfig.Spec.KernelArguments)),
 		fips:       oldConfig.Spec.FIPS != newConfig.Spec.FIPS,
 		passwd:     !reflect.DeepEqual(oldIgn.Passwd, newIgn.Passwd),
```

But needs a bit of investigation probably.

**Comment by sinnykumari** [comment]
This is indeed a nice finding and observation. I was under impression that we do e2e-gcp-upgrade from n-1 version to n which is not, better should have checked.
I am in favor of doing osImageURL check by comparing digest as proposed in https://github.com/openshift/machine-config-operator/issues/1964#issuecomment-666741069 and look for a better way to perform gcp-upgrade test.

Wondering if it is possible to perform gcp-upgrade test in our ci from n-1 release to the current release payload ?

**Comment by cgwalters** [comment]
OK right a quick git annotate takes us to 17f10ed73ad74b20f0673e731c0bb6c942550bd2 which links to https://github.com/openshift/machine-config-operator/issues/462

Ahh...but then wait not long after that we did https://github.com/coreos/rpm-ostree/commit/0ac5f71b9f1629049f84c43f45debad7e61925b9

So...we can probably remove this special digest matching code and at least run through the OS update path, even though no files will change.

**Comment by ericavonb** [comment]
> OK right a quick git annotate takes us to [17f10ed](https://github.com/openshift/machine-config-operator/commit/17f10ed73ad74b20f0673e731c0bb6c942550bd2) which links to #462
> 
> Ahh...but then wait not long after that we did [coreos/rpm-ostree@0ac5f71](https://github.com/coreos/rpm-ostree/commit/0ac5f71b9f1629049f84c43f45debad7e61925b9)
> 
> So...we can probably remove this special digest matching code and at least run through the OS update path, even though no files will change.

This seems like the right way to go. There may be reasons to re-pull the os-image other than os updates, like to pull down updated metadata or something.

**Comment by kikisdeliveryservice** [comment]
> This is indeed a nice finding and observation. I was under impression that we do e2e-gcp-upgrade from n-1 version to n which is not, better should have checked.
> I am in favor of doing osImageURL check by comparing digest as proposed in [#1964 (comment)](https://github.com/openshift/machine-config-operator/issues/1964#issuecomment-666741069) and look for a better way to perform gcp-upgrade test.
> 
> Wondering if it is possible to perform gcp-upgrade test in our ci from n-1 release to the current release payload ?

We don't own e2e-gcp-upgrade it's a required test added to repos that must pass.

**Comment by sinnykumari** [comment]
> Ahh...but then wait not long after that we did [coreos/rpm-ostree@0ac5f71](https://github.com/coreos/rpm-ostree/commit/0ac5f71b9f1629049f84c43f45debad7e61925b9)

Thanks for tracking this down and adding more context, agree with the reasoning :+1:
