### ISSUE TITLE
Assign a priority class to pods

### ISSUE THREAD

**Issue by aveshagarwal** [openshift/machine-config-operator#197]
Priority classes docs:
https://docs.openshift.com/container-platform/3.11/admin_guide/scheduling/priority_preemption.html#admin-guide-priority-preemption-priority-class

Example: https://github.com/openshift/cluster-monitoring-operator/search?q=priority&unscoped_q=priority

Notes: The pre-configured system priority classes (system-node-critical and system-cluster-critical) can only be assigned to pods in kube-system or openshift-* namespaces. Most likely, core operators and their pods should be assigned `system-cluster-critical`. Please do not assign `system-node-critical` (the highest priority) unless you are really sure about it.

**Comment by runcom** [comment]
Should be closed because of the recently merged PR?

**Comment by runcom** [comment]
https://github.com/openshift/machine-config-operator/pull/353

**Comment by kikisdeliveryservice** [comment]
closed as per above comments
