### ISSUE TITLE
MCD should write logs to the journal

### ISSUE THREAD

**Issue by jlebon** [openshift/machine-config-operator#200]
Container logs are temporary, journal logs are forever (well, longer at least...).

This should help with debugging issues with the node rebooting and somehow not having access to the previous container logs.

**Comment by ashcrow** [comment]
@imcleod did we get cards for this already?

**Comment by ashcrow** [comment]
To follow up @imcleod created a placeholder card for this work.

**Comment by cgwalters** [comment]
This is done now.

**Comment by cgwalters** [comment]
(Can someone close the issue?  I don't have perms apparently)
