### ISSUE TITLE
KubeletConfig update changes kubelet.conf formatting

### ISSUE THREAD

**Issue by mrogers950** [openshift/machine-config-operator#2230]
/etc/kubernetes/kubelet.conf starts out as yaml, but changes to json once a KubeletConfig is applied. We have compliance checks that expect the file as yaml only. Is json needed (comments in createNewKubeletIgnition() seem to suggest so) or can we change it to write in yaml? I would be happy to suggest a patch if so.

**Comment by cgwalters** [comment]
I think this is @rphillips 's call.

**Comment by mrogers950** [comment]
I found that our yaml probe works fine with the json format, actually, so this is not a requirement for us. But it might be desired for consistency.

**Comment by kikisdeliveryservice** [comment]
Closing but feel free to reopen.
