### ISSUE TITLE
Parallelize Upgrade for multiples workers 

### ISSUE THREAD

**Issue by guillermodep** [openshift/machine-config-operator#2235]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `oc adm release info --commits | grep machine-config-operator`:**

```
(paste your output here)
```

**Additional environment details (platform, options, etc.):**

**Comment by cgwalters** [comment]
This functionality exists, set `maxUnavailable` in the `machineconfigpool/worker` object.

**Comment by guillermodep** [comment]
@cgwalters thanks! I will test this config today!
