### ISSUE TITLE
Per-profile system reserved resources

### ISSUE THREAD

**Issue by guillaumerose** [openshift/machine-config-operator#2249]
**Description**

Last July, cluster profiles were introduced in https://github.com/openshift/enhancements/pull/200. Last year, MCO raised the system reserved resources which were too much for CRC (see https://github.com/openshift/machine-config-operator/commit/b811616049d7990c70fcfd56ff1d5b746b1a1121).
We had to bump default memory from 8G to 9G with this change. 

A way to resolve that would be to use cluster profile to reduce memory reservation only for CRC profile. It could be done with an env variable in the single node manifest.

Related to https://github.com/code-ready/snc/issues/273

**Comment by kikisdeliveryservice** [comment]
This would be a node-team decision

@rphillips PTAL
