### ISSUE TITLE
Configure HTTP PROXY variables permanently into environment 

### ISSUE THREAD

**Issue by EmilienM** [openshift/machine-config-operator#2271]
**Description**

Proxy variables (HTTP_PROXY, HTTPS_PROXY and
NO_PROXY) are manually set/exported into some bash scripts while it would be beneficial for them to be widely exported on the system; since any application would need access to it (e.g. podman, etc).

**Note**
It is mainly a follow-up of https://github.com/openshift/machine-config-operator/pull/2266.

**Reference**
[Related BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1873556)

**Comment by kikisdeliveryservice** [comment]
Linked PR and underlying BZ are both merged. Closing.

**Comment by kikisdeliveryservice** [comment]
Sorry, a bit of confusion on my part the underlying PR is actually:
https://github.com/openshift/machine-config-operator/pull/2272

Reopening.
