### ISSUE TITLE
Add a Degraded annotation

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#234]
Right now one of my nodes went degraded, apparently the MCD restarted so I don't have those logs, and more worrying I can't find anything in the journal.

I'm thinking we want a new node annotation:
```
machineconfiguration.openshift.io/state=Degraded
machineconfiguration.openshift.io/degraded="Unable to reconcile ..."
```

**Comment by jlebon** [comment]
Did you check `oc logs -p` too?

**Comment by kikisdeliveryservice** [comment]
I usually see the reason in the `oc logs -p` as well.

**Comment by cgwalters** [comment]
Labels are query-able; and we definitely want to make it easy for admins to find degraded nodes.  https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/

**Comment by cgwalters** [comment]
Updating this since labels aren't meant for free-form text; I think we should cover the extended rationale with both an event a systemd journal entry like we do for reboots etc.

**Comment by cgwalters** [comment]
Retitling this to use an annotation instead; in https://github.com/openshift/machine-config-operator/pull/260 we decided not to add a label.

**Comment by cgwalters** [comment]
Also, the MCP really needs to show `(total: 3, updated: 0, unavailable: 1, degraded: 1)` or so.

**Comment by runcom** [comment]
do we want _any_ error during a sync which can result in degraded/unreconcilable to be added in this annotation? I want to hash this out so we can bubble this information up from MCD logs to nodes annotation for an instant debug, wdyt?

**Comment by kikisdeliveryservice** [comment]
@runcom adding the _reason_ an MC is unreconcilable would be extremely helpful for a user rather than them having to bumble thru MCD logs.

**Comment by runcom** [comment]
Yeah, but we also want to provide explaination when for instance, pivot fails but that just marks degraded, not unreconcilable uhm
