### ISSUE TITLE
Cluster upgrades hang trying to upgrade machine-config-operator

### ISSUE THREAD

**Issue by reavessm** [openshift/machine-config-operator#2368]
**Description**

Cluster upgrades hang trying to upgrade machine-config-operator

**Steps to reproduce the issue:**
1. oc adm upgrade --to-latest=true

**Describe the results you received:**
Machine-config-operator is degraded and the cluster is continuously upgrading

**Describe the results you expected:**

Cluster proceeds to upgrade

**Additional information you deem important (e.g. issue happens only occasionally):**

I am running in the OKD 4.6 stable channel.  I successfully upgraded on 12/20/2020, but the next upgrade failed on 1/13/2021.  I also tried to force another upgrade on 1/26/2021, but to the same results.  The other operators seem to upgrade fine.

**Output of `oc adm release info --commits | grep machine-config-operator`:**

```
machine-config-operato https://github.com/openshift/machine-config-operator ead62052138543eb3e19b4de493a94ed7c88b3b9
```

**Additional environment details (platform, options, etc.):**

OKD 4.6 running on Ovirt 4.4

**Comment by vrutkovs** [comment]
See https://github.com/openshift/okd/issues/471

/close

**Comment by reavessm** [comment]
This did not fixed my issues.  I tried all the steps listed in that comment but all that happened was my master node ran out of storage space.  I simply deleted the machine, recreated it, and now I'm at least progressing
