### ISSUE TITLE
/var/home/core/.ssh/authorized_keys not created by MCO during install (OKD 4.6/4.7)

### ISSUE THREAD

**Issue by fortinj66** [openshift/machine-config-operator#2385]
**Description**

During installation MCO does not create /var/home/core/.ssh/authorized_keys which should have the ignition bootstrap key in it.  This prevents core from logging into the server if https://github.com/openshift/machine-config-operator/pull/2087 is enabled as reading authorized_keys.d is disabled.  if https://github.com/openshift/machine-config-operator/pull/2087 is disabled, login succeeds as authorized_keys.d is read and the ignition key is available.

**Steps to reproduce the issue:**
Install OKD 4.7 
**Describe the results you received:**
unable to ssh into server after installation.  If I manually create the authorized_keys file I can log in successfully

**Describe the results you expected:**
successful ssh into servers

**Additional information you deem important (e.g. issue happens only occasionally):**

```
[root@os-utils-d02 qa-4.7]# oc get mc
NAME                                               GENERATEDBYCONTROLLER                      IGNITIONVERSION   AGE
00-master                                          451aa6521d737f849302a98fae2dff213a99eff4   3.2.0             15h
00-worker                                          451aa6521d737f849302a98fae2dff213a99eff4   3.2.0             15h
01-master-container-runtime                        451aa6521d737f849302a98fae2dff213a99eff4   3.2.0             15h
01-master-kubelet                                  451aa6521d737f849302a98fae2dff213a99eff4   3.2.0             15h
01-worker-container-runtime                        451aa6521d737f849302a98fae2dff213a99eff4   3.2.0             15h
01-worker-kubelet                                  451aa6521d737f849302a98fae2dff213a99eff4   3.2.0             15h
99-master-generated-registries                     451aa6521d737f849302a98fae2dff213a99eff4   3.2.0             15h
99-master-okd-extensions                                                                      3.1.0             15h
99-master-ssh                                                                                 3.1.0             15h
99-okd-master-disable-mitigations                                                             3.1.0             15h
99-okd-worker-disable-mitigations                                                             3.1.0             15h
99-worker-generated-registries                     451aa6521d737f849302a98fae2dff213a99eff4   3.2.0             15h
99-worker-okd-extensions                                                                      3.1.0             15h
99-worker-ssh                                                                                 3.1.0             15h
rendered-master-24161f6ba4983107f6f1799baa94a8c3   451aa6521d737f849302a98fae2dff213a99eff4   3.2.0             15h
rendered-worker-7cfc5c07b9d03981cbf576692ff98026   451aa6521d737f849302a98fae2dff213a99eff4   3.2.0             15h
```
Interestingly enough the rendered-master and rendered-worker have the 99-master-ssh and 99-worker-ssh embedded in it as expected.

If I update 99-master-ssh with a new or additional key, the MCO reconciles the change and generates a proper authorized_keys file.

**Output of `oc adm release info --commits | grep machine-config-operator`:**

```
Unfortunately I'm using a custom 4.7 MCO because of the DNS issues in 4,7.  

However, as it also fails in 4.6:
 machine-config-operator                        https://github.com/openshift/machine-config-operator                        eb9778355a9020673e8ce9aee092cb98d80cde5e
```

**Additional environment details (platform, options, etc.):**
OKD 4.7 vSphere IPI

[must-gather logs from clean OKD 4.7 install ](https://www.dropbox.com/s/iy0tfvketvpc6gy/must-gather.local.6862155712704536146.tar.gz?dl=0)

**Comment by vrutkovs** [comment]
Seems https://github.com/openshift/machine-config-operator/pull/2393 is the best fix we have for this

**Comment by darkmuggle** [comment]
I'm confused as to why https://github.com/openshift/machine-config-operator/pull/2388 is not an acceptable path forward?

**Comment by darkmuggle** [comment]
The must gather indicates that the problem is very much above the MCD level. Are you :100: sure this is an MCO issue and not  OKD? 
```
021-02-02T10:27:31.695832925Z W0202 10:27:31.695773       1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
2021-02-02T10:27:37.386709970Z I0202 10:27:37.386649       1 sync.go:570] syncing Required MachineConfigPools
2021-02-02T10:29:02.565149252Z W0202 10:29:02.562796       1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
2021-02-02T10:29:07.843306594Z I0202 10:29:07.843245       1 sync.go:570] syncing Required MachineConfigPools
2021-02-02T10:29:09.673299439Z W0202 10:29:09.673257       1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
2021-02-02T10:29:15.300002643Z I0202 10:29:15.299937       1 sync.go:570] syncing Required MachineConfigPools
2021-02-02T10:30:09.980932932Z W0202 10:30:09.980865       1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
2021-02-02T10:30:15.293884127Z I0202 10:30:15.293831       1 sync.go:570] syncing Required MachineConfigPools
2021-02-02T10:32:04.944277706Z W0202 10:32:04.944221       1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

**Comment by fortinj66** [comment]
> I'm confused as to why #2388 is not an acceptable path forward?

As far as I'm concerned it would be acceptable.  However, I believe Christian would be opposed...

**Comment by fortinj66** [comment]
> The must gather indicates that the problem is very much above the MCD level. Are you 💯 sure this is an MCO issue and not OKD?
> 
> ```
> 021-02-02T10:27:31.695832925Z W0202 10:27:31.695773       1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
> 2021-02-02T10:27:37.386709970Z I0202 10:27:37.386649       1 sync.go:570] syncing Required MachineConfigPools
> 2021-02-02T10:29:02.565149252Z W0202 10:29:02.562796       1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
> 2021-02-02T10:29:07.843306594Z I0202 10:29:07.843245       1 sync.go:570] syncing Required MachineConfigPools
> 2021-02-02T10:29:09.673299439Z W0202 10:29:09.673257       1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
> 2021-02-02T10:29:15.300002643Z I0202 10:29:15.299937       1 sync.go:570] syncing Required MachineConfigPools
> 2021-02-02T10:30:09.980932932Z W0202 10:30:09.980865       1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
> 2021-02-02T10:30:15.293884127Z I0202 10:30:15.293831       1 sync.go:570] syncing Required MachineConfigPools
> 2021-02-02T10:32:04.944277706Z W0202 10:32:04.944221       1 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
> ```

Those just seem to be warning  about CRDs going away in the future...

However, I'll rebuild the cluster and add a new must-gather

**Comment by fortinj66** [comment]
[new must-gather](https://www.dropbox.com/s/orpmpwqi3xtx3j2/must-gather.tar.gz?dl=0)

**Comment by bgilbert** [comment]
#2388 is not an acceptable path because it restores the OKD security vulnerability that any SSH keys injected during node provisioning will remain for the lifetime of the node.

**Comment by fortinj66** [comment]
https://github.com/openshift/machine-config-operator/pull/2393 has been closed without implementation.
