### ISSUE TITLE
Move from hardcoded extensions to using extensions.json

### ISSUE THREAD

**Issue by jlebon** [openshift/machine-config-operator#2445]
In https://github.com/coreos/coreos-assembler/pull/2028, we now include an `extensions.json` in the m-o-c which details extensions available in the embedded yumrepo, as well as the corresponding RPMs, e.g.:

```json
{
  "extensions": {
    "kernel-devel": {
      "packages": [
        "kernel-devel-4.18.0-240.15.1.el8_3",
        "kernel-headers-4.18.0-240.15.1.el8_3"
      ],
      "match-base-evr": "kernel",
      "kind": "os-extension"
    },
    "kernel": {
      "packages": [
        "kernel-4.18.0-240.15.1.el8_3",
        "kernel-core-4.18.0-240.15.1.el8_3",
        "kernel-modules-4.18.0-240.15.1.el8_3",
        "kernel-modules-extra-4.18.0-240.15.1.el8_3"
      ],
      "match-base-evr": "kernel",
      "kind": "development"
    },
    "kernel-rt": {
      "packages": [
        "kernel-rt-core",
        "kernel-rt-kvm",
        "kernel-rt-modules",
        "kernel-rt-modules-extra",
        "kernel-rt-devel"
      ],
      "architectures": [
        "x86_64"
      ],
      "kind": "os-extension"
    },
    "usbguard": {
      "packages": [
        "usbguard"
      ],
      "kind": "os-extension"
    }
  },
  "repos": [
    "rhel-8-nfv"
  ]
}
```

(The MCO should only look at extensions with `kind: os-extension`; the development ones are not meant for layering.)

Rather than hardcoding the list of supported extensions, the MCO could now read them from this JSON file and feed the package list to rpm-ostree.

For validation, there is also a `com.coreos.os-extensions` label on the m-o-c which lists the available extensions (see e.g. https://github.com/coreos/coreos-assembler/pull/2028#issuecomment-774166775).

**Comment by cgwalters** [comment]
I think part of the idea behind the hardcoded list in the MCO is that because it can be part of the CRD it can be validated at `oc create` time.

But that said probably simplest for now is to have a script that machine edits the CRD openapi validation from the current RHCOS build - we aren't going to need to run that very often.
