### ISSUE TITLE
label limited to  machineconfiguration.openshift.io/role: master|worker

### ISSUE THREAD

**Issue by rmr-silicom** [openshift/machine-config-operator#2469]
**Description**
Machineconfig operator does not work with node labels other than
1.machineconfiguration.openshift.io/role: master
2. machineconfiguration.openshift.io/role: slave

**I expect:**
I can use the MachineConfig to nodes which have a custom label.

For example.
feature.node.kubernetes.io/custom-fpga: "true"

**Comment by kikisdeliveryservice** [comment]
The MCO operates on machine config pools, not _any_ labels a node may have.

If you would like to target non-master/worker labelled pools,  you create a custom pool: https://github.com/openshift/machine-config-operator/blob/master/docs/custom-pools.md to target your config properly.

**Comment by rmr-silicom** [comment]
Thank you for the tip! Now i will add a worker to my 3 masters, since this is not supported with masters 'only' operation.
