### ISSUE TITLE
[okd] Can't add baremetal worker with bond interface

### ISSUE THREAD

**Issue by immort4tor** [openshift/machine-config-operator#2510]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**
Can't add a worker with a bond interface

**Steps to reproduce the issue:**
1. Boot from fedora-coreos-33.20210217.3.0-live.x86_64.iso on baremetal
2.
```console
coreos-installer install --ignition-url=http://<web_server_fqdn>/fcos/worker.ign --insecure-ignition \
--append-karg bond=bond0:ens15f0,ens15f1:mode=active-backup \
--append-karg ip=10.0.0.1::10.0.0.254:255.255.255.0:<worker_fqdn>:bond0:none \
--append-karg nameserver=10.0.0.253 \
--append-karg nameserver=10.0.0.252 \
/dev/sda
```
3. Wait
4. Approve CSR's

**Describe the results you received:**
As a result, we get that container ovnkube-node in ovnkube-node-s77qf Pod is in a state CrashLoopBackOff with error in logs:

I0401 16:02:55.480637  114580 ovs.go:166] exec(8): /usr/bin/ovs-vsctl --timeout=15 -- port-to-br br-ex
I0401 16:02:55.488787  114580 ovs.go:169] exec(8): stdout: ""
I0401 16:02:55.488819  114580 ovs.go:170] exec(8): stderr: "ovs-vsctl: no port named br-ex\n"
I0401 16:02:55.488832  114580 ovs.go:172] exec(8): err: exit status 1
I0401 16:02:55.488876  114580 ovs.go:166] exec(9): /usr/bin/ovs-vsctl --timeout=15 -- br-exists br-ex
I0401 16:02:55.496576  114580 ovs.go:169] exec(9): stdout: ""
I0401 16:02:55.496612  114580 ovs.go:170] exec(9): stderr: ""
I0401 16:02:55.496633  114580 ovs.go:166] exec(10): /usr/bin/ovs-vsctl --timeout=15 list-ports br-ex
I0401 16:02:55.505143  114580 ovs.go:169] exec(10): stdout: ""
I0401 16:02:55.505188  114580 ovs.go:170] exec(10): stderr: ""
I0401 16:02:55.505210  114580 ovs.go:166] exec(11): /usr/bin/ovs-vsctl --timeout=15 get Port  Interfaces
I0401 16:02:55.512581  114580 ovs.go:169] exec(11): stdout: ""
I0401 16:02:55.512612  114580 ovs.go:170] exec(11): stderr: "ovs-vsctl: no row \"\" in table Port\n"
I0401 16:02:55.512624  114580 ovs.go:172] exec(11): err: exit status 1
F0401 16:02:55.512651  114580 ovnkube.go:130] failed to get port "" on bridge "br-ex":, stderr: "ovs-vsctl: no row \"\" in table Port\n", error: exit status 1

**Describe the results you expected:**
It was expected that everything will work out correctly, just as if there was only one NIC

**Output of `oc adm release info --commits | grep machine-config-operator`:**
```console
machine-config-operator                        https://github.com/vrutkovs/machine-config-operator                         2e8f00c41266630862b66dd47730e52e94d794b5
```
**Additional environment details (platform, options, etc.):**
```console
version   4.7.0-0.okd-2021-03-28-152009
```
```console
sh$ nmcli con
NAME                UUID                                  TYPE           DEVICE
bond0               356fc164-6386-4383-94cd-81aca04b8cc5  bond           bond0
ovs-if-br-ex        97fc7064-6e0c-454f-964e-a62d9d5dd53f  ovs-interface  br-ex
br-ex               f83f2fbb-57f8-459b-8759-23248858ff85  ovs-bridge     br-ex
ens15f0             d248b31c-3beb-4ae7-a65e-85dad5a4738e  ethernet       ens15f0
ens15f1             5cfc7bb7-a7bf-4b43-8fc5-406e82e12555  ethernet       ens15f1
ovs-port-br-ex      d71ed23a-e692-453c-b7fe-e51583609fb3  ovs-port       br-ex
ovs-port-phys0      9e6efd90-afb5-4d4a-9fa9-2c6ee75a06a6  ovs-port       bond0
Wired connection 1  f18ed9a7-16a5-3ca3-8d9e-c2ec9cb0a56c  ethernet       --
Wired connection 2  01f64983-31d3-3412-877c-6c70bb46455b  ethernet       --
bond0               95398718-8db1-423d-8744-d7bbdc4c0c31  bond           --
ens15f0             3c048294-4add-4406-ae44-b990af8aaf63  ethernet       --
ens15f1             26b0da68-0920-4018-a156-be4981970043  ethernet       --
ovs-if-phys0        ed6e94c2-7cde-4d39-bd96-4691fc6fc45d  bond           --
```
```console
sh$ ls -la /etc/NetworkManager/system-connections/
total 32
drwxr-xr-x. 2 root root 250 Apr  1 11:56 .
drwxr-xr-x. 8 root root 167 Apr  1 11:53 ..
-rw-------. 1 root root 424 Apr  1 11:50 bond0.nmconnection
-rw-------. 1 root root 345 Apr  1 11:56 br-ex.nmconnection
-rw-------. 1 root root 253 Apr  1 11:50 ens15f0.nmconnection
-rw-------. 1 root root 253 Apr  1 11:50 ens15f1.nmconnection
-rw-------. 1 root root 518 Apr  1 11:56 ovs-if-br-ex.nmconnection
-rw-------. 1 root root 304 Apr  1 11:56 ovs-if-phys0.nmconnection
-rw-------. 1 root root 168 Apr  1 11:56 ovs-port-br-ex.nmconnection
-rw-------. 1 root root 168 Apr  1 11:56 ovs-port-phys0.nmconnection
```
```console
sh$ ls -la /etc/NetworkManager/system-connections-merged/
total 32
drwxr-xr-x. 1 root root 140 Apr  1 11:55 .
drwxr-xr-x. 8 root root 167 Apr  1 11:53 ..
-rw-------. 1 root root 424 Apr  1 11:50 bond0.nmconnection
-rw-------. 1 root root 345 Apr  1 11:55 br-ex.nmconnection
-rw-------. 1 root root 253 Apr  1 11:50 ens15f0.nmconnection
-rw-------. 1 root root 253 Apr  1 11:50 ens15f1.nmconnection
-rw-------. 1 root root 518 Apr  1 11:55 ovs-if-br-ex.nmconnection
-rw-------. 1 root root 304 Apr  1 11:55 ovs-if-phys0.nmconnection
-rw-------. 1 root root 168 Apr  1 11:55 ovs-port-br-ex.nmconnection
-rw-------. 1 root root 168 Apr  1 11:55 ovs-port-phys0.nmconnection
```

**Comment by kikisdeliveryservice** [comment]
will let vadim take a first look since okd, otherwise a baremetal person can look

/assign @vrutkovs
