### ISSUE TITLE
MCC racing with itself?

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#255]
I just did `oc edit machineconfigs/00-worker` and changed `OSImageURL`; no MC was generated, and in the MCC logs I see:

```
I1220 15:08:45.772524       1 node_controller.go:340] Error syncing machineconfigpool worker: Operation cannot be fulfilled on machineconfigpools.machineconfiguration.openshift.io "worker": the object has been modified; please apply your changes to the latest version and try again
I1220 15:08:46.272919       1 node_controller.go:340] Error syncing machineconfigpool worker: Operation cannot be fulfilled on machineconfigpools.machineconfiguration.openshift.io "worker": the object has been modified; please apply your changes to the latest version and try again
```

**Comment by kikisdeliveryservice** [comment]
@cgwalters FWIW, I think you need to create a  new machine config to update the OS as opposed to editing the existing 00-worker. Also there was a naming convention of `00-osimageurl-worker` so that that image was applied before the osimageurl, but not sure if still required.

**Comment by kikisdeliveryservice** [comment]
I think this is desired behavior to deter editing nodes directly as opposed to via machineconfigs?

**Comment by cgwalters** [comment]
> FWIW, I think you need to create a new machine config to update the OS as opposed to editing the existing 00-worker. 

Hm, but it should be supported to edit the MCs right?  This relates to https://github.com/openshift/machine-config-operator/issues/183 in that (this came up in a quick meeting between dusty/jlebon/me this morning) the idea is that our initial MC objects delivered by the CVO would have `osImageURL` set, and when doing `oc adm upgrade` those MCs would be replaced by ones from the new update payload.

**Comment by kikisdeliveryservice** [comment]
@cgwalters after reading that thread, I'm more confused than when I started. Seem to be different vectors of how the user might do something, the `oc adm..` and our personal testing. Def would be great to have a consensus and memorialise?  I was terribly confused when I tried to update the osImageURL last week and hit a bunch of bumps. :)

**Comment by ashcrow** [comment]
Unless we have to bypass the MCO and MCS to provide MC's the MCO should always own generating MCs. If the MCO doesn't there is a good possibility that short lived race conditions between edited MC's and what is being generated by the MCO will occur.

**Comment by jlebon** [comment]
> Hm, but it should be supported to edit the MCs right?

So I was looking into this and reading the MCC codebase as a result. I think there might not actually be an issue here. The MCC essentially owns those configs that it generated and will overwrite changes made to them. I'm writing up some docs to help clarify this.

**Comment by jlebon** [comment]
#281

**Comment by cgwalters** [comment]
Yeah, what I was doing was not correct.
