### ISSUE TITLE
add more to test suite

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#257]
It should be pretty easy to put together a quick test suite in e.g. bash that given a running cluster, tests at least a nondestructive scenario of creating a MC, waiting for it to roll out, running a quick daemonset that verifies the files exist, then e.g. deletes it and verifies the nodes are back as they were.

We may be able to enhance non-destructive testing by creating a separate machineset too and having MCs being more destructive just to those nodes (e.g. making them degraded etc.)

**Comment by kikisdeliveryservice** [comment]
I'm supposed to work on some e2e testing after my other PRs are done, so count me in! :D

**Comment by abhinavdahiya** [comment]
@smarterclayton whats the best location to add operator level tests ? That require a cluster.

**Comment by smarterclayton** [comment]
See the e2e-aws-operator jobs in openshift/release.  Basically have a binary / script in your repo, copy their pattern, then you get passed a kubeconfig and can run.

**Comment by cgwalters** [comment]
One thing related to https://github.com/openshift/machine-config-operator/issues/294 is that I think it would be an extremely useful pattern for us to support spinning up a "testnode" machine type that is marked tainted; we could then use it as a target for e.g. upgrade and other testing.

**Comment by cgwalters** [comment]
I'm just going to repurpose this issue now for "let's add more to the test suite" since it's not covering much at all.

I think we can add a test case for e.g. "add a MC that adds a file to workers" easily now.

It'd also be good to extend that and script a reconciliation failure (`rsh` into the mcd and make a conflicting file?).

Testing SSH key updates should be pretty straightforward I think.

But most interesting (for me) is testing OS updates, to do that nicely a pattern like https://github.com/openshift/machine-config-operator/issues/257#issuecomment-454585735 would help.

**Comment by cgwalters** [comment]
This issue is basically done, we can track anything else via PRs.
