### ISSUE TITLE
support removing SSH keys entirely

### ISSUE THREAD

**Issue by fgimenezm** [openshift/machine-config-operator#2592]
I tried re-opening the existing issue #296 (support removing SSH keys entirely) but I can't so I'm opening this one instead. Feel free to re-open the other one and close this one.

About removing SSH keys:

This is even harder in latest versions. Removing the ssh MachineConfig now tries to remove the "core" user altogether which is not possible and makes the MCO fail to update the nodes.

_Originally posted by @fgimenezm in https://github.com/openshift/machine-config-operator/issues/296#issuecomment-851436687_

**Comment by fgimenezm** [comment]
This here:
https://github.com/kikisdeliveryservice/machine-config-operator/blob/c415ce6aed25604bc1d2478951db16759dac31f6/pkg/daemon/update.go#L858

why can't it be 0 ?

**Comment by kikisdeliveryservice** [comment]
reopened old issue, thanks

**Comment by kikisdeliveryservice** [comment]
We can improve this, but for now if you want to clear out ssh keys, just update the ssh machineconfig to explicitly have sshkeys: []
