### ISSUE TITLE
document HA apiserver on bare metal with keepalived and haproxy

### ISSUE THREAD

**Issue by ibotty** [openshift/machine-config-operator#2600]
I see that there is code to handle apiserver failover on bare metal nodes.   It would be great to document that so it's possible to retrofit clusters to use an internal solution.

**Comment by kikisdeliveryservice** [comment]
this would be done via the baremetal team and probably shouldnt live in the mco repo.

cc: @cybertron

**Comment by cybertron** [comment]
I'm afraid there isn't anything to document. The internal loadbalancer functionality is tightly tied to IPI deployments and can't currently be retrofitted into UPI ones. It's possible you could design a UPI internal loadbalancer based on the IPI one, but it won't work today.

It's also worth noting that the current internal loadbalancer implementation is not one I could highly recommend. There are limitations, particularly around VIP failover, that technically violate the OpenShift API availability requirements. We have some long-term plans to address that, but an external loadbalancer is still the better choice for any production clusters today.

**Comment by kikisdeliveryservice** [comment]
Thanks for the comprehensive explanation @cybertron !!

Given the above, closing this issue.
