### ISSUE TITLE
Deleting old rendered MachineConfigs during an update makes recovery super hard.

### ISSUE THREAD

**Issue by m-yosefpor** [openshift/machine-config-operator#2635]
**Description**

When a machineConfig is changed, a new rendered machineConfig is generated by mc-controller, and nodes start to rollout from `current = old rendered-machineconfig` to `desired = new rendered-machineconfig`. However if during MCP updates, one deletes the `current = old rendered machineConfig`, all nodes turn into degraded, also machineconfig-server will respond with `HTTP 500 error` as old rendered-machineconfig is not found, and also those files will no longer be generated by machineconfig-controller, as they only generate new rendered ones. So the MCO cannot manage to turn the cluster to the desired state, and if user does not have a backup of old rendered machine config, they cannot make the cluster healthy again.

Even recreating is not an option since machineconfig-server is not responding.
Also creating a machineconfig with the expected name of old machine config will not help as current state will not match the state on disk.

**Steps to reproduce the issue:**
1. change a machineConfig so a new rendered machine config is generated. `oc edit mc <sth>`
2. delete old rendered machine congis `oc delete mc <old-rendered-mc>`

**Describe the results you received:**

**Describe the results you expected:**

MCO should be able to put the cluster in desired state, and be more stable to such machineConfig resources.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `oc adm release info --commits | grep machine-config-operator`:**

```
(paste your output here)
```

**Additional environment details (platform, options, etc.):**

**Comment by kikisdeliveryservice** [comment]
What is the reason that you are deleting the current rendered config during an update? This is not supported behavior and would be dangerous as the pool is in an intermediate state where some nodes indeed need to be and are on/using the "current" MC unless and until it is their turn to be upgraded to the desired config. You should allow updates to proceed and finish without removing the current rendered config that the nodes are still using.

**Comment by m-yosefpor** [comment]
What I was trying to illustrate here (by deleting old MCs during a MCD update) was only to show how fragile the MCO operations are. OKD is already stable to lots of changes/deletion on applied objects (which can be caused by human errors, or some component misconfiguration such as argocd or a 3rd party controller).

Deleting many of the cluster deployments/services/Routes/CRs will not cause much issues for OKD, as related operators will regenerate the required manifests to put the cluster in the desired state. Even if the configuration of the responsible operator is broken, CVO will first heal the CO and then the CO can heal other affected resources, and finally the cluster is expected to be in desired healthy state. However, MCO is fragile in this manner, and this serious dependency on old MCs during a node ignition update (which can not be regenrated by CO) can put the cluster in an unrecoverable state.

**Comment by arjunprasad2143** [comment]
This issue happened with us also. 
We wanted to delete an older MCP which was not required. Our engineer deleted the MC without waiting for the complete rollout of the new MCP. Now the nodes are in Not Ready state.
