### ISSUE TITLE
Migrating ovs-configuration from bash and providing declarative input

### ISSUE THREAD

**Issue by trozet** [openshift/machine-config-operator#2638]
Today when MCO is booted with an OVN deployment, a systemd service is executed that will configure OVS:

https://github.com/openshift/machine-config-operator/blob/master/templates/common/_base/units/ovs-configuration.service.yaml
https://github.com/openshift/machine-config-operator/blob/master/templates/common/_base/files/configure-ovs-network.yaml

Background:
The goal of the script is to take the NIC on the node that has default gateway access, and migrate it onto the OVS bridge. Basically this converts the NIC into a layer 2 port, connected to an OVS bridge. An internal port on the bridge (br-ex) clones the MAC of the NIC and acts as the layer 3 port. This allows the kernel to still use the IP and port, via the bridge. OVN then is able to directly send packets out of this bridge, without going through the kernel. This allows us to avoid SNAT'ing as well as providing some other advantages like doing hardware offload.

How the script works:
The bash detects characteristics about the original interface (like VLAN, bond, static ip, etc) and then generates new Network Manager key files which are laid down on the host and persist between reboots. The script runs without any user input, and automatically figures out how to generate the files to move the NIC onto the br-ex OVS bridge.

Issues:
1. The bash is not very maintainable, and we would like to move to golang or some alternative.
2. For 4.9, we are going to need to make multiple OVS bridges for certain use cases where a customer has multiple NICs and wants different NICs to handle different OVN traffic. That means moving multiple NICs to different OVS bridges, and we cannot automatically figure out the desired NIC to bridge mapping. That means we need some input during install time to know.
3. As is the case today, networking must be configured in OVS before kubelet starts. Otherwise pods will come up that depend on networking being ready, and it may not be truly ready.

Potential Solutions:
1. The user provides an NM state yaml file. NM state files are yaml files that declare how networking should be configured on the host. See https://nmstate.io/examples.html#interfaces-ovs-bridge for an example. This file can either be laid down with ignition or somehow be part of install time config.
2. We use the MCO first boot binary to launch a podman pod, that runs NM state. We use config from 1, to run an NM state pod which will generate all of the network manager keyfiles for us. If no config is provided, we have to do the same logic we do today by automatically generating an nm state file that will move the default interface NIC into OVS.
3. We add functionality to the MCO first boot binary that mimics what ovs-configuration does today in golang. Then we basically fork the NM state python logic into golang so we can handle multiple NICs. We still use the config from 1.
4. Modify the disk image before install to already have the NM keyfiles on it. This will cover use cases outside of the scope of this issue, including trying to install on nodes that are using a VLAN and cannot pxeboot over native. @cybertron has more details on this idea, but I dont think its possible in 4.9 timeframe.

**Comment by trozet** [comment]
@yuqi-zhang @cgwalters @fedepaol @cybertron thoughts?

**Comment by fedepaol** [comment]
> Today when MCO is booted with an OVN deployment, a systemd service is executed that will configure OVS:
> 
> https://github.com/openshift/machine-config-operator/blob/master/templates/common/_base/units/ovs-configuration.service.yaml
> https://github.com/openshift/machine-config-operator/blob/master/templates/common/_base/files/configure-ovs-network.yaml
> 
> Background:
> The goal of the script is to take the NIC on the node that has default gateway access, and migrate it onto the OVS bridge. Basically this converts the NIC into a layer 2 port, connected to an OVS bridge. An internal port on the bridge (br-ex) clones the MAC of the NIC and acts as the layer 3 port. This allows the kernel to still use the IP and port, via the bridge. OVN then is able to directly send packets out of this bridge, without going through the kernel. This allows us to avoid SNAT'ing as well as providing some other advantages like doing hardware offload.
> 
> How the script works:
> The bash detects characteristics about the original interface (like VLAN, bond, static ip, etc) and then generates new Network Manager key files which are laid down on the host and persist between reboots. The script runs without any user input, and automatically figures out how to generate the files to move the NIC onto the br-ex OVS bridge.
> 
> Issues:
> 
>     1. The bash is not very maintainable, and we would like to move to golang or some alternative.
> 
>     2. For 4.9, we are going to need to make multiple OVS bridges for certain use cases where a customer has multiple NICs and wants different NICs to handle different OVN traffic. That means moving multiple NICs to different OVS bridges, and we cannot automatically figure out the desired NIC to bridge mapping. That means we need some input during install time to know.
> 
>     3. As is the case today, networking must be configured in OVS before kubelet starts. Otherwise pods will come up that depend on networking being ready, and it may not be truly ready.
> 
> 
> Potential Solutions:
> 
>     1. The user provides an NM state yaml file. NM state files are yaml files that declare how networking should be configured on the host. See https://nmstate.io/examples.html#interfaces-ovs-bridge for an example. This file can either be laid down with ignition or somehow be part of install time config.
> 

This seems too low level to me.
The user has to know a lot of informations that we currently carve out of the interface we transform into an ovs bridge, such as mac address, ip and some other properties. That will be probably easier if https://bugzilla.redhat.com/show_bug.cgi?id=1934514 gets in.

>     2. We use the MCO first boot binary to launch a podman pod, that runs NM state. We use config from 1, to run an NM state pod which will generate all of the network manager keyfiles for us. If no config is provided, we have to do the same logic we do today by automatically generating an nm state file that will move the default interface NIC into OVS.
> 
>     3. We add functionality to the MCO first boot binary that mimics what ovs-configuration does today in golang. Then we basically fork the NM state python logic into golang so we can handle multiple NICs. We still use the config from 1.
> 

Why not using the go logic to get the properties we need, and THEN producing an nmstate yaml we can feed nmstate with?
From the user perspective, they'll just need to provide the nic(s) names and that's it.

>     4. Modify the disk image before install to already have the NM keyfiles on it. This will cover use cases outside of the scope of this issue, including trying to install on nodes that are using a VLAN and cannot pxeboot over native. @cybertron has more details on this idea, but I dont think its possible in 4.9 timeframe.

Not sure if I am missing something here, but how would we deal with different ips / mac addresses on different nodes? Would that require a custom image per node? And where would we take those informations from?

**Comment by yuqi-zhang** [comment]
Sorry I haven't had much time to think through this. I think the general direction of moving from a non-maintainable script to golang is good, but I am not certain I want to add more things to the MCO binary that is functionality specific (i.e. option 2/3 to add nmstate processing directly to the MCO).

If we wish to go down that route, I think we should consider that as part of overall MCO networking design, which has been a hot topic itself and has many stakeholders.

For option 1, which platforms would this be applicable to? If I understand correctly currently only baremetal has NMstate enabled. This is probably the "fastest" solution that requires the least design.

Option 4 sounds like related to the machine images pre-enhancement proposal that is floating around.

I think this also warrants a larger discussion, maybe in the arch call or office hours.

**Comment by pliurh** [comment]
I hope we can also put the smart NIC into consideration during the refactoring.

For the smart NIC use case, we may only have a pool of worker nodes with smart NIC and the reset don't. The host network setup is different between these pools, we don't need OVS running on the hosts which have smart NICs. It is not supported by MCO currently. As the ovs-configuration is part of the default machine config. It is rendered by MCO based on the CNI plugin type at cluster level.

Does it make sense that we render this machine config by CNO instead of MCO? So that we can 1)manage the host network at pool level, 2)have better collaboration on host nework configuration and CNI components.

**Comment by rbbratta** [comment]
Ran into an interesting corner case with Tang disk encryption.  QE vSphere testing had to switch from using `ifcfg` ignition files to kernel boot args for static IP and bonding (using the bonding process described here https://access.redhat.com/solutions/4762021 )

```
ip=<IP>::<Gateway>:<NetMask>:<HostName>:bond0:none nameserver=<DNS Server-IP> bond=bond0:<NIC NAME1>,<NIC NAME2>:mode=802.3ad,lacp_rate=fast,miimon=100,xmit_hash_policy=layer2+3
```

Will kernel cli args `ip=`, `bond=` get converted to `nmstate`?  Currently `ip=` is converted into `.nmconnection` files.
  
Tang/NBDE with Static IP address configuration on non-BM (vSphere) platform
https://docs.google.com/document/d/1rnAutjuxzUAauqOZwc8Iccl7SSZVWGJXH5VJL08YvTU/edit

> Documented procedure/workflow assumes the use of DHCP.  During boot, networking in the initramfs will default to DHCP, and, once the network is online, the system will be able to communicate with the Tang server to get the key to unlock the root device.  In environments with static IP configuration, this custom network configuration is only configured in the real root, not the initramfs.  In this situation there is no network connection configured in the initramfs during this phase of the boot process, the Tang server is inaccessible, and as a result the root device can’t be unlocked to complete the boot process.
