### ISSUE TITLE
MCD: Not cleaning up files whe removed from MC

### ISSUE THREAD

**Issue by ashcrow** [openshift/machine-config-operator#268]
See: https://bugzilla.redhat.com/show_bug.cgi?id=1663376

**Comment by kikisdeliveryservice** [comment]
Should be covered by[ deleteStaleData()](https://github.com/openshift/machine-config-operator/blob/7773bacc6e79829d3325f7747e076e96aebf7a4e/pkg/daemon/update.go#L273) I thought?

**Comment by kikisdeliveryservice** [comment]
So this is what [deleteStaleData()] (https://github.com/openshift/machine-config-operator/blob/7773bacc6e79829d3325f7747e076e96aebf7a4e/pkg/daemon/update.go#L273 ) does after an update is run.  But I don't know that `oc delete` is calling all of our functions like the same as deleting/updating via MCD does?
