### ISSUE TITLE
systemReservedCPU reservation using the auto reservation is smaller than the default one

### ISSUE THREAD

**Issue by e-minguez** [openshift/machine-config-operator#2747]
**Description**

systemReservedCPU reservation using the auto reservation is smaller than the default one.

**Steps to reproduce the issue:**
1. Have a system with 32 CPUs
2. Run the /usr/local/sbin/dynamic-system-reserved-calc.sh script 

**Describe the results you received:**

It calculates SYSTEM_RESERVED_CPU=0.15

**Describe the results you expected:**

The default one is 0.5 so I would expect more https://github.com/openshift/machine-config-operator/blob/master/pkg/controller/kubelet-config/helpers.go#L46 :

```
...
	if val, ok := userDefinedSystemReserved["cpu"]; ok {
		systemReservedCPU = val
	} else {
		systemReservedCPU = "500m"
	}
```

**Additional information you deem important (e.g. issue happens only occasionally):**

The calculations of the script for 32 cores:

```
+ recommended_systemreserved_cpu=0
+ (( 32 <= 1 ))
+ recommended_systemreserved_cpu=0.06
+ total_cpu=31
+ (( 31 <= 1 ))
++ echo 0.06 0.01
++ awk '{print $1 + $2}'
+ recommended_systemreserved_cpu=0.07
+ total_cpu=30
+ (( 30 <= 2 ))
++ echo 0.07 0.01
++ awk '{print $1 + $2}'
+ recommended_systemreserved_cpu=0.08
+ total_cpu=28
+ (( 28 >= 0 ))
++ awk '{print $1 + $2}'
+++ echo 28 0.0025
+++ awk '{print $1 * $2}'
++ echo 0.08 0.07
+ recommended_systemreserved_cpu=0.15
+ echo SYSTEM_RESERVED_CPU=0.15
```

**Output of `oc adm release info --commits | grep machine-config-operator`:**

Unrelated

**Additional environment details (platform, options, etc.):**

**Comment by kikisdeliveryservice** [comment]
Node team would own this value.

/assign @rphillips
