### ISSUE TITLE
Question: Is this ssh key check necessary: https://github.com/openshift/machine-config-operator/blob/d4dc34299e409010592d6c5d3d9bbbcdd572e2ac/pkg/daemon/update.go#L851

### ISSUE THREAD

**Issue by relyt0925** [openshift/machine-config-operator#2787]
I was just curious why the sshkey check specifically is there:
https://github.com/openshift/machine-config-operator/blob/d4dc34299e409010592d6c5d3d9bbbcdd572e2ac/pkg/daemon/update.go#L851

I believe it is supported in openshift to boot nodes without an ssh key. Just curious if someone has some background on that specific line

**Comment by relyt0925** [comment]
Note this was noticed in the `machine-config-daemon firstboot-complete-machineconfig`

Going to a payload that contains
`{"ignition":{"version":"3.1.0"},"passwd":{"users":[{"name":"core"}]}.....` (with no ssh key)

Since the initial payload initialized here has users nil: 
https://github.com/openshift/machine-config-operator/blob/d4dc34299e409010592d6c5d3d9bbbcdd572e2ac/pkg/daemon/daemon.go#L543

and the new payload has a user with no ssh key this code path is triggered:
https://github.com/openshift/machine-config-operator/blob/d4dc34299e409010592d6c5d3d9bbbcdd572e2ac/pkg/daemon/update.go#L773
https://github.com/openshift/machine-config-operator/blob/d4dc34299e409010592d6c5d3d9bbbcdd572e2ac/pkg/daemon/update.go#L785

And then it fails out. I believe if the len(tempUser.SSHAuthorizedKeys) >= 1 check is removed it would work

**Comment by sinnykumari** [comment]
This could be bug in the code but so far we didn't hit this issue in MCO. Can you please provide exact steps to reproduce the issue?

**Comment by relyt0925** [comment]
I can! 

So this is in regards to the newer hypershift repo/offering:
https://github.com/openshift/hypershift


It is on the `machine-config-daemon firstboot-complete-machineconfig` command.

Steps to reproduce:

1) Place any ignition config that contains a section defining the core user without any ssh keys at 
`/etc/ignition-machine-config-encapsulated.json`

2) run `machine-config-daemon firstboot-complete-machineconfig` and it will error on the ssh check. However: I believe it should pass since no ssh keys is a valid configuration.

**Comment by relyt0925** [comment]
This can be done on any RHCOS box (doesn't need to be a part of an active openshift cluster: can be done by just booting the RHCOS box up with a basic ignition config.

**Comment by cgwalters** [comment]
> This can be done on any RHCOS box (doesn't need to be a part of an active openshift cluster: can be done by just booting the RHCOS box up with a basic ignition config.

I don't think that's true, because the MCD and the `machine-config-daemon-firstboot.service` etc. are part of the Ignition rendered by the MCO.  So presumably you are at least manually including that in the Ignition?

**Comment by yuqi-zhang** [comment]
For all default OCP installs, the installer generates a MC that has sshkeys in it. I think this was likely originally wrote with that in mind. I am not sure if not providing a sshkey affects functionality at all. If not, maybe we can relax that check a bit.

You can "reproduce" this by deleting the installer provided ssh key on any OCP cluster I believe.
