### ISSUE TITLE
Support custom config pool on master nodes

### ISSUE THREAD

**Issue by valumar** [openshift/machine-config-operator#2842]
Since Openshift officially supports 3 nodes cluster installation Machine Config Operator should support custom pools on master nodes.

**Comment by sinnykumari** [comment]
If you want to create custom pool, you can do it with worker pool. I don't understand why MCO should support custom pool based on master node? Can you please provide reason?

**Comment by kikisdeliveryservice** [comment]
closing due to lack of response
