### ISSUE TITLE
How to I add machineconfigpool named infra to the cluster

### ISSUE THREAD

**Issue by jatanmalde** [openshift/machine-config-operator#294]
Hello.

I currently only see two default `machineconfigpool` with the installation
```
[root@localhost ~]# oc get machineconfigpool
NAME      AGE
master    6d
worker    6d
[root@localhost ~]# 

```
How do I tell installer about additional `machineconfigpool` for the cluster so that I can have some infra nodes on the cluster.

Please advice on it.

**Comment by wking** [comment]
The essiest way is to add additional machine(set)s and machineconfigpools as day-2 operations.  There is very little difference between you pushing those into the cluster after the installer succeeds and getting the installer to push them for you.

**Comment by jatanmalde** [comment]
@wking I agree to your point, How could I add the `machineconfigpool` prior installation.

Lets say if I want to add another `machineconfigpool`. How can I achive that?

Thanks.

**Comment by wking** [comment]
> I agree to your point, How could I add the machineconfigpool prior installation.

If you agree about it being easiest as a day-2 change, why do you care about adding these prior to installation?  Just push the objects you want into the cluster post-install.

**Comment by jatanmalde** [comment]
@wking I did not find the Day2 -operation sections. If you can post the link then that would help.

I can take look at it once to see how can I add machineconfigpool?

Thanks

**Comment by wking** [comment]
I dunno if there are docs for this yet, but if you want a new machineconfig pool, you can probably yse the existing worker pool as a template.

**Comment by wking** [comment]
Looks like there may eventually be docs [here][1].

[1]: https://github.com/openshift/training/blob/master/docs/compute/09-multiple-machine-pools.md

**Comment by runcom** [comment]
@wking just to iterate on this one, is it possible today, as a day-2 operation, to bring up instances on aws and mark them in a new MCpool? I've tried scaling the worker set, creating a machine pool and a machine config but everything blew up cause previous machine configs tied to "worker"s role are taking over anyway. Just trying to find a pointer to follow so I can test this out further.
