### ISSUE TITLE
support removing SSH keys entirely

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#296]
Ref: https://github.com/openshift/machine-config-operator/pull/115#discussion_r246809985

Currently if a user provides an SSH key to the installer, then decides to remove it, the MCD will silently keep the last specified key.

In https://github.com/openshift/machine-config-operator/issues/292 we fixed a panic when the `user` section was empty.  I think we should take the next step and remove the authorized keys.

The concrete scenario here is an administrator who initially provides a SSH key just to give themselves a "fallback", then gains confidence in the system and decides to remove it.

**Comment by kikisdeliveryservice** [comment]
I'll work on this, but I will note that there is a difference between an empty Passwd:User section and an empty User:SSHAuthorizedKeys section. This issue would cover the latter case as opposed to the former.

**Comment by ashcrow** [comment]
Is this something we still need/want to do or should we go ahead and close this issue?

**Comment by fgimenezm** [comment]
This is even harder in latest versions. Removing the ssh MachineConfig now tries to remove the "core" user altogether which is not possible and makes the MCO fail to update the nodes.

**Comment by kikisdeliveryservice** [comment]
This could be optimized, but currently if you'd like to remove ssh keys, you may update the sshkey MC to explicitly have sshkeys: []

**Comment by fgimenezm** [comment]
> This could be optimized, but currently if you'd like to remove ssh keys, you may update the sshkey MC to explicitly have sshkeys: []

This doesn't work. I results in this message being logged:
    Message:               Node lab1-czvfr-master-0 is reporting: "can't reconcile config rendered-master-03e6e309d18a7fe4295351a4afd58d80 with rendered-master-aac2805716bf9df925f7608973f6de83: ignition passwd user section contains unsupported changes: user must be core and have 1 or more sshKeys: unreconcilable"

That is because of this code here: https://github.com/kikisdeliveryservice/machine-config-operator/blob/c415ce6aed25604bc1d2478951db16759dac31f6/pkg/daemon/update.go#L850

**Comment by kikisdeliveryservice** [comment]
Ah yes sorry that is correct, you will need to supply 1 or more sshkeys.
