### ISSUE TITLE
Question: api.ci.openshift.org returns no such host when following hacking doc

### ISSUE THREAD

**Issue by koly23** [openshift/machine-config-operator#3003]
Hello,

When I am following the hacking document(https://github.com/openshift/machine-config-operator/blob/master/docs/HACKING.md), I cannot open api.ci.openshift.org.
When I use oc login --server=https://api.ci.openshift.org, it returns "no such host". Maybe the site is down or the name is changed, can anyone update the hacingk doc?

**Comment by sqwaseda** [comment]
Good issue
Totally agree!
