### ISSUE TITLE
MCO should taint only CoreOS nodes on ssh

### ISSUE THREAD

**Issue by vrutkovs** [openshift/machine-config-operator#304]
Related to https://github.com/openshift/machine-config-operator/pull/289

The process of joining RHEL nodes to the cluster involves ssh'ing (using Ansible) to the node and applying Ignition config. The node would join the cluster but would be tainted.

While we could un-taint the node using Ansible it would still be a bad UX for the customers. Some customer services restart might be required on new RHEL hosts, so regular untainting the nodes would be annoying

**Comment by ashcrow** [comment]
Agreed. :+1:

**Comment by ashcrow** [comment]
The actual tainting process should not happen on non RHCOS systems. The portion of code which actually detects and reports the SSH is part of RHCOS itself. Did you see a taint from SSHing to RHEL or is this more of a reminder that it shouldn't be added to RHEL?

**Comment by vrutkovs** [comment]
Right, RHEL nodes are not being tainted - as sshd_config is not being modified
