### ISSUE TITLE
Machine Config Operator is root in cluster

### ISSUE THREAD

**Issue by abhinavdahiya** [openshift/machine-config-operator#31]
MCO manages `ClusterRoles` and `ClusterRoleBindings` so that MachineConfig{Controller, Server, Daemon} can access and manage:
1. CRDs
2. MachineConfigs and Pools (cluster scoped)
3. Node annotation updates

Should MCO be given root access to cluster?

/cc @aaronlevy @eparis

**Comment by ashcrow** [comment]
I tend to think that MCO shouldn't have root like access to the cluster, but instead have specific access granted to CRDs, MCs, Pools, and annotation modification abilities. Unless, of course, finer grained access isn't possible, though I think it's likely doable with roles and service accounts.

**Comment by aaronlevy** [comment]
Overall agree - however, a sort of unanswered question is how we want to deal with setting up the roles that each SLO needs (and what the managed components of the SLO need). 

We could have the TLO  be responsible for this, but it does have some risk that state of the SLO (and SLO components) are bleeding into TLO and are less self-contained.

For the TLO we were going to assume a `/manifests` directory exists in each SLO container image, and this is what the operator needs to run (and will be blindly applied by the TLO) - but it's unclear if this should also contain roles for the components that the SLO manages (e.g. machineConfigDaemon might have a more restrictive role than than MachineConfigOperator).

So this could look something like:

```
10-mco-role.yaml
20-mcd-role.yaml
15-mco-deployment.yaml
```

Side note - we probably need some kind of declarative deletion behavior on the `/manifests` directory - as roles/objects might be removed as well.

/cc @smarterclayton

**Comment by smarterclayton** [comment]
I think the manifest should declare their roles.  We should periodically do
a review of the roles.  Every operator should define their own role and we
review it in situ.

Good point on the deletion, if CVO was grabbing new manifest and old
manifest we would know, but we don't know that in the model where the CVO
image has the manifests layered on top.  Also, we probably need to preserve
declarative deletes over many updates.  Did x-operator have a model for
this?

**Comment by eparis** [comment]
I tend to believe that {Cluster,}Role{,Bindings} needed by the SLO should be declared in /manifests and should be blindly applied by the CVO.

Delete sounds hard.

**Comment by aaronlevy** [comment]
I think "needed by the SLO" everyone is pretty much in agreement. But do we extend that to "Needed by all components managed by the SLO". For example, Network-Operator (SLO) might have one role/binding, while Calico (component manged by SLO) has its own role/binding.

It gets a little weird with assuming that all {Cluster,}Role{,Bindings} are the responsibility of CVO. In some cases the SLO managed components might be optional and not always installed (e.g. user chooses flannel vs calico - which translates into different role/binding needs). We could always create both, but this was the more unknown behavior.

> Also, we probably need to preserve declarative deletes over many updates. Did x-operator have a model for this?

We had label based pruning: https://github.com/coreos-inc/tectonic-operators/blob/master/x-operator/Documentation/design.md#pruning-components

**Comment by cgwalters** [comment]
The MCO has the ability to write arbitrary files to the host.  That can't really change, so...closing.
