### ISSUE TITLE
keepalived can keep ingress VIP on wrong node under certain circumstances

### ISSUE THREAD

**Issue by nvsmirnov** [openshift/machine-config-operator#3155]
**Description**

If string representation of IP an address of one node is a part of string representation of IP of another node, then keepalived make wrong decision about which node is running ingress at the time.

I.E., in this scenario:
nodeA is 10.12.11.10
nodeB is 10.12.11.11
nodeC is 10.12.11.101
nodeD is 10.12.11.102
So, nodeA IP as a strig is part of nodeB and nodeC IPs. 
On my (failed) installation, keepalived decided that ingress is running on nodeA, but it was running on another node.

**Steps to reproduce the issue:**
1. I created a cluster with master node IPs x.x.x.10-.12, and worker node IPs x.x.x.100-102.

**Describe the results you received:**
keepalived was keeping ingress VIP on master node x.x.x.10, although real ingress is on worker node x.x.x.100.

**Describe the results you expected:**
keepalived shoud keep VIP on node which runs ingress.

**Additional information you deem important (e.g. issue happens only occasionally):**
If I figured all correctly, I believe the cause is in /etc/keepalived/chk_default_ingress.sh, which is created from templates/common/on-prem/files/keepalived-script-default-ingress.yaml

Fix is trivial (if we don't wont to re-work checks in more efficient way than running many grep's):
Change IP regexp so it includes EOL sign, like grep -q 'x.x.x.x$'.
Now:
```
    /host/bin/oc --kubeconfig /var/lib/kubelet/kubeconfig get ep -n openshift-ingress router-internal-default -o yaml | grep 'ip:' | grep -q {{`{{.NonVirtualIP}}`}}
```
New:
```
    /host/bin/oc --kubeconfig /var/lib/kubelet/kubeconfig get ep -n openshift-ingress router-internal-default -o yaml | grep 'ip:' | grep -q '{{`{{.NonVirtualIP}}`}}$'
```

**Output of `oc adm release info --commits | grep machine-config-operator`:**
```
  machine-config-operator                        https://github.com/openshift/machine-config-operator                        f70f2811ec1f6c5057caada406df0a20c477bfc1
```

**Additional environment details (platform, options, etc.):**

**Comment by kikisdeliveryservice** [comment]
This sounds like it needs a bugzilla opened for tracking and review.

**Comment by nvsmirnov** [comment]
Opened bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=2089775

**Comment by kikisdeliveryservice** [comment]
I'm going to close this issue and let the team track via the [BZ that you opened.](https://bugzilla.redhat.com/show_bug.cgi?id=2089775) Thanks so much for doing that @nvsmirnov much appreciated!
