### ISSUE TITLE
How to recover from 'Degraded' status

### ISSUE THREAD

**Issue by jianlinliu** [openshift/machine-config-operator#320]
Sometime I created a wrong customized machineconfig, once I applied it to my cluster, some node will to to "Degrated" status for ever, how to correct and recover it?

**Comment by cgwalters** [comment]
We're discussing this in https://github.com/openshift/machine-config-operator/issues/254

/close

**Comment by cgwalters** [comment]
Here's a direct link to a comment with hopefully useful information: https://github.com/openshift/machine-config-operator/issues/254
