### ISSUE TITLE
Avoid kubernetes node port range (II)

### ISSUE THREAD

**Issue by jgato** [openshift/machine-config-operator#3205]
**Description**

We have hit a bug solved on this commit:

https://github.com/openshift/machine-config-operator/commit/675c770f65f095ecda2508b9543c6ca8e0b931f4

But we are wondering...  would it happen the same about this:

https://github.com/openshift/machine-config-operator/blob/675c770f65f095ecda2508b9543c6ca8e0b931f4/templates/master/00-master/on-prem/files/haproxy-haproxy.yaml#L20

Who is setting the '.LBConfig.LbPort'. In principle we see:

```
# cat /etc/haproxy/haproxy.cfg 
global
  stats socket /var/lib/haproxy/run/haproxy.sock  mode 600 level admin expose-fd listeners
defaults
  maxconn 20000
  mode    tcp
  log     /var/run/haproxy/haproxy-log.sock local0
  option  dontlognull
  retries 3
  timeout http-request 30s
  timeout queue        1m
  timeout connect      10s
  timeout client       86400s
  timeout server       86400s
  timeout tunnel       86400s
frontend  main
  bind :::9445 v4v6
  default_backend masters
listen health_check_http_url
  bind :::9444 v4v6
  mode http
  monitor-uri /haproxy_ready
  option dontlognull
listen stats
  bind localhost:30000
  mode http
  stats enable
  stats hide-version
  stats uri /haproxy_stats
  stats refresh 30s
  stats auth Username:Password
backend masters
   option  httpchk GET /readyz HTTP/1.0
   option  log-health-checks
   balance roundrobin
   server master-0.el8k-ztp-1.hpecloud.org 10.19.10.103:6443 weight 1 verify none check check-ssl inter 1s fall 2 rise 3
   server master-1.el8k-ztp-1.hpecloud.org 10.19.10.105:6443 weight 1 verify none check check-ssl inter 1s fall 2 rise 3
   server master-2.el8k-ztp-1.hpecloud.org 10.19.10.107:6443 weight 1 verify none check check-ssl inter 1s fall 2 rise 3

```

which is '30000', that is in the NodePort range, and other SVC would be assigned to that port. Actually, it happened in one environment.
Should this  .LBConfig.LbPort not been using that range?

**Comment by cybertron** [comment]
Yes, but that's not defined in MCO. It was fixed in https://github.com/openshift/baremetal-runtimecfg/pull/175

**Comment by sinnykumari** [comment]
Closing since concern has been already taken care in https://github.com/openshift/baremetal-runtimecfg/pull/175
