### ISSUE TITLE
Round off SYSTEM_RESERVED_MEMORY if value is in decimal. 

### ISSUE THREAD

**Issue by kenneth-dsouza** [openshift/machine-config-operator#3298]
**Description**

Currently the recommended system reserved size obtained when autoSizingReserved is set can also be in decimal.
If this value is in decimal, it will affect the allocated memory calculation. 
It will come down to float value and expressing this in Kib format becomes difficult later. Due to this we express the value in m instead of Kib

https://pkg.go.dev/k8s.io/apimachinery/pkg/api/resource#NewMilliQuantity

**Steps to reproduce the issue:**
1.  Pass RAM size as 377Gi
2.   autoSizingReserved code recommends size as 14.3Gi

Expressing 14.3Gi in to bytes will turn out to be 15354508083.2 bytes

Gi = GiB = Gibibyte. 1Gi = 2³⁰ = 1,073,741,824 bytes
Mi = MiB = Mebibyte. 1Mi = 2²⁰ = 1,048,576 bytes
Ki = KiB = Kibibyte. 1Ki = 2¹⁰ = 1,024 bytes

[Allocatable memory] = [Node Capacity] - [system-reserved] - [Hard-Eviction-Thresholds] 

[Node Capacity] = 395911864Ki
 [system-reserved] =  14.3Gi ( This will be set on basis if autoSizingReserved is true or false, if false it will be set to default value 1Gi if not set in kubelet.conf)
 [Hard-Eviction-Thresholds] = 100Mi ( This is the default value if not set)

[Allocatable memory] = 405413748736  - 15354508083.2 - 104857600 = 389954383053 bytes 

This will get expressed in milli quantity instead of Kib due to fraction value.

**Describe the results you received:**
SYSTEM_RESERVED_MEMORY=14.3Gi

**Describe the results you expected:**
SYSTEM_RESERVED_MEMORY=14Gi

I have a patch ready to round off the value. This will help us to make sure that we get SYSTEM_RESERVED_MEMORY always in power of 2^n. 

```
 git diff
diff --git a/templates/common/_base/files/kubelet-auto-sizing.yaml b/templates/common/_base/files/kubelet-auto-sizing.yaml
index cdb0c6d13..b158d8784 100644
--- a/templates/common/_base/files/kubelet-auto-sizing.yaml
+++ b/templates/common/_base/files/kubelet-auto-sizing.yaml
@@ -40,6 +40,7 @@ contents:
         if (($total_memory >= 0)); then # 2% of any memory above 128GB
             recommended_systemreserved_memory=$(echo $recommended_systemreserved_memory $(echo $total_memory 0.02 | awk '{print $1 * $2}') | awk '{print $1 + $2}')
         fi
+        recommended_systemreserved_memory=$(echo $recommended_systemreserved_memory | awk '{printf("%d\n",$1 + 0.5)}') # Round off so we avoid float conversions
         echo "SYSTEM_RESERVED_MEMORY=${recommended_systemreserved_memory}Gi">> ${NODE_SIZES_ENV}
     }
     function dynamic_cpu_sizing {
```

**Comment by sinnykumari** [comment]
cc @harche maybe interesting to look at

**Comment by harche** [comment]
Thanks @kenneth-dsouza. Can you open the PR against MCO repo?

**Comment by kenneth-dsouza** [comment]
Ack @harche, will open it soon.
