### ISSUE TITLE
Remove Dockerfile.rhel7

### ISSUE THREAD

**Issue by LorbusChris** [openshift/machine-config-operator#3309]
As RHEL7 isn't supported as base OS in OpenShift anymore, `Dockerfile.rhel7` should be removed accordingly.

There seems to be some automation in place to update its contents from `Dockerfile`. That should be removed, as well as all references to it in the `release` repo should be changed to ref `Dockerfile` instead.

**Comment by kikisdeliveryservice** [comment]
I had a PR for this but it autoclosed bc stale: https://github.com/openshift/machine-config-operator/pull/3002
