### ISSUE TITLE
realtime kernel enablement relies on delta from past machine state which doesn't exist in hypershift

### ISSUE THREAD

**Issue by relyt0925** [openshift/machine-config-operator#3468]
To enable the realtime kernel: currently the machine config operator looks at the delta between the previous machine config and the current proposed machine config and if realtime kernel has been selected proceeds to run this code:
https://github.com/openshift/machine-config-operator/blob/6a59f30edc594e7d2bdebc721541b2a0ccd35325/pkg/daemon/update.go#L1175-L1211

The problem for hypershift is the combination of two things:
1) The previous machine config isn't persisted and therefore there is always an empty machine config for the "previous machine config"
2) The enablement option cannot be reran twice: if that code is ran on a node with a realtime kernel already enabled the rpm-ostree commands fail with "kernel not found" (fails removing the packages as they have been removed and does not gracefully handle that failing the upgrade)

This means that for hypershift: in place upgrades using the real time kernel are not working. I am curious if we can make the automation for real time kernel enablement be more graceful when running on a machine with the real time kernel already enabled (meaning it can skip some of the removal and reset steps). If it was able to gracefully run in that mode: real time kernel could be utilized in hypershift environments.

**Comment by relyt0925** [comment]
The problem is the upgrades for the real time kernel are not truly "reconciled". The kernel type and associated automation that ran is actually done as a diff between what the "old machine config" had and what the new machine config has:
https://github.com/openshift/machine-config-operator/blob/48e94f504efceaa40a9e6c4d11f6abb279df3608/pkg/daemon/update.go#L813





lisowski
  [8 minutes ago](https://coreos.slack.com/archives/C01C8502FMM/p1672335996553159?thread_ts=1672335791.380739&cid=C01C8502FMM)
In the case of "runFirstbootCompleteMachineConfig" it is always empty:
https://github.com/openshift/machine-config-operator/blob/48e94f504efceaa40a9e6c4d11f6abb279df3608/pkg/daemon/daemon.go#L926
And therefore every update with real time kernel enabled it tries and go through the process of converting from regular kernel to realtime kernel which is not setup currently to pass when ran on a machine with a real time kernel already enabled


lisowski
  [6 minutes ago](https://coreos.slack.com/archives/C01C8502FMM/p1672336136616949?thread_ts=1672335791.380739&cid=C01C8502FMM)
currently that is done by this code here:
https://github.com/openshift/machine-config-operator/blob/6a59f30edc594e7d2bdebc721541b2a0ccd35325/pkg/daemon/update.go#L1175-L1211
I am wondering if we can make that process a little more graceful to be able to work without relying on looking at "past information"

**Comment by relyt0925** [comment]
cc @yuqi-zhang who I have been chatting with about this

**Comment by cgwalters** [comment]
> The previous machine config isn't persisted and therefore there is always an empty machine config for the "previous machine config"

This will cause serious problems down the line; specifically older files will silently persist, creating [hysteresis](https://blog.verbum.org/2020/08/22/immutable-%E2%86%92-reprovisionable-anti-hysteresis/).

This however is another bug that will be fixed by layering, xref https://github.com/openshift/machine-config-operator/issues/3137 - if the state of the node is always a container image, then bootc/rpm-ostree always handle transitioning between states and there's no MachineConfig or Ignition that needs diffing.

**Comment by yuqi-zhang** [comment]
Hi @relyt0925 , sorry for the delay, just looking through some of the logic,

For https://github.com/openshift/machine-config-operator/blob/48e94f504efceaa40a9e6c4d11f6abb279df3608/pkg/daemon/daemon.go#L926 this is only run on newly provisioned machines. Are you saying that in your case, there is an RHCOS machine that before joining the cluster for the first time, is already set up with the RT kernel?

In Hypershift we have two modes of nodepools: inplace and replace
 - inplace basically uses the current state on the system, so it should not detect a diff, and actually runs the regular MCD
 - replace should be starting with a completely new node each time, so you shouldn't have RT kernel yet (and thus no previous state

Is there a third operation that IBM clusters are doing that I am missing the context for?

**Comment by relyt0925** [comment]
Hey!

Ok that makes sense! The system used on the IBM side in Satellite predates that logic and actually uses complete-firstboot. Part of the reason for this is there is a necessesity for full control of worker upgrades at an individual worker level (cannot just automatically roll out across all nodes in a nodepool). 

So it effectively reignites the node through the complete-firstboot path with the latest machine config everytime an upgrade is triggered. 

However: if the path going on currently for the machine config path works that same strategy can be adopted (running the machine-config-daemon and that will look at current state versus an empty diff).
