### ISSUE TITLE
daemon: unable to rotate token error

### ISSUE THREAD

**Issue by yuqi-zhang** [openshift/machine-config-operator#358]
After the daemon has been running for ~5 minutes, it starts to spam:

`E0131 21:27:01.343248   29281 token_source.go:132] Unable to rotate token: failed to read token file "/var/run/secrets/kubernetes.io/serviceaccount/token": open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory`

repeatedly in the daemon logs. It does not seem to otherwise affect daemon behaviour.

**Comment by abhinavdahiya** [comment]
Is this happening only for daemon? And all other pods, operator, controller, server are working?

**Comment by yuqi-zhang** [comment]
Operater/controller/server seem to be fine. Although I specifically rebuilt the daemon from the `master` branch myself.

**Comment by abhinavdahiya** [comment]
It might have to do with chroot after client has been created [here](https://github.com/openshift/machine-config-operator/pull/46)

**Comment by abhinavdahiya** [comment]
daemon needs to be able to rotate its credentials.

**Comment by yuqi-zhang** [comment]
If that's the case I'm surprised we haven't seen this earlier, unless token rotation is relatively new?

I can check whether this happens with a fresh cluster from `master` of the installer to make sure whether changing image and rebooting does something wonky.

**Comment by kikisdeliveryservice** [comment]
@ashcrow how long lived would we be looking for?

**Comment by ashcrow** [comment]
I don't know how often the rotation occurs by default unfortunately.

**Comment by cgwalters** [comment]
Yeah we should probably back off the chroot into the host rootfs...though that is going to require some nontrivial reworking in the code.

**Comment by kikisdeliveryservice** [comment]
Someone else also saw this in a new cluster from today (logs are in the link above).

**Comment by derekwaynecarr** [comment]
i hit this on a cluster < 1hr.  i discovered it when i appeared to have a master show "degraded" state while trying to apply a new update payload, and not sure what to do to debug further.  fwiw, i see the token is in pod.
