### ISSUE TITLE
[RFE] pre/post application hooks, reboot definition

### ISSUE THREAD

**Issue by thoraxe** [openshift/machine-config-operator#360]
It came up in conversation today that it might be useful to be able to define pre/post application hooks and/or define whether or not node reboots are required. While sysctls aren't an ideal use case, they are a somewhat realistic one.

For example, on a regular system, applying a sysctl involves adding an `/etc/sysctl.d` file and then executing something like `sysctl -p`. A reboot isn't required to apply the change, but it would definitely make the change take effect.

In this particular instance, after the `MachineConfig` was applied (file created), the `post-application-hook` would be to execute `sysctl -p`. No further action (reboot) would be required. So you could have another flag that was `reboot-required: false` or something.

The chrony example in the machine-config-operator documentation is also realistic. I don't need to reboot the node just to apply the chrony config -- a post-application hook (systemctl restart chrony or similar) would be sufficient.

I can't think of a good pre-application hook example. 

Note that "application" here means "applying the configuration to the relevant nodes".

**Comment by runcom** [comment]
I believe this makes sense and most of the time applying a MachineConfig doesn't really require an update (the case I have in mind is changing the crio configuration through the CRD, that just requires a `systemctl restart crio.service`). Chrony and sysctls are other great examples as post-hooks.
As for pre-hooks, not sure if we do already have something, but one could set up something to rename a file before updating it (`mv file file.bak`) for some reason.

I'm not really fond on the _application_ naming though but we can bikeshed on that soon I guess.

> So you could have another flag that was `reboot-required: false` or something.

While this might makes sense to lock down what users can/cannot do, I fear everyone else could/would come up with his own requirements and ask us to implement another knob for their own purposes. So, an example of hooks can be found in runc when people can set up their stuff pre/post container stuff and as long as it adheres to the specification, everything should be good.

There could also be other mean to have something like this if we have plugins on special hardware and configuration as well probably (reload gpus stuff w/o rebooting for instance, not sure though).

**Comment by sdodson** [comment]
Sounds dangerously close to MCO becoming a re-implementation of ansible tasks. Following the discussion here.

**Comment by cgwalters** [comment]
There's also the general pattern we have of defining custom CRDs for things.  Today the kubelet bits are a special sub-controller; could imagine e.g. having a "NTP confg" CRD, and also teach the MCD how to live-apply NTP config changes.

**Comment by jlebon** [comment]
Yeah, not a big fan of adding (to borrow a word from the RPM world) scriptlets. The way I was thinking about it, any kind of "skip reboot" optimization should probably live in the MCD itself since the MCD knows exactly what the diff is from the previous to the next config. (And it's flexible of course how that code plugs into the MCD, I think we were discussing a plugin system at some point?)

**Comment by kikisdeliveryservice** [comment]
Along the lines of what @jlebon this seems outside of what the MCD is intended to do, ie apply changes in a controlled/predictable way. The ability for users to change the fundamental behavior so much could also really affect troubleshooting/maintenance/expectations down the line.  I think it makes more sense for the MCD itself to define what it will do and how, which seems more in-line with our push to a self-managed cluster.
