### ISSUE TITLE
Early ssh access detection 

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#379]
I'm surely missing some context but I believe the issue still holds. Anyone can currently ssh into nodes before the MCD runs or the login monitor goroutines is started leaving a window open where we won't detect that.

~~I was thinking (wrongly cause I don't know the installer code probably), can we completely disable the sshd service between the installer ending needing it, and have the MCD itself then start it through the systemd dbus api? Just a random thought (and guess) but I believe we can keep brainstorming here.~~

**Comment by cgwalters** [comment]
https://github.com/openshift/machine-config-operator/pull/359#issuecomment-459746749

**Comment by ashcrow** [comment]
/assign @runcom 

Since there is a PR that will close this issue.
