### ISSUE TITLE
Degradation of nodes should provide better information

### ISSUE THREAD

**Issue by ashcrow** [openshift/machine-config-operator#382]
Currently when a node goes into `degraded` it can be hard to figure out why this is the case. Some possibilities include:

- Unable to parse a section of the MC
- Unable to apply the `Ignition` configuration
- Unable to `pivot` to an operating system update

Ideally, when the MCD decides the node should be `degraded` it should bubble up information as to why.

/cc @derekwaynecarr @imcleod @runcom

**Comment by runcom** [comment]
I believe I've seen something about adding an annotation to explain that (`degradedReason` or something like that?)

**Comment by ashcrow** [comment]
@runcom could work ... though if we can get the information in a way that is shown easily in the UI that would be even better.

**Comment by cgwalters** [comment]
See also https://github.com/openshift/machine-config-operator/issues/234

**Comment by kikisdeliveryservice** [comment]
For the MCs that info should be easy since it's coming down to reconcilable() but a side effect that I can see is lots of confusion as to why a node completely degrades just bc a MC is incorrect: #254

**Comment by cgwalters** [comment]
Marking as dup of https://github.com/openshift/machine-config-operator/issues/234
