### ISSUE TITLE
install ClusterOperator CRD as part of release payload

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#383]
Currently we install it dynamically; this means the CVO is unaware of our status and won't e.g. error out if we start failing.

Doing this will be a way to get gating on degraded status.

**Comment by cgwalters** [comment]
Example: https://github.com/openshift/cluster-kube-controller-manayger-operator/blob/master/manifests/0000_12_kube-controller-manager-operator_07_clusteroperator.yaml

**Comment by cgwalters** [comment]
And then we'd need to start e.g.

```
diff --git a/pkg/operator/status.go b/pkg/operator/status.go
index 066f289..2d365a2 100644
--- a/pkg/operator/status.go
+++ b/pkg/operator/status.go
@@ -114,12 +114,6 @@ func (optr *Operator) syncFailingStatus(ierr error) error {
 
 func (optr *Operator) fetchClusterOperator() (*configv1.ClusterOperator, error) {
 	co, err := optr.configClient.ConfigV1().ClusterOperators().Get(optr.name, metav1.GetOptions{})
-	if meta.IsNoMatchError(err) {
-		return nil, nil
-	}
-	if apierrors.IsNotFound(err) {
-		return optr.initializeClusterOperator()
-	}
 	if err != nil {
 		return nil, err
 	}
```

Looking at the code in the CKCMO repo I think we need this:

```
	v1helpers.EnsureOperatorConfigExists(
		dynamicClient,
		v311_00_assets.MustAsset("v3.11.0/kube-controller-manager/operator-config.yaml"),
		schema.GroupVersionResource{Group: operatorv1.GroupName, Version: operatorv1.GroupVersion.Version, Resource: "kubecontrollermanagers"},
	)

```

**Comment by runcom** [comment]
> Looking at the code in the CKCMO repo I think we need this:

we'll also need something like `status.NewClusterOperatorStatusController(` from `github.com/openshift/library-go/pkg/operator/status` as other operator uses + I believe https://github.com/openshift/machine-config-operator/pull/351 must be reworked now to use `library-go` as well.

**Comment by abhinavdahiya** [comment]
https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/clusteroperator.md

CVO will NOT install your clusteroperator

**Comment by runcom** [comment]
> CVO will NOT install your clusteroperator

@abhinavdahiya could you elaborate on that and tell me how to proceed? like, is there code you can point me to so I can check there? I assumed https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/clusteroperator.md#why-i-want-clusteroperator-custom-resource-in-manifests would just take and apply the CO
