### ISSUE TITLE
worker nodes go NotReady after a while

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#389]
Spotting this on clusters I leave running during the night, the next day, workers are just dead. Not sure if it's us, but worth investigating if you also see this (I believe someone else saw this as well). If it's known, please feel free to close this issue.

**Comment by sjenning** [comment]
Introduced by https://github.com/openshift/cluster-kube-controller-manager-operator/pull/132 and fixed in https://github.com/openshift/cluster-kube-controller-manager-operator/pull/147
