### ISSUE TITLE
Substitute pkg/ with internal/

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#398]
Code within pkg/ here is by no mean intended to be used outside of this project. Since Go 1.4 we can move everything under pkg/ to internal/ so we can only use our stuff and nobody else could vendor and use it (that's our code and not intended to be imported anyway). Go enforces it of course https://golang.org/doc/go1.4#internalpackages

I'm also trying to understand if code under lib/ is just a fork, or it's properly vendored with dep or whatever. In case it's not, we need to work that out to make into vendor as well if it's reusable code. Of course, lib/ is also meant to be used by just ourselves so move it under internal/ as well.

This is a list of packages to be moved and or packages to remain there https://github.com/openshift/machine-config-operator/issues/398#issuecomment-462433426
```
The following packages are most definitely supposed to be used outside this project.

* `pkg/apis`
* `pkg/generated`
* `/pkg/controller/common/constants.go`
* `pkg/daemon/constants/constants.go`

while these can be used outside:

* `pkg/daemon/rpm-ostree.go`
```
In addition to the above, we should be moving the clientsets under `cmd/common` to `internal/` to be shared across the project and tests.

**Comment by ashcrow** [comment]
:+1: to moving to `internal`.

I don't believe `lib/` is vendored.

**Comment by runcom** [comment]
> I don't believe `lib/` is vendored.

too bad, worth understanding why is that and how we can move to that direction instead of using forks

**Comment by ashcrow** [comment]
@abhinavdahiya :arrow_up:

**Comment by abhinavdahiya** [comment]
> Code within pkg/ here is by no mean intended to be used outside of this project.

The following packages are most definitely supposed to be used outside this project.
- `pkg/apis`
- `pkg/generated`
- `/pkg/controller/common/constants.go`
- `pkg/daemon/constants/constants.go`

while these can be used outside:
- `pkg/daemon/rpm-ostree.go`

**Comment by runcom** [comment]
cool, much better to have that picture now, thanks @abhinavdahiya

**Comment by runcom** [comment]
@abhinavdahiya though, what about `lib/`? is there something we can follow through vendor or does it need to stay forked for now?
