### ISSUE TITLE
Kubelet (and CRI-O) CRDs can be fooled by normal MCs

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#400]
If you create a machine config referencing the kubelet config (or the CRI-O once it lands) you're able to go around the existing CRD we have in place for the kubelet (and soon CRI-O).

The following MC causes at least `maxUnavailable` node(s) to go completely off (kube isn't reporting anymore).
```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: worker-add-file-0004
spec:
  config:
    ignition:
      version: 2.2.0
    storage:
      files:
      - contents:
          source: data:,test
        filesystem: root
        mode: 0644
        path: /etc/kubernetes/kubelet.conf
```

```
[core@ip-10-0-171-250 ~]$ systemctl status -l kubelet.service
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2019-02-11 14:36:39 UTC; 3s ago
  Process: 5028 ExecStart=/usr/bin/hyperkube kubelet --config=/etc/kubernetes/kubelet.conf --bootstrap-kubeconfig=/etc/kubernetes/kubeconfig --kubeconfig=/var/lib/kubelet/kubeconfig --container-runtime=remote --container-runtime-endpoint=/var/run/crio/crio.sock --allow-privileged --node-labels=node-role.kubernetes.io/worker --minimum-container-ttl-duration=6m0s --volume-plugin-dir=/etc/kubernetes/kubelet-plugins/volume/exec --client-ca-file=/etc/kubernetes/ca.crt --cloud-provider=aws --anonymous-auth=false (code=exited, status=255)
  Process: 5026 ExecStartPre=/bin/rm -f /var/lib/kubelet/cpu_manager_state (code=exited, status=0/SUCCESS)
  Process: 5023 ExecStartPre=/bin/mkdir --parents /etc/kubernetes/manifests (code=exited, status=0/SUCCESS)
 Main PID: 5028 (code=exited, status=255)

Feb 11 14:36:39 ip-10-0-171-250 systemd[1]: Failed to start Kubernetes Kubelet.
Feb 11 14:36:39 ip-10-0-171-250 systemd[1]: Unit kubelet.service entered failed state.
Feb 11 14:36:39 ip-10-0-171-250 systemd[1]: kubelet.service failed.
```

```
15:39:39 [github.com/openshift/machine-config-operator] ‹cvo-overrides› oc get nodes
NAME                                         STATUS                        ROLES    AGE   VERSION
ip-10-0-13-126.us-west-2.compute.internal    Ready                         master   53m   v1.12.4+9e35761882
ip-10-0-131-187.us-west-2.compute.internal   Ready                         worker   40m   v1.12.4+9e35761882
ip-10-0-149-200.us-west-2.compute.internal   Ready                         worker   40m   v1.12.4+9e35761882
ip-10-0-171-250.us-west-2.compute.internal   NotReady,SchedulingDisabled   worker   40m   v1.12.4+9e35761882
ip-10-0-22-191.us-west-2.compute.internal    Ready                         master   53m   v1.12.4+9e35761882
ip-10-0-47-163.us-west-2.compute.internal    Ready                         master   53m   v1.12.4+9e35761882
```

Ideally, either the kubelet/cri-o config controllers block or reconcile such a thing, or we explicitely blacklist CRD paths for stuff we expose through the CRDs to avoid people doing stupid stuff (of course, one might still be able to create an mc with a unit which rm the config or does weird stuff).

My point being, the entry points to configure the kubelet config and CRI-O are the CRDs so we better avoid people playing with those configs directly through MCs

@sjenning et all wdyt?

**Comment by jlebon** [comment]
Related: https://github.com/openshift/machine-config-operator/pull/330#discussion_r253114040. Thanks for bringing this up as a separate thread!

We definitely want to document this properly so users know about the CRD. Though do we want to actively block overriding it? Is there a use case for being able to override `kubelet.conf` at the MC level? The one I originally thought of was for overriding the config only for a specific pool, but looking closer at the docs now, it seems like the new spec does include [a pool selector](https://github.com/openshift/machine-config-operator/pull/330/files#diff-fdcb05045fc0d70ab72370e56d1a4084R69).

**Comment by runcom** [comment]
My reason for actively blocking it is because I don't really want to leave that port opened for admins to shoot themselves in the foot. I fear that even if we document it, leaving that provides a ui which is allowing you to do the same things in two ways. The way I see CRDs (and feel free to tell me I'm blind) is to provide a nice UI for important configuration (like kubelet and crio) that we want to _manage_. But if you can edit and replace them with a normal MC, again, we do have a UI which let's you do a "controlled" thing through the CRD and an "uncontrolled" thing via the MCs
