### ISSUE TITLE
operator should handle MCD sync gracefully

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#407]
We need to start doing testing of `oc adm upgrade` including a new MCO codebase.

Rolling out a new MCC may involve e.g. new configs being generated, which could start machine updates.  If the MCD on a node is involved in trying to do that sync, it's going to be disruptive to have it be replaced by the MCO updating the MCD daemonset.

Offhand...I think if we're operating on an existing cluster, the operator should pause until the pools are idle, then roll out the MCD first?

**Comment by runcom** [comment]
> Offhand...I think if we're operating on an existing cluster, the operator should pause until the pools are idle, then roll out the MCD first?

makes total sense

**Comment by runcom** [comment]
what I'm seeing on `oc adm upgrade` is that the _new_ operator is (ofc) the one being rolled out, do you mean we should pause the new operator until all _old_ pools are idle?

**Comment by cgwalters** [comment]
At the moment it's dangerous to kill the MCD unless it's idle.  We can and should harden things against that - there are small things we could do which would make it more reliable, but getting to "100% interruptable"...not easy.

Simplest thing I think is to enforce the property "if a pool is updating" then "ds/machine-config-daemon is complete".

> do you mean we should pause the new operator until all _old_ pools are idle?

So in this case yeah I think the new operator would come on and see the pools are active, and avoid rolling out the new MCD.

Maybe what we want is something like a `Paused` element in the controller config; the operator sets that when it detects it's upgrading, and the render controller would then stop generating new rendered MCs.  That way we ensure progress

Another thing we should do that would be complementary is for the daemon to catch the `SIGTERM` for pod termination and if it's actively working, ignore it.  And we can bump `terminationGracePeriodSeconds`.

**Comment by runcom** [comment]
can this be closed due to #477

**Comment by runcom** [comment]
as discussed during sync, we feel #477 cover pretty much this, closing, feel free to reopen if you feel otherwise
