### ISSUE TITLE
Wrap wait.* calls to expose the real error on failure

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#410]
Taken from https://github.com/openshift/machine-config-operator/pull/408#discussion_r255720389

There are other spots where we're not correctly reporting the error (i.e. https://github.com/openshift/machine-config-operator/blob/master/pkg/daemon/node.go#L55-L65)

On error, we should save the `lastErr` encountered + check for `wait.ErrWaitTimeout` in the `if err != nil` and report lastErr.

**Comment by jlebon** [comment]
> in the `if err != nil` and report lastErr

Ahh yep, that makes sense to me. (With the caveat that it might actually have been a different error on each retry, but even then, just percolating the last error seems like the right behaviour.)
