### ISSUE TITLE
Add e2e smoke tests for KubeletConfig and CRI-O CRDs

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#428]
Even if those are managed by other teams, it would be nice to have some e2e coverage for them. Smoke tests would suffice (as well as some regression tests like https://github.com/openshift/machine-config-operator/pull/424#issuecomment-463383904)

**Comment by kikisdeliveryservice** [comment]
Since this was opened we have https://github.com/openshift/machine-config-operator/blob/master/test/e2e/ctrcfg_test.go
