### ISSUE TITLE
Pod sandboxes do not use payload specified image

### ISSUE THREAD

**Issue by sjenning** [openshift/machine-config-operator#455]
https://github.com/openshift/machine-config-operator/blob/master/templates/master/01-master-container-runtime/_base/files/crio.yaml#L206

https://github.com/openshift/machine-config-operator/blob/master/templates/worker/01-worker-container-runtime/_base/files/crio.yaml#L206

Should use the `pod` image from the release payload.

There is some plumbing to do here as that image pull spec is not provided to the MCO currently.

@smarterclayton @umohnani8 @mrunalp @runcom @rphillips

**Comment by sdodson** [comment]
/cc @vrutkovs @mtnbikenc 
We'll want to track this change so we're ideally setting the correct pause image during BYO.

**Comment by cgwalters** [comment]
:thinking: Why are we still doing the pause image thing with cri-o? It always seemed silly...plus if we do need to do it we can pick another image to use for this right?

**Comment by sjenning** [comment]
It holds open the pod-level namespaces, namely the network namespace.

This is so the namespaces can be initialized before the application starts (assign IPs and whatnot), and maintained if the application container(s) die and need to be restarted.

**Comment by vrutkovs** [comment]
In RHEL scaleup we use default CRIO config and change `pause_image` and `pause_command` - https://github.com/openshift/openshift-ansible/pull/11203/files#diff-8696e419a88c9744f085bc0a531bc511R49

**Comment by mrunalp** [comment]
Also, since k8s added support for sharing pid namespaces, we can't get rid of the infra(pause) container as it is expected to be pid 1 for the pod.

**Comment by umohnani8** [comment]
@sjenning is the `pod` image coming from docker.io or quay.io?

**Comment by runcom** [comment]
> Should use the `pod` image from the release payload.

what's the name of that image that I can query with `releasepayloadimage image {pod}`?

> 
> There is some plumbing to do here as that image pull spec is not provided to the MCO currently.

this has to go through https://github.com/openshift/installer/blob/master/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template#L155 right?

**Comment by cgwalters** [comment]
https://github.com/openshift/machine-config-operator/pull/343 is a good prior change for "get an image from the release payload into configs".
