### ISSUE TITLE
rekick an MCD sync after a failure

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#478]
If e.g. pivot fails, do we have/want a way to rekick the whole process? right now we seem to be going Degraded and live with that. QE raised an interesting question though: is my cluster just busted then if everything is degraded? how do we get back to a working state manually if possible?

Not something we can fix right away, but worth documenting _if_ there's a way today (like killing the MCD?)

**Comment by cgwalters** [comment]
https://github.com/openshift/machine-config-operator/issues/254#issuecomment-455179843

**Comment by runcom** [comment]
> #254 (comment)

omg, thanks Colin :heart:

**Comment by cgwalters** [comment]
Can we close this issue as a dup of #254 ?
