### ISSUE TITLE
MC* should use Ignition's validation logic to validate Ignition types

### ISSUE THREAD

**Issue by ajeddeloh** [openshift/machine-config-operator#479]
**Description**

MCO/MCD can currently use MCs that contain Ignition types that are invalid according to Ignition. It should check that the configs are valid using [Ignition's validation logic](https://github.com/coreos/ignition/blob/spec2x/config/validate/validate.go#L108).

**Steps to reproduce the issue:**
1. Create a machine config that should be invalid (e.g. use a relative path for a file)
2. Have that work instead of failing

**Describe the results you received:**
MCD applied the change

**Describe the results you expected:**
MCO/D/something should fail when presented with an invalid config

cc @kikisdeliveryservice since I was talking about this with her
cc @abhinavdahiya since he had some ideas on using admission plugins for this

**Comment by kikisdeliveryservice** [comment]
I can confirm through testing on my cluster that I am able to create and apply a machineconfig with what should be invalid ignition config fields.
For example, I am able to write a file to a relative path `home/whatever` and a mc is generated and applied successfully without error via the MCD.

**Comment by runcom** [comment]
I would add that we don't need to Degrade in such a case, just (sort of) rejecting the MC if possible

**Comment by ajeddeloh** [comment]
Ideally whatever is generating it should fail instead of whatever is consuming it. Invalid MCs should probably be disallowed everywhere if that's possible

**Comment by kikisdeliveryservice** [comment]
as per convo with @runcom We'll have to go Degraded on bad MCs for now and then iterate once the Unreconcilable epic is done switch to that.

**Comment by kikisdeliveryservice** [comment]
Started on this, will pick it up on Monday.

**Comment by runcom** [comment]
just noticed that we're not setting the ignition version to:

- SSH MCs (00-*-ssh)
- registries MCs (99-*-registries)

we should be doing that afaict.
