### ISSUE TITLE
upgrade control plane before compute

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#480]
We need to upgrade masters before workers when doing OS updates.

This is a messy topic because so far we've intentionally conflated "config change" and "OS update".  Maybe simplest is to just have the node controller just prioritize `master` (or we add a generic `priority` integer or something).  But basically I think simplest is to do this in the node controller.

Another approach would be for the operator to control the pools - set an equivalent of the `Paused` field (we wouldn't want to acutally use `Paused` since that's for admins to use).

**Comment by runcom** [comment]
thanks for filing this out Colin
