### ISSUE TITLE
daemon: Don't reboot for noops

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#485]
Now that https://github.com/openshift/machine-config-operator/pull/463 landed I was playing with an upgrade; it seems to work fine:

```
I0224 13:47:46.173163    4861 daemon.go:504] Current config: worker-42c66cf3b4a40d2c37ce17bc7c4a62b7
I0224 13:47:46.173196    4861 daemon.go:505] Desired config: worker-76dc89e185d472746c1da5c1277ac2e9
I0224 13:47:46.173441    4861 daemon.go:897] Current and target osImageURL have matching digest sha256:660061d6eae3ee6d93ca836cd52e6033f1d611c629c1ce47cf272c9e9bda2488
```

Cool.  But...we still reboot the cluster in the middle of the upgrade for...I'm pretty sure a no-op. 

Eventually of course we should support live updates.  But for now, maybe do the "matching digest" bit when reconciling and detect if there are no other changes?

**Comment by runcom** [comment]
Yeah, I'd go with detecting if there are no changes during reconciling

**Comment by cgwalters** [comment]
This is obsolete.
