### ISSUE TITLE
errors strings must start with lowercase

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#501]
As a general rule as the guideline says: https://github.com/golang/go/wiki/CodeReviewComments#error-strings

Let's keep this open till most of the code is polished and we'll be more strict when reviewing PRs.
Keep it open as a tracker for PRs that are cleaning the current code.

Ref: https://github.com/openshift/machine-config-operator/pull/481#discussion_r260157691

**Comment by kikisdeliveryservice** [comment]
I will make the changes in update.go!

**Comment by kikisdeliveryservice** [comment]
Opened PR #539 that updates the mcd gofiles: daemon.go, node.go, osrelease.go, rpm-ostree.go, update.go, writer.go

**Comment by kikisdeliveryservice** [comment]
Closing as the rest of the errors were updated in #2868
