### ISSUE TITLE
MCC should have MCs Ignition validation

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#502]
Taken from: https://github.com/openshift/machine-config-operator/pull/481#issuecomment-467579138

We should add ignition validation to the MCC as well (it's gonna be in MCD via #481 )

**Comment by kikisdeliveryservice** [comment]
On it!

**Comment by kikisdeliveryservice** [comment]
Ok, so for this, I'm going to do #498 first otherwise, those will fail ignition validation that I add in the MCC bc they don't have a version..
