### ISSUE TITLE
investigate high CPU usage

### ISSUE THREAD

**Issue by miabbott** [openshift/machine-config-operator#519]
@smarterclayton says:

> MCO is the third highest CPU namespace right now - using about a tenth of a core on an unloaded cluster on average.  that’s ok, but should be lower (that’s higher than SDN).  can someone take the todo to do a quick look at where the CPU is coming from and what is the cause (writes, busy loops, checking too much, etc)?

**Comment by kikisdeliveryservice** [comment]
Some more information:
in general most healthy operators at steady state on unloaded clusters should be 10millicore, and operators that have per node agents can budget 5-10millicore per node

**Comment by kikisdeliveryservice** [comment]
```
Element    Value
namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{container_name="machine-config-server",namespace="openshift-machine-config-operator",pod_name="machine-config-server-cmgjq"}    0.02591943592962962
namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{container_name="machine-config-server",namespace="openshift-machine-config-operator",pod_name="machine-config-server-b8tf7"}    0.024595734537037065
namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{container_name="machine-config-server",namespace="openshift-machine-config-operator",pod_name="machine-config-server-gmd8d"}    0.02412587116296297
namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{container_name="machine-config-controller",namespace="openshift-machine-config-operator",pod_name="machine-config-controller-7d5744464-zws45"}    0.007748433951851876
namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{container_name="machine-config-operator",namespace="openshift-machine-config-operator",pod_name="machine-config-operator-5bf44bf567-rt2hc"}    0.006262270633333337
namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{container_name="machine-config-daemon",namespace="openshift-machine-config-operator",pod_name="machine-config-daemon-gmtld"}    0.0023182287481481514
namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{container_name="machine-config-daemon",namespace="openshift-machine-config-operator",pod_name="machine-config-daemon-5gl8s"}    0.0021795583518518552
namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{container_name="machine-config-daemon",namespace="openshift-machine-config-operator",pod_name="machine-config-daemon-pph69"}    0.002175958748148148
namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{container_name="machine-config-daemon",namespace="openshift-machine-config-operator",pod_name="machine-config-daemon-h7rg6"}    0.001971203488888886
namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{container_name="machine-config-daemon",namespace="openshift-machine-config-operator",pod_name="machine-config-daemon-b8vc4"}    0.0016234032148148135
namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{container_name="machine-config-daemon",namespace="openshift-machine-config-operator",pod_name="machine-config-daemon-wngl6"}    0.0014885247296296286
```

**Comment by cgwalters** [comment]
I suspect the CPU usage from the MCS pods is related to the ELB health checks (/healthz) as defined by the installer.   Looks like the interval there is every 10 seconds.

**Comment by runcom** [comment]
yaeh that makes sense, not sure we want the check to be less frequent or something else. The MCS is super simple web server which I cannot find any way to make it leaner (/cc @wking @smarterclayton )

**Comment by wking** [comment]
> I  suspect the CPU usage from the MCS pods is related to the ELB health  checks (/healthz) as defined by the installer.   Looks like the interval  there is every 10 seconds.

Where is the measured 10-second interval coming from?  Logs for a random, recent run are not enlightening:

```console
$ curl -s https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.0/5634/artifacts/e2e-aws/pods/openshift-machine-config-operator_machine-config-server-28jd4_machine-config-server.log.gz | gunzip
I0313 20:50:10.448871       1 start.go:37] Version: 4.0.0-alpha.0-28-g9e6d0a4b-dirty
I0313 20:50:10.450349       1 api.go:51] launching server
I0313 20:50:10.450427       1 api.go:51] launching server
```

How would folks feel about using something like [lestrrat-go/apache-logformat](https://github.com/lestrrat-go/apache-logformat) to wrap our handler?

**Comment by cgwalters** [comment]
> Where is the measured 10-second interval coming from?

https://github.com/openshift/installer/blob/4b12088025778add89e95099eaeebb773c39436d/data/data/aws/vpc/master-elb.tf#L90

right?

**Comment by wking** [comment]
> > Where is the measured 10-second interval coming from?
>
> https://github.com/openshift/installer/blob/4b12088025778add89e95099eaeebb773c39436d/data/data/aws/vpc/master-elb.tf#L90
>
> right?

I meant "how did we decide it was the health checks that were causing the high CPU usage?".  We could adjust the health-check interval, but serving those responses is just "[hand back a 204][1]".  I don't see that costing many cycles, and if somehow it *is* terribly expensive, it makes me very concerned about how well the MCS will handle for its real job of serving Ignition configs.

[1]: https://github.com/openshift/machine-config-operator/commit/d0a7ae21b0e4d3174fd5ec41288204d4b0292019#diff-4bbf1ce644e1b41f1ed61ab858def528R137

**Comment by cgwalters** [comment]
> I meant "how did we decide it was the health checks that were causing the high CPU usage?".

I didn't look, just a theory.
