### ISSUE TITLE
potential backport on okd 4.0 assuming  K8s 1.12 is being targeted

### ISSUE THREAD

**Issue by DanyC97** [openshift/machine-config-operator#520]
you might already be aware of the issue, however in case you haven't i thought i should just give you a heads up.

Assuming you targeting 4.0 with 1.12 (as per latest openshift blog published by @crawford ) you should be aware of [this](https://github.com/kubernetes/kubernetes/issues/74412#issuecomment-468437599) issue which is forcing a golang version bump before 1.14 gets into freeze move

There is also a workaround which i think you can take it in your kubelet config - https://github.com/kubernetes/kubernetes/pull/74755

/cc @wking @smarterclayton 

_please close this issue once you ack, i couldn't find a better way to notify the right group_

**Comment by crawford** [comment]
Thanks for the heads-up! I'm going to let @runcom close this to make sure he sees it.

**Comment by runcom** [comment]
is there anything we (mco) should do here? (I'm probably missing something obvious) Is this an heads up that we're just going to upgrade golang and make sure everything still works fine here?

**Comment by RobertKrawitz** [comment]
For now we're going to simply cherrypick the point fix, revert the use of the watch-based monitoring strategy in favor of the previous caching code that doesn't have this problem (I have a cherrypick PR waiting to go as soon as https://github.com/kubernetes/kubernetes/pull/74842 merges).  @rphillips and I were discussing whether the MCO should block any attempt by the user to change the default; that's what issue is about.

**Comment by rphillips** [comment]
I added a PR to prevent the KubeletConfiguration variable being changed by the user.

**Comment by runcom** [comment]
Awesome, thanks for the clarification

**Comment by kikisdeliveryservice** [comment]
Since this has been addressed, closing.
