### ISSUE TITLE
Host trusted CA certs

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#528]
EDIT: See https://github.com/openshift/machine-config-operator/issues/528#issuecomment-511452454

---

I'd like to be able to configure my hosts to trust a CA internal to my company, so I can pull container images from there.

Note that while Ignition has a `security.certificateAuthorities` it in fact [only applies to Ignition fetching configs](https://github.com/coreos/ignition/pull/636) which isn't relevant for us.

Something like a `trustedCertificateAuthorities` section in `MachineConfig`, and the MCD drops them in `/etc/pki/ca/trust/source/anchors` and runs `update-ca-trust`?

**Comment by runcom** [comment]
if this is for pulling container images we've done that already and demoed it ~2months ago at least. Basically we lay down registries certificates in the cri-o location where it's gonna look and trust them on pull.

@mrunalp do you remember ^^ (I'm currently afk so can't check it but I remember doing that demo 😄 )

**Comment by runcom** [comment]
ok found it, here's the asciinema https://asciinema.org/a/221479 - we might want to convert that to official doc but not on us I guess

**Comment by mrunalp** [comment]
We will follow with Chris Negus on the docs.

**Comment by kikisdeliveryservice** [comment]
Thanks @mrunalp !

**Comment by runcom** [comment]
closing this, no code/doc should land here

**Comment by cgwalters** [comment]
Trusting a registry isn't the same thing as installing a host-global CA cert.

**Comment by cgwalters** [comment]
In case anyone is curious, the referenced operator is https://github.com/openshift/cluster-image-registry-operator/#image-registry-certificates-configmap

In practice actually, that operator won't help with what I want since we're pulling direct via `podman` to the host, we aren't doing a pull-through to the internal registry.

**Comment by runcom** [comment]
Laying down certificates in that way I demoed works for Podman as well as containers/image is still the pull driver. I'm not sure what the use case is here. If it's for pulling images, whether Podman or the Openshift builder or whatever including docker, the method above works just fine afaict.

**Comment by wking** [comment]
> I'm not sure what the use case is here. If it's for pulling images...

That's my use case (discussion in openshift/installer#472).  Docs would be great :).

**Comment by cgwalters** [comment]
See also https://github.com/containers/libpod/issues/2317

**Comment by cgwalters** [comment]
If anyone wants to do this today, you'd need to create a MachineConfig object that drops certificates in the usual Fedora/RHEL location: `/etc/pki/ca-trust/source/anchors/`.

Then you also need to a systemd unit in your Ignition that runs `update-ca-trust` at boot time, you want it to be `Before=kubelet.service` etc.

**Comment by cgwalters** [comment]
Per discussion with Abhinav and Mrunal, I will write a patch to add `coreos-update-ca-certs.service` that runs on early boot; requiring users to do that invites race conditions and other issues.

**Comment by runcom** [comment]
> Per discussion with Abhinav and Mrunal, I will write a patch to add `coreos-update-ca-certs.service` that runs on early boot; requiring users to do that invites race conditions and other issues.

has this came from the latest proxy requirements about ca for proxy?

**Comment by cgwalters** [comment]
> has this came from the latest proxy requirements about ca for proxy?

Yep.

**Comment by cgwalters** [comment]
Depends https://github.com/coreos/fedora-coreos-config/pull/120

**Comment by cgwalters** [comment]
In the current 4.2 development stream we landed code similar to https://github.com/coreos/fedora-coreos-config/pull/120 in RHCOS, so it should be sufficient to supply the certificates to Ignition.

**Comment by dustymabe** [comment]
> In the current 4.2 development stream we landed code similar to [coreos/fedora-coreos-config#120](https://github.com/coreos/fedora-coreos-config/pull/120) in RHCOS, so it should be sufficient to supply the certificates to Ignition.

Reading back through this ticket it looks like the above *at-least* handles the *at install time* case. Does it also cover the *day 2 via the MCO case* or is that still outstanding work to be addressed before this issue is closed?

**Comment by cgwalters** [comment]
> Does it also cover the day 2 via the MCO case

It does, yes.

**Comment by dustymabe** [comment]
Should this issue be closed?

**Comment by cgwalters** [comment]
See also https://github.com/openshift/enhancements/pull/115/#issuecomment-580966164
