### ISSUE TITLE
Fix dependency on chroot

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#543]
Today the way the MCD `chroot` into the host creates all sort of problems.  I believe this was done for a few reasons:

 - We can speak DBus to e.g. systemd/rpm-ostree
 - When processing Ignition we don't have to deal with the rootfs prefix

And over time we've had to add hacks like https://github.com/openshift/machine-config-operator/pull/370 to pick up things from the Kube side.

Dealing with DBus is easy, we can just bind mount `/run/dbus/system-bus-socket` into our code.

The filesystem bits are hard mainly because of symlinks.  See e.g. [AT_NO_JUMPS patches](https://marc.info/?l=linux-api&m=155215087916280&w=2) and [rpm-ostree os-release change](https://github.com/projectatomic/rpm-ostree/commit/e94f8c9b5f8e327c792156d6f154aedcba96ef16).

I think for the filesystem stuff...basically we need to split the MCD into two containers (in the same pod); the "kube mcd" and the "host mgmt MCD".  Only the latter "hostmgmt" MCD would be chrooted.  

Or...actually perhaps even easier, have a single MCD that execs the child process chrooted.  The child process gets passed the Ignition configs as temporary files.

In fact it's *almost* like we exec in once-from mode.

**Comment by cgwalters** [comment]
One thing that might actually help us a lot architecturally too is to also have the "once-from" code (basically Ignition handling) also be built into an RPM that goes into the host.  And then when we want to run it rather than using `chroot` we actually `systemd-run` it just like we do for rpm-ostree.

**Comment by ashcrow** [comment]
:+1: to https://github.com/projectatomic/rpm-ostree/commit/e94f8c9b5f8e327c792156d6f154aedcba96ef16 ... though we will need to build that package and get it into composes for it to be used.

> Or...actually perhaps even easier, have a single MCD that execs the child process chrooted. The child process gets passed the Ignition configs as temporary files.
> In fact it's almost like we exec in once-from mode.

I like this path.

**Comment by cgwalters** [comment]
I just did https://github.com/openshift/machine-config-operator/pull/545
which I think simplifies the code and will help avoid the immediate crasher.

Basically, while I think going down the exec path is a good idea it's fairly risky/involved at the moment.
Dropping our dependency on everything using cgo should get us unblocked.

**Comment by jlebon** [comment]
Previous discussions on this subject in #45. Definitely agree overall we should only be chroot'ing for the parts we really have to.

> I just did #545
which I think simplifies the code and will help avoid the immediate crasher

What's the crasher BTW?

**Comment by cgwalters** [comment]
> What's the crasher BTW?

```
0311 21:46:03.865051    2971 daemon.go:446] Fatal error checking initial state of node: Checking initial state: error detecting early SSH accesses: unable to open a handle to the library
```

**Comment by cgwalters** [comment]
Leaving this issue open; https://github.com/openshift/machine-config-operator/pull/545 merged which solves our immediate problem, but we should still do this at some point to avoid hacks like https://github.com/openshift/machine-config-operator/pull/370
