### ISSUE TITLE
increase frequency of pool -> operator status reporting

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#550]
https://github.com/openshift/origin/pull/22302#issuecomment-472694227

From Derek:

master-e2e-aws-upgrade/14/build-log.txt

looking at https://github.com/openshift/machine-config-operator/blob/f97747550f42821725f2853b211cc48d4c0df42e/pkg/operator/sync.go#L320

i see on every operator sync, we drop into that function and wait 10m for the sync of all pools to complete.

is it possible to 1) report what machine is unavailable to aid debugging, 2) get feedback on cluster operator object at a frequency better than 10m chunks of time? if we dropped the polling altogether in that function, would we just get updated data on the operator next sync loop iteration? its not clear what benefit the 10m poll provides, but maybe its a limitation of current structure?

**Comment by runcom** [comment]
my reply is here https://github.com/openshift/origin/pull/22302#issuecomment-472868298

**Comment by runcom** [comment]
Increased frequency of poll (by removing the polling altogher, now we just act as a controller), also added logs about unavailable nodes for inspection/debugging
