### ISSUE TITLE
e2e: TestMCDeployed taking 80% of e2e test time

### ISSUE THREAD

**Issue by kikisdeliveryservice** [openshift/machine-config-operator#567]
TestMCDeployed is currently taking ~40 minutes to run. 
Our test limit is 50m: `GOCACHE=off go test -timeout 50m -v${WHAT:+ -run="$WHAT"} ./test/e2e/`

As it stands the current e2e tests take ~41 minutes.  When I try to run my new test https://github.com/openshift/machine-config-operator/pull/541 it times out after 9 minutes because we have hit the total test time of 50.

Relevant logs from https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/541/pull-ci-openshift-machine-config-operator-master-e2e-aws-op/1211/  
```
GOCACHE=off go test -timeout 50m -v${WHAT:+ -run="$WHAT"} ./test/e2e/
=== RUN   TestMCDToken
--- PASS: TestMCDToken (0.45s)
=== RUN   TestMCDeployed
--- PASS: TestMCDeployed (2418.86s)
=== RUN   TestUpdateSSH
panic: test timed out after 50m0s

goroutine 2196 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1240 +0xfc
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x44

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc42036e0f0, 0x1068b0d, 0xd, 0x10eb6c0, 0x48a201)
	/usr/local/go/src/testing/testing.go:825 +0x301
testing.runTests.func1(0xc42036e000)
	/usr/local/go/src/testing/testing.go:1063 +0x64
testing.tRunner(0xc42036e000, 0xc42017fdd8)
	/usr/local/go/src/testing/testing.go:777 +0xd0
testing.runTests(0xc4202de660, 0x1857080, 0x7, 0x7, 0x1)
	/usr/local/go/src/testing/testing.go:1061 +0x2c4
testing.(*M).Run(0xc420341380, 0x0)
	/usr/local/go/src/testing/testing.go:978 +0x171
github.com/openshift/machine-config-operator/test/e2e_test.TestMain(0xc420341380)
	/go/src/github.com/openshift/machine-config-operator/test/e2e/main_test.go:9 +0x2b
main.main()
	_testmain.go:52 +0x151
```
I think we will have to raise our test time or test less mcs in TestMCDeployed (which is currently testing 10?) otherwise we will keep running into this as we add e2e. Not sure how long this can reasonably take? Perhaps MCDeployed should be in its own test package and optional?

cc: @runcom

**Comment by runcom** [comment]
That test is critical to make sure the basic functionality works. I'm fine raising the test time to at least 1h and a half

**Comment by kikisdeliveryservice** [comment]
Ok, I'll let you know.

**Comment by kikisdeliveryservice** [comment]
I believe that #563 fixed this problem.  All of the e2e-aws-op tests were able to run with no timeouts!

Closing this issue.
