### ISSUE TITLE
Add new node.openshift.io/rhelmajor=7|8 label

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#582]
https://github.com/openshift/machine-config-operator/pull/514 added the OS version but it isn't usable as a selector for e.g. daemonsets that just care about RHEL major (e.g. iptables vs nftables).

Let's add a new label and implement it for both RHCOS and BYO RHEL.

Proposal is: `node.openshift.io/rhelmajor=7|8`.

**Comment by ashcrow** [comment]
`node.openshift.io/rhelmajor=7|8` makes sense to me.

**Comment by ashcrow** [comment]
The RHCOS `VERSION` or `VERSION_ID` can be parsed to set this like so: `echo $VERSION | cut -d . -f 2`

**Comment by sjenning** [comment]
fyi @rphillips

**Comment by chambridge** [comment]
We wish to use this as part of our metrics information that will be utilized for subscription entitlement reconciliation. The sooner we have this information the better.

**Comment by sdodson** [comment]
> We wish to use this as part of our metrics information that will be utilized for subscription entitlement reconciliation. The sooner we have this information the better.

Do you also have a use for differentiating between RHEL and RHCOS for those same purposes?

**Comment by chambridge** [comment]
We are currently using the label `node.openshift.io/os_id` which shows up on `kube_node_labels` as `label_node_openshift_io_os_id` to differentiate between RHEL and RHCOS.

**Comment by adelton** [comment]
Wouldn't using something like `PLATFORM_ID="platform:el8"` directly from `/etc/os-release` be a reasonable value and distinguisher? So something like `node.openshift.io/platform=platform:el8`?

**Comment by adelton** [comment]
Or is it important for the value to be a single integer value?

**Comment by ashcrow** [comment]
In the latest devel builds I do see a new key in `/etc/os-release` called `RHEL_VERSION` that @cgwalters has kindly added.

**Comment by cgwalters** [comment]
> Wouldn't using something like PLATFORM_ID="platform:el8" directly from /etc/os-release be a reasonable value and distinguisher? 

That doesn't seem to exist in RHEL7.  It's some modularity invention right?  Are you aware of any docs for what it means?  Doesn't seem to be more useful than just `VERSION_ID`  to me?

**Comment by adelton** [comment]
You are right, `PLATFORM_ID` does not seem documented at https://www.freedesktop.org/software/systemd/man/os-release.html.

**Comment by adelton** [comment]
> In the latest devel builds I do see a new key in `/etc/os-release` called `RHEL_VERSION` that @cgwalters has kindly added.

Devel builds of which product are these? On RHEL 8.1, redhat-release-8.1-3.3.el8.x86_64 does not seem to have `RHEL_VERSION`, and neither I see id on CoreOS 42.80.20191010.0 with redhat-release-coreos-420.8-3.el8.x86_64.

**Comment by cgwalters** [comment]
> Devel builds of which product are these? 

RHCOS 43.81 with `redhat-release-coreos`.  

I don't think we need `RHEL_VERSION` in `redhat-release` beacuse the `VERSION_ID` is the same thing.  RHCOS though is a fusion of RHEL and OpenShift versions.

**Comment by adelton** [comment]
Ah, I see.
So I guess the question is, do we hope to get the major RHEL version computed on the OS level, perhaps as part of the `kubelet.service` definition, so that the `--node-labels=node.openshift.io/rhelmajor=(7|8)` is passed in with that single-digit value, or are we OK with passing in both the `VERSION` and `RHEL_VERSION` values and computing the value in the .go code?
