### ISSUE TITLE
Don't re-download release image

### ISSUE THREAD

**Issue by mhrivnak** [openshift/machine-config-operator#585]
As I understand it, the release image will be downloaded by each individual node when it is time to upgrade that node. The redundant downloading may have little impact in a public cloud environment, where the image is likely being downloaded from inside the cloud environment. On-prem clusters downloading over the internet will feel a greater impact from downloading the same image many times.

It would be valuable to download the image only once into the cluster and re-use it for each node upgrade.

Eventually it will be useful to provide a release image to a disconnected cluster. I'd consider that a separate RFE. But it might be a useful direction to keep in mind, in case this RFE can be implemented in a way that could be extended to a bring-your-own-release-image workflow.

**Comment by runcom** [comment]
mmm the machine-config-operator isn't playing with the release image, maybe this is intended for another repo or bugzilla?

**Comment by mhrivnak** [comment]
This RFE is following up on this thread: https://github.com/openshift/machine-config-operator/pull/561#discussion_r267107240

Maybe I'm using the wrong term?

**Comment by runcom** [comment]
:man-shrugging: it's ok then, even if I think it's an infra issue rather than a MCO only one

**Comment by mhrivnak** [comment]
@cgwalters WDYT? Anything I can do to improve this issue?

**Comment by cgwalters** [comment]
I don't see why the answer to this is any different than the other containers.  (Barring of course the current fact that `machine-os-content` is one of the larger ones)

There are a whole lot of ways to address this.  First is `oc adm release mirror`, although AIUI today the problem with that is it changes the checksums which breaks higher level things like Cincinnati.

It certainly seems to me that something could live at the CRI-O layer or below that e.g. was able to pull images via sha256 from other nodes that have it already.  Or relatedly, have the internal registry do pull-through.  I know there's various experiments with this type of stuff (e.g. containers/image + bittorrent), don't know how far away it is from being shippable.

**Comment by runcom** [comment]
> It certainly seems to me that something could live at the CRI-O layer or below that e.g. was able to pull images via sha256 from other nodes that have it already. Or relatedly, have the internal registry do pull-through. I know there's various experiments with this type of stuff (e.g. containers/image + bittorrent), don't know how far away it is from being shippable.

right, that's why I thought this issue doesn't belong specifically to MCO. I remember discussions in CRI-O around distributed file sharing (torrent) and pull-through mechanism to achieve what this PR is aiming for.

**Comment by cgwalters** [comment]
> right, that's why I thought this issue doesn't belong specifically to MCO.

Yeah, I don't know where else we'd file it though right now.

Thinking about this more there is one other special thing about `machine-os-content` - it's pulled directly by `podman` during early pivot, not kubelet/cri-o.  Which means any automatic caching would have to work very early on.

A model that might make a lot of sense is for the bootstrap node to pull the image and seed it to the masters, which then help seed it to workers.

**Comment by smarterclayton** [comment]
Maybe, but if we do that we need to fit it into the larger story around content.  I don't want to short circuit with an install hack, I want this to be the unified solution.

**Comment by wking** [comment]
Landed a few hours ago, and will probably help with both Podman and CRI-O cases once they pick it up: containers/image#564  But for initial bootstrapping, my preferred approach is still cutting frequent bootimages so folk on important releases don't need an early pivot.

**Comment by cgwalters** [comment]
> But for initial bootstrapping, my preferred approach is still cutting frequent bootimages so folk on important releases don't need an early pivot.

We've covered this topic a lot and I'm too lazy to find earlier messages but:

Ultimately, it's reality that not all install scenarios are going to support reliably having bootimages that are the exact version we want.  Think VMWare, bare metal etc.  For OpenStack today AFAICS we just ask the user to manage uploading images into Glance manually and provide that to the install config.

Since we can't do it everywhere we might as well consistently pivot.  Note that at least if we *do* use the right bootimage we won't pivot, so the groundwork is laid there.

**Comment by wking** [comment]
> Since we can't do it everywhere we might as well consistently pivot. Note that at least if we do use the right bootimage we won't pivot, so the groundwork is laid there.

Right.  So we could resolve [rhbz#1702519][1] for the intall-time rush by building bootimages for that RHCOS, bumping the installer pins, and cutting rc.1.  Doesn't mean we shouldn't also work on reliable pivots, but I don't see a need to avoid useful tools that we already put in our toolbox ;).

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1702519

**Comment by cgwalters** [comment]
https://github.com/openshift/machine-config-operator/pull/805
will be an important part of implementing this.
