### ISSUE TITLE
operator doesn't watch cm/machine-config-osimageurl

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#606]
I remember wrestling with this earlier...today it doesn't work to

```
$ oc scale --replicas=0 -n openshift-cluster-version deploy/cluster-version-operator
$ oc edit cm/machine-config-osimageurl
<change osimageurl>
```

Since the operator doesn't watch it I think; you have to "bounce" the operator (e.g. `oc delete -l k8s-app=machine-config-operator pods` and wait for it to come back).

Hmm and actually that got me a new `controllerconfig` but the MCC didn't react to that either, had to bounce it too.

I think we had a kind of assumption that `machine-os-content` would always be updated alongside the MCO.  There was an issue I think around this.

**Comment by runcom** [comment]
so do we want the operator/controller to watch that cm and resync when it changes?

**Comment by runcom** [comment]
> I think we had a kind of assumption that `machine-os-content` would always be updated alongside the MCO.

I guess a simple test would be to create a payload which just overrides the machine-os-content and see how it goes? (should do nothing actually right?, then yeah, we need to fix it)

**Comment by runcom** [comment]
```
	cmInformer.Informer().AddEventHandler(optr.eventHandler())
```


Operator should resync on config map changes 🤔

**Comment by runcom** [comment]
I also don't understand why we watch every config map change in the whole cluster to trigger our operator resync :/

**Comment by runcom** [comment]
Update: scaling the CVO, updating the cm for osimageurl just worked for me, I can see the new CC with my dummy value for osimageurl

**Comment by runcom** [comment]
The MCC also reacted just fine for the new CC:
```
...

[Install]
WantedBy=multi-user.target

        Enabled:  true
        Name:     kubelet.service
  Os Image URL:   dummy
Events:           <none>
````
