### ISSUE TITLE
Kubelet and ContainerRuntime controllers not reacting to ControllerConfig changs

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#630]
Both controllers are using the ControllerConfig to render their templates but they're not re-triggering a sync if the ControllerConfig changes. That can result in MachineConfigs for these controllers to use old values from ControllerConfig in their templates. I believe they should have an event handler to re-sync on ControllerConfig changes (like the TemplateController or something along that path)

**Comment by runcom** [comment]
also kube and container controllers aren't reacting to ControllerConfig changes..

**Comment by runcom** [comment]
Slightly modified this issue after testing... @mrunalp @umohnani8 @sjenning @rphillips ptal

**Comment by umohnani8** [comment]
on it!

**Comment by bparees** [comment]
is this being tracked in a BZ?

**Comment by runcom** [comment]
nope, I haven't fully validated this, looks like the ControllerConfig isn't something users should play with at all

**Comment by umohnani8** [comment]
@runcom so the controllers don't need to watch the controllerConfig for any changes then?

**Comment by umohnani8** [comment]
@runcom is this still an issue? Anything I need to fix in containerRuntimeConfigController?

**Comment by runcom** [comment]
@umohnani8 nope, nothing to change now but I'll revisit this later in the future
