### ISSUE TITLE
Optimize reboots

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#650]
~~With #632 we can now just edit the pull secret and roll out the pull secret to all nodes. That isn't optimal as it requires a reboot of all the nodes for just a file replace. Similar to kargs and others, I was wondering if we can plug a new CRD (or MC extension somehow) where we can add context and understand that only the PullSecret changed and we don't need to reboot a N nodes cluster. There's probably some research to be done as secrets are, well, secrets so it might not be that straightforward as we need to be careful not to expose them.~~

When we'll tackle the "avoid reboot when not needed" we need to take into account someone changing only the PullSecret. it doesn't require a reboot so maybe $(diff $oldps $newps) would tell us if it changed and if no other thing changed, we may avoid a reboot.

**Comment by runcom** [comment]
This isn't a real thing tho,  we might be able to skip a reboot by inspecting the rendered machineconfig and see if pull-secret actually changed with kube api to decide on reboot (and other stuff)

**Comment by cgwalters** [comment]
Repurposing this issue for adding the infrastructure to avoid reboots.  The pull secret is one example.

**Comment by mrguitar** [comment]
It's almost easier to flag what requires a reboot rather than the opposite: OS updates & kargs are the two big ones off the top of my head. I suspect there are more.

Most changes involving adding files & dir don't require a reboot, however, some will need a service restart to take effect. 

Reboots need to be restricted heavily when using Ceph and replicas and state become an issue, and also for CNV/kubevirt workloads.

**Comment by runcom** [comment]
> It's almost easier to flag what requires a reboot rather than the opposite: OS updates & kargs are the two big ones off the top of my head. I suspect there are more.

this isn't as easy as it sounds this way though, we can just let users toggle a knob. We need to be the ones _deriving_ when a reboot is needed anyway. Otherwise, it gets pretty messy.

> Reboots need to be restricted heavily when using Ceph and replicas and state become an issue, and also for CNV/kubevirt workloads.

We need to understand more from the above and understand how we can derive those also.

**Comment by e-minguez** [comment]
It would be nice to have a proper way to disable reboot temporary. The use case is you just deployed your baremetal cluster and you want to customize a few things (such as NTP, modify registries, etc.) and avoid a reboot per modification (specially for baremetal where it can take a few minutes to reboot the hosts)

**Comment by cgwalters** [comment]
You can do this today, just set the `paused` field in the `machineconfigpool` objects to true.

**Comment by e-minguez** [comment]
> You can do this today, just set the `paused` field in the `machineconfigpool` objects to true.

Nice! Thanks for the tip!

**Comment by cgwalters** [comment]
https://github.com/openshift/enhancements/pull/159

**Comment by cgwalters** [comment]
There has also been discussion around something a "disruption window" specifying when a pool could reboot.  One could imagine we define a CRD or so for that, something that allows multiple owners to pause at a time.

**Comment by cgwalters** [comment]
A case where this came up is around rotating the pull secret - we absolutely can just replace the kubelet pull secret live.  That would help a lot in a situation where e.g. one of the values leaked and needs to be rotated quickly without much cluster downtime.
