### ISSUE TITLE
oc edit node -> remove currentConfig annotation never reconciles

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#660]
As title says, if we drop the currentConfig annotation from a node, we're not going back. One thing we might want to do is (non trivial I guess) lookup what we've stored on disk in the MCD and re-load that.

**Comment by runcom** [comment]
now that ondisk state is there and respected/relied on for DR, I believe it's gonna be something we might want to fix instead of having the node crashlooping or manual intervention. Basically, if we, for whatever reason fail to grab the currentConfig in MCD, we're going to rely on what we have on disk and proceed w/o bailing.

**Comment by kikisdeliveryservice** [comment]
Addressed
