### ISSUE TITLE
Writable CRI-O hooks directory missing

### ISSUE THREAD

**Issue by lrgar** [openshift/machine-config-operator#669]
**Description**

If my understanding is correct, the default CRI-O configuration when creating an Openshift 4 environment is set by this Operator.

We, Dynatrace, use CRI-O hooks to inject our agent into container processes.

Based on the current state:
1. `hooks_dir` is not set on crio.conf. On this scenario, CRI-O will look for the implicit directories, `/etc/containers/oci/hooks.d`, and `/usr/share/containers/oci/hooks.d`
2. On a new OCP 4 environment, `/usr/share/containers/oci/hooks.d` was there although read-only. `/etc/containers/oci/hooks.d` didn't exist.
3. Our agent doesn't have a place to put its hook, since the `/usr` directory was read-only. If we create the `/etc/containers/oci/hooks.d` directory ourselves, then we also need to restart the CRI-O daemon so that the directory gets recognized, which is something we want to avoid.

At the end, we don't currently have a place to put our hook by default.

Also,
* On the default crio.conf templates on this repository, `hooks_dir_path` is being set. This is deprecated since CRI-O 1.12.6. It's now called `hooks_dir` and overrides the implicit hooks directories.

**Steps to reproduce the issue:**

1. Create a new Openshift environment with the latest [Openshift 4 installer](https://github.com/openshift/installer/releases/tag/v0.16.1).
2. Look for the `/etc/containers/oci/hooks.d` directory.

**Describe the results you received:**

There is no `/etc/containers/oci/hooks.d` directory.

**Describe the results you expected:**

There should be `/etc/containers/oci/hooks.d` directory.

**Additional information you deem important (e.g. issue happens only occasionally):**

Original PR for the CRI-O change (applies to 1.13): https://github.com/cri-o/cri-o/pull/1943
Backport to 1.12, released with CRI-O 1.12.6: https://github.com/cri-o/cri-o/pull/2061
CRI-O 1.12.6 release: https://github.com/cri-o/cri-o/releases/tag/v1.12.6
Current docs: https://github.com/cri-o/cri-o/blob/release-1.12/docs/crio.conf.5.md

**Output of `oc adm release info --commits | grep machine-config-operator`:**

```
$ oc adm release info --commits | grep machine-config-operator
  machine-config-controller                     https://github.com/openshift/machine-config-operator                       ee4e0643716780def1aadaaf7ef4f67b2f99cd7f
  machine-config-daemon                         https://github.com/openshift/machine-config-operator                       ee4e0643716780def1aadaaf7ef4f67b2f99cd7f
  machine-config-operator                       https://github.com/openshift/machine-config-operator                       ee4e0643716780def1aadaaf7ef4f67b2f99cd7f
  machine-config-server                         https://github.com/openshift/machine-config-operator                       ee4e0643716780def1aadaaf7ef4f67b2f99cd7f
  setup-etcd-environment                        https://github.com/openshift/machine-config-operator                       ee4e0643716780def1aadaaf7ef4f67b2f99cd7f
```

**Additional environment details (platform, options, etc.):**

After doing SSH to one of the nodes.

```
$ crio --version
crio version 1.12.9-1.rhaos4.0.gitaac6be5.el7

$ cat /etc/os-release
NAME="Red Hat Enterprise Linux CoreOS"
VERSION="410.8.20190325.0"
VERSION_ID="4.1"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 410.8.20190325.0 (Ootpa)"
ID="rhcos"
ID_LIKE="rhel fedora"
ANSI_COLOR="0;31"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.1"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.1"
OSTREE_VERSION=410.8.20190325.0
```

**Comment by runcom** [comment]
@mrunalp @umohnani8 ptal

>  If we create the /etc/containers/oci/hooks.d directory ourselves, then we also need to restart the CRI-O daemon so that the directory gets recognized, which is something we want to avoid.

Why is that tho? With the MCO you can deploy files (and parent dir gets created). Then you set the hookdir in crio conf via ContainerRuntimeConfig and MCO reboots the nodes and your config is applied.

Maybe we should just set hooks dir to the writable one in crio conf by default so users just lay down hooks and MCO restarts nodes

**Comment by lrgar** [comment]
Just to clarify, adding hooks to the directory doesn't require a CRI-O restart itself. The CRI-O daemon watches for changes on the hook directories already. You'll still need to restart the pods so it gets applied to them.

We are on the process of certifying our Dynatrace Operator with RedHat for Openshift 4, and ideally we would like to have it working out of the box. Our agent can add such file automatically, so that is OK as long as the directory exists.

From our point of view, it's OK for the customer to restart their environment, but we want to avoid making changes on the customer environment ourselves.

**Comment by runcom** [comment]
> We are on the process of certifying our Dynatrace Operator with RedHat for Openshift 4, and ideally we would like to have it working out of the box. Our agent can add such file automatically, so that is OK as long as the directory exists.

I believe that means that we can use the writable directory then? waiting for Mrunal to comment

> Just to clarify, adding hooks to the directory doesn't require a CRI-O restart itself. The CRI-O daemon watches for changes on the hook directories already. You'll still need to restart the pods so it gets applied to them.

this is how MCO works today (lay down something, reboot

**Comment by lrgar** [comment]
Yes, having `/etc/containers/oci/hooks.d` existing is sufficient for us.

**Comment by runcom** [comment]
> Yes, having `/etc/containers/oci/hooks.d` existing is sufficient for us.

hold on tho, can't you just ship a MachineConfig with something in that directory? that way, the parent /etc/containers/oci/hooks.d is created:

```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 50-examplecorp-hook
spec:
  config:
    ignition:
      version: 2.2.0
    storage:
      files:
      - contents:
          source: data:,HOOKS_DATA
        filesystem: root
        mode: 0644
        path: /etc/containers/oci/hooks.d/yourhooks
```

You can basically do the above, and the node is restarted making it effective (am I missing something?)

**Comment by lrgar** [comment]
We don't use MCO to store our hook. Our agent uses a privileged pod that has access to the host, and adds the hook file whenever it's required.

Again, our goal is to avoid having to restart the node if someone wants to use the Dynatrace Operator. If that directory exists, a customer can install our operator from the Openshift's Operator Hub and won't have to restart the node and break anything it's already running there.

I understand that this is a workaround. But from our point of view, since CRI-O supports hooks by default as long as the hooks directories exist, we would like to take advantage of this to provide simple and friction-less service to our customers.

**Comment by runcom** [comment]
> We don't use MCO to store our hook. Our agent uses a privileged pod that has access to the host, and adds the hook file whenever it's required.

got it, now I understand I think. I believe it's gonna be just a matter of creating that hook dir when installing the RPM @mrunalp @lsm5

**Comment by runcom** [comment]
cc @cgwalters as well if you have ideas/comments

**Comment by cgwalters** [comment]
A fix for this is in progress.

**Comment by runcom** [comment]
has this been solved? cc @lsm5

**Comment by cgwalters** [comment]
```
$ oc debug node/ip-10-0-156-156.us-east-2.compute.internal
# chroot /host
# rpm-ostree status -b
State: idle
AutomaticUpdates: disabled
BootedDeployment:
* pivot://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:7425a864b498dc18166ffdfeb14f500292e9681c854852d89f919c5b56203630
              CustomOrigin: Managed by pivot tool
                   Version: 410.8.20190509.3 (2019-05-09T11:53:46Z)
sh-4.4# ls -al /etc/containers/oci/hooks.d/
total 0
drwxr-xr-x. 2 root root  6 May 16 01:41 .
drwxr-xr-x. 3 root root 21 May 16 01:41 ..
sh-4.4# 
```
