### ISSUE TITLE
"pending config matches current! Failed to reboot" in CI

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#687]
https://search.svc.ci.openshift.org/?search=Failed+to+reboot&maxAge=168h&context=2&type=all

[This job](https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/operator-framework_operator-marketplace/171/pull-ci-operator-framework-operator-marketplace-master-e2e-aws-upgrade/30/artifacts/e2e-aws-upgrade/pods/) for example sohws the MCD in an infinite loop ∞ of:

> W0430 16:38:15.928620   92795 daemon.go:301] Booting the MCD errored with pending config rendered-master-ffee5d48648207ca0587519b2768dc98 bootID a0e96dcb-817b-478e-93ef-d5b90eb96b8b matches current! Failed to reboot

This is fallout from making the MCD a proper controller (which is good!) - but this error was originally designed to be fatal:

```
// getPendingConfig loads the JSON state we cache across attempting to apply
// a config+reboot.  If no pending state is available, ("", nil) will be returned.
// The bootID is stored in the pending state; if it is unchanged, we assume
// that we failed to reboot; that for now should be a fatal error, in order to avoid
// reboot loops.
```

What's unclear to me is how we got into this state.  I am not finding any earlier logs from previous boots.  That would inform a bit what we should do...
But...offhand, it feels to me like there's just a conflict between avoiding reboot loops and being a controller.  If we're going to keep trying that inevitably will involve rebooting.

**Comment by cgwalters** [comment]
I think `checkStateOnBoot` should probably learn instead to warn loudly if something isn't what we expect, but we should attempt to reconcile at least once.

Another option would be to have a `/run/machine-config-daemon/force.stamp` file which an admin could write to skip the state checks and force an update (i.e. we rewrite files, update the os etc.)

Or really both of these - the implementation here could be "write a 'we forced config' flag to the journal" before rebooting.  If on reboot and we detect that the previous reboot forced the config, then we just go degraded and don't try to apply again.

**Comment by runcom** [comment]
this should be #719 - basically, the logic pre-719 was flawed and even if we marked the config no more pending, if MCD restarted we would still be doing the bootid check but we should have not. 719 addresses that.

**Comment by runcom** [comment]
> https://search.svc.ci.openshift.org/?search=Failed+to+reboot&maxAge=168h&context=2&type=all

oh ok, this contains old jobs, nevermind.

**Comment by cgwalters** [comment]
We can easily reconcile osImageURL drift, just switch to the new one; done.

The interesting bits are the filesystem changes.  I think as long as we add a log message when we *start* a config change to the journal, then we can reliably know which state transition A -> B we were trying.  It should generally always work I think to do diff(A, B) and apply the changes by removing all files that are in A but not in B, then apply all files in A.

**Comment by cgwalters** [comment]
I think we're not seeing this anymore.
