### ISSUE TITLE
Update k8s drain lib so we can use stable daemonset API group

### ISSUE THREAD

**Issue by jlebon** [openshift/machine-config-operator#71]
See https://github.com/openshift/machine-config-operator/pull/70#discussion_r218148579.

**Comment by wking** [comment]
Should this be an issue in openshift/kubernetes-drain?  And should we get an `OWNERS` there with some of you on it?

I'd [still][1] like to get that library upstreamed into client-go or some such; anything that would help move in that direction is welcome :).

[1]: https://github.com/kubernetes/kubernetes/issues/25625#issuecomment-405056988

**Comment by runcom** [comment]
drain now has its own library in kube upstream, let's move forward to that (https://github.com/kubernetes/kubernetes/pull/72827)
