### ISSUE TITLE
max pods for baremetal

### ISSUE THREAD

**Issue by jtaleric** [openshift/machine-config-operator#723]
**Description**

How did we come up with `--max-pods=250`? I would like to understand how that number got decided on. When we run on `baremetal`, it might make sense to increase this. However, I want to make sure we use the same calculation/finger-in-the-wind that came to the 250 pod number. 

**Additional environment details (platform, options, etc.):**
baremetal

**Comment by runcom** [comment]
@abhinavdahiya @sjenning @rphillips ptal

**Comment by kikisdeliveryservice** [comment]
see also: https://github.com/openshift/machine-config-operator/pull/212

**Comment by sjenning** [comment]
an example of how to adjust `max-pods` is in the docs here
https://docs.openshift.com/container-platform/4.5/scalability_and_performance/recommended-host-practices.html#create-a-kubeletconfig-crd-to-edit-kubelet-parameters_

250 is the maximum supported but cluster-admins can go beyond that at their own risk if they know their pods are not stressful in kubelet terms (not many containers/secrets/configmaps/volumes/probes per pod).
