### ISSUE TITLE
automatically reconcile early config drift

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#726]
In e.g. a bare metal install it's easy to extract version N of the Ignition generated by the installer and set up a PXE server to point to it, and then update to version N+1 release payload.

This causes the `rendered-master-<hash> not found error`.

There are two things we could do.  First, I think we might as well serialize the full MC into the Ignition, as we discovered it's not large.  This would allow us to automatically reconcile state.

However, the next problem then is that the cluster would come up and immediately start rebooting.

An optimization here would be to pull the MCD image and run it at the same time we're doing early pivot (effectively this would reimplement early pivot).

**Comment by cgwalters** [comment]
As far as hacking this...I think it would work to edit the nodes and change their `currentConfig` annotation to match the `desiredConfig`.

**Comment by runcom** [comment]
> As far as working around this...I think it would work to edit the nodes and change their `currentConfig` annotation to match the `desiredConfig`.

I fear this isn't going to work:

```
	nodeAnnotations := map[string]string{
		daemonconsts.CurrentMachineConfigAnnotationKey:     conf,
		daemonconsts.DesiredMachineConfigAnnotationKey:     conf,
		daemonconsts.MachineConfigDaemonStateAnnotationKey: daemonconsts.MachineConfigDaemonStateDone,
	}
```

The desired config wouldn't be there either, but the cluster will have a completely different rendered machine-config. Also, not sure about how safe would it to be to discover the cluster rendered MC and apply that to the node, it risks differing from bootstrap for critical stuff which might lead to something bad.

**Comment by williamcaban** [comment]
Patching this might fix BZ https://bugzilla.redhat.com/show_bug.cgi?id=1764001 and issues described here  https://github.com/openshift/machine-config-operator/pull/1203#issuecomment-544886806
