### ISSUE TITLE
Add MCD OWNERS to manifest files

### ISSUE THREAD

**Issue by ashcrow** [openshift/machine-config-operator#73]
Currently those who are MCD owners have access to the code, but not the manifests/yaml files related to the code. Would it make sense to add them for things such as https://github.com/openshift/machine-config-operator/pull/60#issuecomment-422119132?

**Comment by jlebon** [comment]
Seeing as the MCD-specific manifests are already split in a separate subdir, we can do this without granting permissions to the rest of the manifests. I opened https://github.com/openshift/machine-config-operator/pull/75.

**Comment by abhinavdahiya** [comment]
I think OS team should have admin access to this repo. You guys will have to own entire code soon. :)

/cc @crawford

**Comment by jlebon** [comment]
> You guys will have to own entire code soon. :)

AFAIK, that is not actually the case.

**Comment by eparis** [comment]
I will have a conversation with Ian.
