### ISSUE TITLE
shortName(s) for machineconfig and machineconfigpools in CRDs

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#737]
possibly ~~ContainerRuntimeConfig~~ and KubeletConfig (haven't checked). Would be nice to do `oc get mcps` or `oc describe mcp worker` or `oc get mc 00-master` instead of typing the whole `machineconfigpool` for instance. The container runtime crd already does this (but maybe it needs plural? https://github.com/openshift/machine-config-operator/blob/master/manifests/containerruntimeconfig.crd.yaml#L13)

Also, we should check for upgradeability for this w/o breaking our api (haven't checked myself)

**Comment by LorbusChris** [comment]
strong +1 for shortNames!

I couldn't find an example where they have a plural, though. Might not be needed?

**Comment by runcom** [comment]
> Might not be needed?

yeah might not be needed, let's double check upstream as well

/assign @LorbusChris

**Comment by runcom** [comment]
closed by #840
