### ISSUE TITLE
Fold MCO images into one

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#739]
Since MCO and MCC are strictly related, it would be appropriate to fold all our images into just one to avoid falling into bugs and error whenever the build system isn't properly setup and could lead to different images being built from different commits. 

This requires changes at least to:

- installer's bootkube
- mco itself

To expand on the above, this should be done in 2 steps to avoid any breakage (and we need to think about backwards compatibility as well):

- tweak bootkube to accept the MCO image itself (requires a PR in MCO to add a new flag for the MCO image, then a PR in the installer for bootkube to pass it)
- change Dockerfiles to build all binaries into a single image here in MCO
- remove the entrypoint(s) from the image above
- create a compatibility entrypoint for https://github.com/openshift/installer/blob/master/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template#L187 and set it to the above image
- tweak the `machine-config-operator` cmd to no-op on these flags https://github.com/openshift/installer/blob/master/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template#L196-L200 (except kube-client-agent) image, and instead use the MCO image itself directly (which we plugged at the beginning)
- now the CI should be good so merge the above PR
- create a PR in the installer to tweak bootkube to only use 1 image
- merge the above
- remove compatibility code from point 1 and the fake entrypoint and all other compatibility code
- merge the above
- done

**Comment by runcom** [comment]
I've expanded the points above to something clearer now

**Comment by runcom** [comment]
@cgwalters ptal

**Comment by cgwalters** [comment]
A preparatory step for this is probably to go to a single binary (`hypermco`) too right?  Otherwise we're wasting a lot of space.  But I guess it's not required.

I was thinking of this more like:

 - Change e.g. `Dockerfile.machine-config-operator` to put all the binaries inside there
 - Drop the default `ENTRYPOINT`, change our manifests to launch that image

Now we have a single image running in the cluster by default; no other PRs to installer required right?
But we are building 3 unnecessary images, so the remaining work would be similar to your outline.  I suspect we'd also need patches to the release controller and ART's configuration to delete builds?

**Comment by runcom** [comment]
> I suspect we'd also need patches to the release controller and ART's configuration to delete builds?

yep, that's gonna be a required thing anyway.

> I was thinking of this more like:
> 
> * Change e.g. `Dockerfile.machine-config-operator` to put all the binaries inside there
> * Drop the default `ENTRYPOINT`, change our manifests to launch that image

The thing is bootkube needs to have plumbing for that MCO image as well (we're currently just passing the MCC/MCD/MCS image names to the render routine, now we'll need another one, the MCO one since that's currently just substituted by `oc adm release new`)

**Comment by cgwalters** [comment]
If we don't change the `ENTRYPOINT` then the behavior of the MCO image in `bootkube.sh` shouldn't require changes right?  I edited my suggestion above.

**Comment by runcom** [comment]
> If we don't change the `ENTRYPOINT` then the behavior of the MCO image in `bootkube.sh` shouldn't require changes right? I edited my suggestion above.

yes, maybe I'm wrong, but the image names must be plumbed anyway through i.e. https://github.com/openshift/installer/blob/master/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template#L199 to be rendered in the manifest for the other subcomponents - that's why I thought we needed changes in bootkube also

**Comment by runcom** [comment]
Something like this:
```
diff --git a/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template b/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
index ecb30c8f0..4364e2950 100755
--- a/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
+++ b/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template
@@ -199,6 +199,7 @@ then
                        --machine-config-server-image=${MACHINE_CONFIG_SERVER_IMAGE} \
                        --machine-config-daemon-image=${MACHINE_CONFIG_DAEMON_IMAGE} \
                        --machine-config-oscontent-image=${MACHINE_CONFIG_OSCONTENT} \
+                       --machine-config-operator=${MACHINE_CONFIG_OPERATOR_IMAGE} \
                        --infra-image=${MACHINE_CONFIG_INFRA_IMAGE} \
                        --cloud-config-file=/assets/manifests/cloud-provider-config.yaml
```
so that we can render the subcomponents manifests with that image

maybe I'm overlooking something obvious tho

**Comment by cgwalters** [comment]
> so that we can render the subcomponents manifests with that (single) image

Oh sorry I see!  Right.  Yes.  Though I think we could also use the downward API to inspect our own pod's container image or so?

**Comment by runcom** [comment]
> Though I think we could also use the downward API to inspect our own pod's container image or so?

 we could also yeah - I thought about going the proper way through bootkube as this is not something we'll block the next release on so we might as well just do it through bootkube

**Comment by kikisdeliveryservice** [comment]
**Tracking PRs for this Epic:**

**Closed:**

mco: add mco image flag: https://github.com/openshift/machine-config-operator/pull/847

installer: add mco image: https://github.com/openshift/installer/pull/1847

mco: create a single mco image: https://github.com/openshift/machine-config-operator/pull/850

installer: remove image refs for mco components: https://github.com/openshift/installer/pull/1875

updated release repo: https://github.com/openshift/release/pull/4153

mco: remove required flags for mco component images: https://github.com/openshift/machine-config-operator/pull/897

mco: update templates: https://github.com/openshift/machine-config-operator/pull/899

mco: ratchet new dockerfile name: https://github.com/openshift/machine-config-operator/pull/941

**Open:**

release: rename mco dockerfile: https://github.com/openshift/release/pull/4314

ART: update dockerfiles: ocp-build-data/merge_requests/181

**WIP:**

mco: remove all refs to component images: https://github.com/openshift/machine-config-operator/pull/895

**Comment by kikisdeliveryservice** [comment]
@runcom once this is all finished - doesn't this work close #421

**Comment by runcom** [comment]
> @runcom once this is all finished - doesn't this work close #421

yep 👍
