### ISSUE TITLE
the MCD shouldn't mark a node degraded because of it's own bugs

### ISSUE THREAD

**Issue by sdemos** [openshift/machine-config-operator#74]
There are several bugs right now (#66, #68 for example) which, because they trigger errors, set the node into a degraded state. It seems to me like we should consider breaking up "this error means there is something wrong with the node that we can't fix" and "this error means there is something wrong with us or our configuration" wherever possible, so that we aren't throwing around the degraded label when it might not actually apply.

Like, for instance, I think it wouldn't be great if we had the node-reprovision-on-degraded-state setup, and then we hit #66 and discover that our nodes are getting reprovisioned every 20 minutes because of a bug in the daemon.

We should be able to do this by having an additional return value plumbed through, where we say whether or not this is an error that indicates a degraded state or not. 

Thoughts?

**Comment by jlebon** [comment]
Yeah, that makes sense to me.

> Like, for instance, I think it wouldn't be great if we had the node-reprovision-on-degraded-state setup

Is this currently the only code that would read the degraded state label?

**Comment by ashcrow** [comment]
I think this makes sense. Should we create a type to hold internal items like this and pass it around, or do you think that `degraded` would be the only extra item to pass around?

**Comment by sdemos** [comment]
> Is this currently the only code that would read the degraded state label?

afaik, but I don't know if there are plans in the future to key off of it for different things instead, so either way we should be careful with the semantics of the degraded state label. 

> Should we create a type to hold internal items like this and pass it around, or do you think that degraded would be the only extra item to pass around?

I don't foresee anything else that we would generally want to pass around that are in this category. If something else comes up in the future, it shouldn't be a hard refactor to change it to a type, but for now I think just having a `degraded` return value should be enough.

I'll take a look at implementing this.

**Comment by sdemos** [comment]
I implemented the approach I had in here a while ago but it would need a complete rewrite to fit with the new structure with informers (it didn't even rebase cleanly onto my comparatively mild changes to process before that pr). I don't think I'm in a good position to continue to take this on, so if someone else wants to pick it up, that would be awesome.

I've thought a little more about this in the meantime as well. I think in particular, the class of errors that shouldn't mark the node degraded will be errors from kubernetes interactions. I don't think that errors there indicate degradation on the node, and anyway, if there are non-transient errors in the kube layer there's probably something even more wrong and we can't do anything about it. 

I can't think of any errors returned from interactions with the node that shouldn't result in degradation. I don't think there is a consistent way to know whether it's an error we can ignore or something we need to feed up the stack, and this work should air on the side of caution and degrade nodes if it doesn't (or can't) know either way.

**Comment by cgwalters** [comment]
Related: https://github.com/openshift/machine-config-operator/pull/206

**Comment by cgwalters** [comment]
This is done.
