### ISSUE TITLE
Add a basic HACKING.md

### ISSUE THREAD

**Issue by jlebon** [openshift/machine-config-operator#8]
It'd be nice if there was a `HACKING.md` with instructions on how to build and test this code in a real cluster. I know a lot of this stuff is still :construction: under construction :construction:, though such a doc, even if primitive/high-level, would help other contributors start hacking early on.

**Comment by ashcrow** [comment]
@jlebon I added basic build instructions as part of 4fe5522bc7887c11aab4be554fe7c39627582436. I'll add a PR for using `go test` as there isn't a `Makefile` or other single location to execute such things yet.

**Comment by jlebon** [comment]
Thanks! Yeah, the building part is nice. Though the more interesting part is actually deploying it onto a cluster to test it. AIUI, this is done right now by instantiating the resource files in `manifests/`.

**Comment by ashcrow** [comment]
:+1: I'll defer the instantiating resources item to folks who are doing that today as I haven't had to do so yet in my development.
