### ISSUE TITLE
MCD: Log level clean up

### ISSUE THREAD

**Issue by ashcrow** [openshift/machine-config-operator#80]
In the logs we are using a combination of default verbosity and 2. However, most, if not all, of our current logging seems like it would be beneficial in normal circumstances. 

## What brings this up

Looking at the log output of https://github.com/openshift/machine-config-operator/issues/79 brought this to mind.

## Proposal

- Use default V for general information useful to admins
- Use `V(2)` for more fine grained items
- Use `V(3)` for debug level logging

## Example

`Daemon.enableUnit` could be updated like:

```golang
// enableUnit enables a systemd unit via symlink
func (dn *Daemon) enableUnit(unit ignv2_2types.Unit) error {
	// The link location
	wantsPath := filepath.Join(wantsPathSystemd, unit.Name)
	// sanity check that we don't return an error when the link already exists
	if _, err := os.Stat(wantsPath); err == nil {
		glog.Infof("%s already exists. Not making a new symlink", wantsPath)
		return nil
	}
	// The originating file to link
	servicePath := filepath.Join(pathSystemd, unit.Name)
	err := os.Symlink(servicePath, wantsPath)
        if err == nil {
    	    glog.Infof("Enabled %s", unit.Name)
            glog.V(3).Infof("Symlinked %s to %s", servicePath, wantsPath)
        } else {
            glog.Warningf("Unable to enable unit %s: %s", unit.Name, err)
        }
        return err
}
```

/cc @sdemos @jlebon @kikisdeliveryservice

**Comment by jlebon** [comment]
Or maybe just two levels? I.e. the default, and `V(2)` for debugging? The more levels you have, the more you have to think about each print statement you add. Whereas "is this only useful for debugging?" is easier to answer.

**Comment by ashcrow** [comment]
I'd be fine with two levels.

**Comment by ashcrow** [comment]
@kikisdeliveryservice is picking this work up. Thanks @kikisdeliveryservice!

**Comment by kikisdeliveryservice** [comment]
So to confirm, I'm updating functions in daemon/update.go using the default and V(2) as appropriate?

**Comment by ashcrow** [comment]
@kikisdeliveryservice in part yes :-). There are a few things to do to close this issue:

1. Ensure that default (no `V`) use is consistent
2. Ensure that `V(2)` is consistent
3. Add logs for both verbosity to help support folks know what's happening.

Think of the default as `info` level and `V(2)` as `debug` level.

**Comment by kikisdeliveryservice** [comment]
@ashcrow Thanks for the clarification!

I'll link to my WIP once I have something pushed.
