### ISSUE TITLE
Can't import machine-config-operator

### ISSUE THREAD

**Issue by jmontleon** [openshift/machine-config-operator#848]
I'm trying to import github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/v1

Go get fails with:
```
-> unzip /home/jmontleo/Documents/openshift/pkg/mod/cache/download/github.com/openshift/machine-config-operator/@v/v3.11.0+incompatible.zip: malformed file path "pkg/controller/template/test_data/templates/aws/master/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt": invalid char ':'
```

Digging around it looks like the colon is reserved on Windows so go doesn't consider it valid.

**Steps to reproduce the issue:**
```
$ go get https://github.com/openshift/machine-config-operator
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
	ignoring go.mod;
	see 'go help modules'
package https:/github.com/openshift/machine-config-operator: https:/github.com/openshift/machine-config-operator: invalid import path: malformed import path "https:/github.com/openshift/machine-config-operator": invalid char ':'
```

**Describe the results you expected:**
It should be possible to go get and import

**Additional information you deem important (e.g. issue happens only occasionally):**
https://github.com/golang/go/issues/28001

**Output of `oc adm release info --commits | grep machine-config-operator`:**
N/A

**Additional environment details (platform, options, etc.):**
N/A

**Comment by runcom** [comment]
we're not using go mod just yet and code isn't ready to move to it right now. Guess we need to fix this anyway once kube switches to that maybe.

**Comment by ashcrow** [comment]
@runcom is there an upstream issue in kube for the move?

**Comment by runcom** [comment]
I need to check on it

**Comment by runcom** [comment]
FYI, current master doesn't have this issue since we got rid of that file specifically (test_data...)

**Comment by gildub** [comment]
@runcom,

Still same issue.
Although it's not explicitly listed, maybe it need a relesae attach to it but I tried with tag `@4.2.0-201907161330`

```
go list -m --versions github.com/openshift/machine-config-operator
github.com/openshift/machine-config-operator v0.0.0 v3.11.0+incompatible v4.0.0-alpha.0+incompatible v4.2.0-alpha.0+incompatible
```

**Comment by jhrozek** [comment]
The [compliance operator](https://github.com/openshift/compliance-operator) would benefit from having this issue fixed or possible to work around. In the operator, we'd like to create MachineConfig objects as remediations for compliance issues in the cluster.

I'm still hitting the issue as of today:
```
go get -u github.com/openshift/machine-config-operator
go: extracting github.com/openshift/machine-config-operator v3.11.0+incompatible
-> unzip /home/jhrozek/go/pkg/mod/cache/download/github.com/openshift/machine-config-operator/@v/v3.11.0+incompatible.zip: malformed file path "pkg/controller/template/test_data/templates/aws/master/files/-etc-docker-certs.d-docker-regis
try.default.svc:5000-ca.crt": invalid char ':'
package github.com/openshift/machine-config-operator: unknown import path "github.com/openshift/machine-config-operator": unzip /home/jhrozek/go/pkg/mod/cache/download/github.com/openshift/machine-config-operator/@v/v3.11.0+incompatible.
zip: malformed file path "pkg/controller/template/test_data/templates/aws/master/files/-etc-docker-certs.d-docker-registry.default.svc:5000-ca.crt": invalid char ':'
```

**Comment by harche** [comment]
@runcom I am writing an operator where I can want to write file using MCO, but because of this bug I am not able to import `MachineConfig`. I guess for now, I will follow what @jhrozek did in this commit, https://github.com/jhrozek/compliance-operator-1/commit/f214d7c2aafb672ecac09a28c9404a03174d0dc3

**Comment by enxebre** [comment]
I'm facing this too, is this API not consumable atm?

**Comment by gmeghnag** [comment]
I'm facing the same issue..
