### ISSUE TITLE
controller: empty platform vs platform none

### ISSUE THREAD

**Issue by kikisdeliveryservice** [openshift/machine-config-operator#857]
So reading through render.go, I'm wondering why we treat an empty platform as an error and not a platformNone? Mostly I'm looking at:
https://github.com/openshift/machine-config-operator/blob/0d843aa29c6a5ce5aedcd1cb1638d2383ea17e41/pkg/controller/template/render.go#L123

```
func platformFromControllerConfigSpec(ic *mcfgv1.ControllerConfigSpec) (string, error) {
	switch ic.Platform {
	case "":
		return "", fmt.Errorf("cannot generate MachineConfigs with an empty platform field")
	case platformBase:
		return "", fmt.Errorf("platform _base unsupported")
	case platformAWS, platformAzure, platformBaremetal, platformOpenstack, platformLibvirt, platformNone:
		return ic.Platform, nil
	default:
		glog.Warningf("Warning: the controller config referenced an unsupported platform: %s", ic.Platform)
		return platformNone, nil
	}
}
```

if platform is ""/ empty it's not construed as None. For it to be none it literally has to be "None", which ok, but should maybe the Error say something about that at least? `cannot generate MachineConfigs with an empty platform field, to indicate no platform use "platform: None"` or something?

Just wondering how clear this is and what we're trying to cover with the "" check.

**Comment by sgreene570** [comment]
Also definitely worth nothing that if we switch over to the openshift API `PlatformType` object, there is no "base" platform, just the "none" platform.

https://github.com/openshift/api/blob/master/config/v1/types_infrastructure.go
