### ISSUE TITLE
Modifying the `/etc/localtime` symlink with a machine config doesn't work

### ISSUE THREAD

**Issue by e-minguez** [openshift/machine-config-operator#871]
**Description**
Trying to modify the timezone of the RHCOS workers in OCP4.1 doesn't seem to work.

**Steps to reproduce the issue:**
1. Create a machine config as:
```
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-timezone-worker
spec:
  config:
    ignition:
      config: {}
      security:
        tls: {}
      timeouts: {}
      version: 2.2.0
    networkd: {}
    passwd: {}
    storage:
      links:
      - filesystem: root
        hard: false
        overwrite: true
        path: "/etc/localtime"
        target: "/usr/share/zoneinfo/Europe/Madrid"
    systemd: {}
  kernelArguments: null
  osImageURL: ""
```
2. Apply it `oc apply -f <file>`
3. Wait for the worker to be rebooted and configured with the Europe/Madrid timezone.

**Describe the results you received:**

The machine-config-daemon pod for the worker says:

```
I0620 15:22:09.829250    2522 update.go:836] controller syncing started
I0620 15:22:09.833412    2522 update.go:174] Checking reconcilable for config rendered-worker-e6a4b0979577baf840166015d5d96b00 to rendered-worker-e6a4b0979577baf840166015d5d96b00
I0620 15:22:09.834727    2522 update.go:836] Starting update from rendered-worker-e6a4b0979577baf840166015d5d96b00 to rendered-worker-e6a4b0979577baf840166015d5d96b00
I0620 15:22:09.837658    2522 update.go:388] Updating files
I0620 15:22:09.837681    2522 update.go:590] Writing file "/etc/tmpfiles.d/cleanup-cni.conf"
I0620 15:22:09.840499    2522 update.go:590] Writing file "/etc/systemd/system.conf.d/kubelet-cgroups.conf"
I0620 15:22:09.842564    2522 update.go:590] Writing file "/var/lib/kubelet/config.json"
I0620 15:22:09.845077    2522 update.go:590] Writing file "/etc/kubernetes/ca.crt"
I0620 15:22:09.847482    2522 update.go:590] Writing file "/etc/sysctl.d/forward.conf"
I0620 15:22:09.849470    2522 update.go:590] Writing file "/etc/kubernetes/kubelet-plugins/volume/exec/.dummy"
I0620 15:22:09.850736    2522 update.go:590] Writing file "/etc/containers/registries.conf"
I0620 15:22:09.852986    2522 update.go:590] Writing file "/etc/containers/storage.conf"
I0620 15:22:09.855248    2522 update.go:590] Writing file "/etc/crio/crio.conf"
I0620 15:22:09.857887    2522 update.go:590] Writing file "/etc/kubernetes/cloud.conf"
I0620 15:22:09.859279    2522 update.go:590] Writing file "/etc/kubernetes/kubelet.conf"
I0620 15:22:09.861550    2522 update.go:545] Writing systemd unit "kubelet.service"
I0620 15:22:09.863627    2522 update.go:562] Enabling systemd unit "kubelet.service"
I0620 15:22:09.863719    2522 update.go:482] /etc/systemd/system/multi-user.target.wants/kubelet.service already exists. Not making a new symlink
I0620 15:22:09.863729    2522 update.go:407] Deleting stale data
I0620 15:22:09.863749    2522 update.go:652] Writing SSHKeys at "/home/core/.ssh/authorized_keys"
I0620 15:22:09.869587    2522 update.go:801] logger doesn't support --jounald, logging json directly
I0620 15:22:09.874864    2522 update.go:836] Update prepared; beginning drain
I0620 15:22:09.955417    2522 update.go:836] drain complete
I0620 15:22:09.959509    2522 update.go:836] initiating reboot: Node will reboot into config rendered-worker-e6a4b0979577baf840166015d5d96b00
I0620 15:22:10.090866    2522 start.go:215] Shutting down MachineConfigDaemon
```

Then, after reboot:

```
I0620 15:26:18.630319    2861 update.go:836] controller syncing started
I0620 15:26:18.640397    2861 update.go:174] Checking reconcilable for config rendered-worker-e6a4b0979577baf840166015d5d96b00 to rendered-worker-a68141c31b952917b0ab5c31bf6a4226
E0620 15:26:18.642538    2861 writer.go:109] Marking Unreconcilable due to: can't reconcile config rendered-worker-e6a4b0979577baf840166015d5d96b00 with rendered-worker-a68141c31b952917b0ab5c31bf6a4226: ignition links section contains changes: unreconcilable
```

And the symlink didn't changed

**Describe the results you expected:**
The symlink is modified.

**Additional information you deem important (e.g. issue happens only occasionally):**
Manually running `timedatectl` changes the `/etc/localtime` symlink and it works.

**Output of `oc adm release info --commits | grep machine-config-operator`:**

```
  machine-config-controller                     https://github.com/openshift/machine-config-operator                       a3a9a27ddff494b5735992a564b238ccae7564e2
  machine-config-daemon                         https://github.com/openshift/machine-config-operator                       a3a9a27ddff494b5735992a564b238ccae7564e2
  machine-config-operator                       https://github.com/openshift/machine-config-operator                       a3a9a27ddff494b5735992a564b238ccae7564e2
  machine-config-server                         https://github.com/openshift/machine-config-operator                       a3a9a27ddff494b5735992a564b238ccae7564e2
  setup-etcd-environment                        https://github.com/openshift/machine-config-operator                       a3a9a27ddff494b5735992a564b238ccae7564e2
```

**Additional environment details (platform, options, etc.):**

**Comment by kikisdeliveryservice** [comment]
We currently do not support updates to storage: links as per the error message:
```b5c31bf6a4226
E0620 15:26:18.642538    2861 writer.go:109] Marking Unreconcilable due to: can't reconcile config rendered-worker-e6a4b0979577baf840166015d5d96b00 with rendered-worker-a68141c31b952917b0ab5c31bf6a4226: ignition links section contains changes: unreconcilable```

This is indicated in the documentation:
https://github.com/openshift/machine-config-operator/blob/master/docs/MachineConfigDaemon.md#supported-vs-unsupported-ignition-config-changes

**Comment by e-minguez** [comment]
Closing it then. Thanks!

**Comment by kimba74** [comment]
@e-minguez How did you end up configuring the timezone on the nodes since Links are not supported (yet?).

**Comment by e-minguez** [comment]
> @e-minguez How did you end up configuring the timezone on the nodes since Links are not supported (yet?).

I didn't. I guess you can just base64 the tzdata file `/usr/share/zoneinfo/Europe/Madrid` and apply a file machineconfig with that content.

**Comment by kimba74** [comment]
> 
> I didn't. I guess you can just base64 the tzdata file `/usr/share/zoneinfo/Europe/Madrid` and apply a file machineconfig with that content.

Yikes! That's what I thought but hoped for a different response ;o)

Maybe we need to open a feature request. Would be cool if that could be done via an Operator or similar.

**Comment by cgwalters** [comment]
And more importantly, the current opinion at a higher level is that node timezone in OpenShift 4 should always be UTC.

**Comment by kimba74** [comment]
Which is all fine and good in theory but our clients CISO requires all resources to be set to their HQ's timezone regardless of where they are located. So I took took the suggestion with the base64 timezone from above and it works. At least I get my ATO that way.

**Comment by kimba74** [comment]
Alright, the base54 overwrite option is not an option either. While it does set the date and time of the node correctly `timedatectl` does not recognize it and thus the cronjobs still get executed with UTC. After some digging I found this in the man pages oc `timedatectl`:

>  Because the timezone identifier is extracted from the symlink target name of /etc/localtime, this file may not be a normal file or hardlink.

So here is the answer why that didn't work. Somewhere for an older OpenShift instance (~3.10) I read that the cronjobs are now scheduled through a controller and that setting the TZ on that controller pod (either via `env TZ` or by mounting the node's `localtime` file) should solve that problem. But since OpenShift4 is much different than 3.10 I have no clue if that still applies or if that has moved to a different pod. 

I'll keep investigating but if anybody have suggestion on how to execute the cronjobs in a specific timezone please let me know. (Reason: UTC does not observe DST and this would make scheduling more specific cronjobs difficult)

**Comment by e-minguez** [comment]
I guess that another solution is to create a daemonset that mounts the host filesystem, creates a symlink then waits forever.

**Comment by kimba74** [comment]
Besides that being a pretty horrible hack I'm not even sure it would work. The Containers seem to keep running on UTC regardless of what the underlying nodes have configured as time zone. Also, if what I have seen online so far is true (mainly 3.10+ posts), the cronjobs are scheduled by a controller and abide to its time zone.

So, having said that, for solving the timing issue with cronjobs we would have to figure out which controller (controller-manager?) schedules the cronjobs in 4.x and if changing its time zone has an adverse effect on the rest of the system.
