### ISSUE TITLE
machineconfigoperator bootstrap pod cann't be created because the required image in manifests is missing

### ISSUE THREAD

**Issue by dongyanyang** [openshift/machine-config-operator#874]
**Description**

When use openshift-installer of branch release-4.2 to create cluster of openstack platform, the machineconfigoperator-bootstrap-pod failed, so the bootstrap server does not have 22623 port bind and the master machines cann't get the ignition configs.

The error log in journalctl:
hyperkube[1512]: E0621 07:03:43.400947    1512 file.go:187] Can't process manifest file "/etc/kubernetes/manifests/machineconfigoperator-bootstrap-pod.yaml": invalid pod: [spec.containers[0].image: Required value spec.initContainers[0].image: Required value]

**Steps to reproduce the issue:**
1. build openshift-installer with release-4.2 branch and update PlatformNames and HiddenPlatformNames in pkg/types/installconfig.go to expose openstack platform.
2. deploy an openstack cloud
3. openshift-install create cluster (with clouds.yaml filled with openstack cloud info deployed in step #2 )
4. logon to the bootstrap server and check journalctl logs

**Describe the results you received:**

**Describe the results you expected:**

machineconfigoperator-bootstrap-pod should be created without error

**Additional information you deem important (e.g. issue happens only occasionally):**

Checked the content of /etc/kubernetes/manifests/machineconfigoperator-bootstrap-pod.yaml, the image field for both the machine-config-controller and machine-config-server are null:
[root@ipicluster-2dfw7-bootstrap ~]# cat /etc/kubernetes/manifests/machineconfigoperator-bootstrap-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: bootstrap-machine-config-operator
  namespace:
spec:
  initContainers:
  - name: machine-config-controller
    image:
    command: ["/usr/bin/machine-config-controller"]
    args:
    - "bootstrap"
    - "--manifest-dir=/etc/mcc/bootstrap"
    - "--dest-dir=/etc/mcs/bootstrap"
    - "--pull-secret=/etc/mcc/bootstrap/machineconfigcontroller-pull-secret"
    resources:
      limits:
        memory: 50Mi
      requests:
        cpu: 20m
        memory: 50Mi
    securityContext:
      privileged: true
    volumeMounts:
    - name: bootstrap-manifests
      mountPath: /etc/mcc/bootstrap
    - name: server-basedir
      mountPath: /etc/mcs/bootstrap
  containers:
  - name: machine-config-server
    image:
    command: ["/usr/bin/machine-config-server"]
    args:
      - "bootstrap"
    volumeMounts:
    - name: server-certs
      mountPath: /etc/ssl/mcs
    - name: bootstrap-kubeconfig
      mountPath: /etc/kubernetes/kubeconfig
    - name: server-basedir
      mountPath: /etc/mcs/bootstrap
    securityContext:
      privileged: true
  hostNetwork: true
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  restartPolicy: Always
  volumes:
  - name: server-certs
    hostPath:
      path: /etc/ssl/mcs
  - name: bootstrap-kubeconfig
    hostPath:
      path: /etc/mcs/kubeconfig
  - name: server-basedir
    hostPath:
      path: /etc/mcs/bootstrap
  - name: bootstrap-manifests
    hostPath:
      path: /etc/mcc/bootstrap

**Comment by dongyanyang** [comment]
I doubt this error is related to the latest change: https://github.com/openshift/machine-config-operator/commit/23cc9b8f5733de8c2efd0ac1772f1a70a6dcdd8a

**Comment by runcom** [comment]
Can you tell us which branch 4.2 commit were you using for the installer?

**Comment by runcom** [comment]
cc @kikisdeliveryservice - I believe the installer version you're using doesn't have a patch in the installer which is the one plumbing down the image to manifests

**Comment by kikisdeliveryservice** [comment]
Yes @dongyanyang  you'll probably want to be using master (or an approve image from registry.ci) as I don't think the release-4.2 is being used/kept up to date yet.

**Comment by kikisdeliveryservice** [comment]
@dongyanyang please try updating your installer to pull in the latest changes. It looks like you are using an updated MCO payload but still using an older branch. This can happen bc the images for that branch are not pinned.

**Comment by dongyanyang** [comment]
My openshift-install version:

[root@zvmci2-master ~]# openshift-install version
openshift-install unreleased-master-1099-g25d1ae28d11c71b96fb8b8de1095911923d9d8ee-dirty
built from commit 25d1ae28d11c71b96fb8b8de1095911923d9d8ee
release image registry.svc.ci.openshift.org/origin/release:4.2
