### ISSUE TITLE
Reason should be one word not full message

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#890]
There are several occurrences where we're setting the Reason field to a long message rather than a one-word simple message. This happens today with the ControllerConfig and MachineConfigPool. It hasn't caused issues like https://github.com/openshift/machine-config-operator/pull/879 but we need to basically move what we're now setting as Reason to Message (and either leave Reason empty cause we don't really need it, we have the Type field).

Examples:

Must be flipped and Reason set to `""`

https://github.com/openshift/machine-config-operator/blob/master/pkg/controller/node/status.go#L76

Flip as well and Reason empty https://github.com/openshift/machine-config-operator/blob/0d843aa29c6a5ce5aedcd1cb1638d2383ea17e41/pkg/controller/template/status.go#L21

There are other occurrences of course, the above are just examples from code

**Comment by sgreene570** [comment]
Does this warrant changing the `MachineConfigPoolCondition` and `NewControllerConfigStatusCondition` since all instances of the types would have at least one empty field? Or is should we be flipping message with reason and setting reason to a one word string? Trying to better understand what you have in mind.

**Comment by runcom** [comment]
> Does this warrant changing the `MachineConfigPoolCondition` and `NewControllerConfigStatusCondition` since all instances of the types would have at least one empty field? Or should we be flipping message with reason and setting reason to a one word string? Trying to better understand what you have in mind.

just flipping reason with message and leaving Reason empty cause the Type field is expressive enough
