### ISSUE TITLE
Add CRD openapi

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#930]
Following https://github.com/openshift/origin/pull/22696/files#diff-b212b5fb9c78264b938f2bc554a80376R90 and https://github.com/openshift/cluster-version-operator/pull/168/files - our CRDs need to provide openAPIV3Schema for validation and oc explain

This is related to https://bugzilla.redhat.com/show_bug.cgi?id=1705750

Work started here https://github.com/openshift/machine-config-operator/pull/928 (cc @vrutkovs )

**Comment by LorbusChris** [comment]
linking this here for reference: https://github.com/openshift/crd-schema-gen
