### ISSUE TITLE
report rpm-ostree overrides

### ISSUE THREAD

**Issue by cgwalters** [openshift/machine-config-operator#945]
Today if one e.g. `rpm-ostree override replace ./kernel-blah.x86_64.rpm` on a node (as our hacking doc mentions), the MCO is totally unaware of this and os upgrades *will* preserve that override, which people may not always want.

Further, we should at least roll up somewhere into at least the pool status the fact that there are overrides.

(Also tangentially related to this topic, I think `MachineConfigPool` should have a status flag set if any nodes aren't RHCOS)

**Comment by runcom** [comment]
> (Also tangentially related to this topic, I think `MachineConfigPool` should have a status flag set if any nodes aren't RHCOS)

super true this, I always oc get nodes -o wide to understand if I'm on RHCOS+RHEL

**Comment by cgwalters** [comment]
Or, another important question here: should we report or go degraded?  Today if one manually overrides the booted deployment entirely via e.g. `pivot` or `rpm-ostree rebase` the MCD will go degraded.
