### ISSUE TITLE
Pin a version of go bin-data or atleast document which one to use

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [openshift/machine-config-operator#951]
**Description**
As of now, there are many variants of go bin-data. As a contributor, it becomes difficult to identify which version of bindata I should use. Can this be explicitly documented or have that library vendored and pinned. The other advantage of having the version pinned is, we don't have to explicitly mention which version of bin-data library to use

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `oc adm release info --commits | grep machine-config-operator`:**

```
(paste your output here)
```

**Additional environment details (platform, options, etc.):**

**Comment by kikisdeliveryservice** [comment]
This issue actually brought down our ci today. In summary:

`test verify` started failing across PRs. I noticed it happening #953 which is a simple doc fix. When looking at verify i saw:

```
 --- hack/../_tmp/pkg/operator/assets/bindata.go    2019-07-11 20:25:22.160515877 +0000
+++ hack/../pkg/operator/assets/bindata.go    2019-07-11 20:25:22.176516911 +0000
@@ -66,7 +66,7 @@ func (fi bindataFileInfo) Mode() os.File
     return fi.mode
 }
 
-// Mode return file modify time
+// ModTime return file modify time
 func (fi bindataFileInfo) ModTime() time.Time {
     return fi.modTime
 } 
```

Which matches the first change in a month to go into go-bindata: https://github.com/go-bindata/go-bindata/commit/a87177b60aad08824a6f8b96d9c3dfa1117ebe6c#diff-15036d5e0876436b1832c7721c9c7afd

Note that this changes is a mere comment change but gave us non-matching bindata and brought our CI to a halt.

As a fix we updated bindata.go here in #957 but we should probably be pinning all of these gopkgs going forward and document this as ravi suggested above.

Further, we will also have to update both our repo and release (see https://github.com/openshift/release/pull/4282/files) which also doesn't pin.  walters has suggested that we could change the release job to run a script from our repo.

**Comment by kikisdeliveryservice** [comment]
Also in the course of troubleshooting this I realized that I (and other people) were using an old go bindata version (a change went in recently that we didnt update locally) so it would be good to update documentation as well for dev systems.

**Comment by kikisdeliveryservice** [comment]
Other issue is that `make update` just checks that there is `go-bindata` so that you can be using the old `go-bindata` and generate incorrect bindata. See: https://github.com/openshift/machine-config-operator/blob/acb193e7d5b1edebb514e30a7e5cca686d5617d5/Makefile#L41
