### ISSUE TITLE
MCD doesn't always fully apply new configs

### ISSUE THREAD

**Issue by sdemos** [openshift/machine-config-operator#97]
The [top-level logic of the daemon](https://github.com/openshift/machine-config-operator/blob/3a73b1d142eb1efb3fad5b160915e6ddf3d38311/pkg/daemon/daemon.go#L104) currently goes something like this -
* daemon starts up
* check if the machine is in the desired state, as defined by the desiredConfig annotation. this call returns true if currentConfig == desiredConfig [1], and if it doesn't it checks to make sure all the files, systemd units, and and the operating system are all what we want them to be.
  * if it's not, make sure the config is reconcilable, update, and reboot
  * if it is, set the update as done and make the machine schedulable
* wait for the desiredConfig annotation to change
  * when it does, jump back to the "checking machine state" step and continue

this logic is the source of the bug. if the desired machine config contains _only_ irreconcilable differences between it and the current config, the update is never attempted, because the validation logic only validates that all the _reconcilable_ changes are the same. it should be setting the node as degraded. it's also a time-bomb; if someone later makes a valid, reconcilable change, we attempt to apply the changes and only then does everything get rejected and the node set to degraded.

there are three ways I can see to fix this issue -
1. check that a machine is reconcilable every time the desired annotation changes, before validating machine state. this would also happen on startup, because it's entirely possible that while we weren't running the desiredConfig annotation was updated.
2. update the validation logic so that it checks everything defined by ignition regardless of whether we can reconcile it or not. 
3. only validate the node state either when a machine starts up or when we apply an update that we decided doesn't need a reboot (that doesn't actually ever happen right now but the logic is written with that possibility in mind for the future). the node validation logic acts more explicitly as a gate for marking the update as complete. we always attempt to apply config changes when told to, whether or not they seem to represent the same machine state we are already in.

option 1 lets us reject configs we can't reconcile (fixing this problem). it also seems like it may reduce the number of reboots, if, say, we are told to update to a config that we _can_ reconcile, but it turns out that we don't actually need to make any changes to the machine (although, of the top of my head, I can't think of any examples of when this would happen that aren't bugs in the validation logic). the problem with this approach is that it relies much more heavily on our validation logic being totally complete and correct, since if it thinks that a machine is in the correct state, it never goes through the update application logic.

option 2 seems like it would be a lot of work, and it seems like unecessary work, making the assumption that we are the only people who can modify a node under normal operation (plus, even if the node is modified, arguably it's better to just leave that modification be then wipe everything away and start over, since presumably there is a reason for the change).

option 3 is essentially in line with the logic I've always had in mind for the node-agent, now mcd. we rely on the mcc to only tell us to update to a new configuration if there is actually a difference (which it does right now) for minimizing our reboots. if there are subtle side-effects of the update application that we don't account for when validating the machine state, they still happen. this is the option I'm leaning towards.

[1]: I don't think that this should be in the validation logic in general, but I'm going to be opening a separate bug for the issue of removing it since it's not really related to this bug.

/cc @ashcrow @jlebon @kikisdeliveryservice

**Comment by ashcrow** [comment]
I agree with @jlebon. Option 1 to me makes the most sense at least for now.

**Comment by jlebon** [comment]
Sigh, I had a typo for "cheaper to update than to check", I edited it to read "cheaper to check than to update".

**Comment by kikisdeliveryservice** [comment]
I don't have much of a pony in this race =) but wondering @ashcrow if the "for now" in your response means you'd foresee us having to change it later?

**Comment by kikisdeliveryservice** [comment]
Also thanks @sdemos for this comprehensive writeup!

**Comment by ashcrow** [comment]
I don't forsee us *having* to change it in the future, but we may decide to do so.

**Comment by sdemos** [comment]
I still think option 3 is the way to go here. I don't foresee any situations where we will be told to update to a valid config that doesn't actually require any changes (i.e. I think every change will either be invalid _or_ require us to apply the update). I think it's more likely we end up in a situation where we end up discounting configurations that have subtle side effects we don't account for in the validation logic, and then those side effects don't happen when we want them to. 

however, it's possible that I'm just afraid of nothing here, or that I'm not seeing something. if everyone still thinks that option 1 is the way to go, I'll throw that change together instead.

**Comment by ashcrow** [comment]
I personally still like 1 because of the extra validation that occurs. It doesn't get skipped via following a different code path.

**Comment by sdemos** [comment]
in option 3 validation still occurs for all updates, it just doesn't stop an update from being applied. validation would be the gate for marking a node update as completed, so it would have to happen.

**Comment by ashcrow** [comment]
@sdemos In that case I misunderstood. So with 3 we still don't attempt to apply non-reconcilable MC's correct? If so, I'm fine with us running with 1 or 3 out of the gate.

**Comment by sdemos** [comment]
yeah, reconcilability is still determined as part of the update flow, so configs will get rejected if we can't apply them. then we apply the update, and then validate that it was applied the way we expected it to be. 

there is some slight complexity around handling updates that don't require reboots, but that complexity was always there, we just need to make sure we account for it.

**Comment by ashcrow** [comment]
Unless @jlebon objects, then 3 WFM.

**Comment by jlebon** [comment]
I think (3) is fine with me too. We can always make it smarter as well so we don't update things that obviously didn't change, e.g. not calling `pivot` if `bootedOSImageURL == desiredOSImageURL`.
