### ISSUE TITLE
MCD: consider removing annotation equality checking from node validation logic

### ISSUE THREAD

**Issue by sdemos** [openshift/machine-config-operator#98]
the current [validation logic](https://github.com/openshift/machine-config-operator/blob/3a73b1d142eb1efb3fad5b160915e6ddf3d38311/pkg/daemon/daemon.go#L198) in the MCD first checks if the annotations on the node are equal. if they are, it assumes that the node has a valid configuration. 

this assumption does make some amount of sense. we are generally careful to validate the node state before marking the update as done, so if everything is as expected and nothing ever changes, the node _is_ going to be in a valid state. 

however, I think we should always validate the machine state in full every time we call the validation function. it's not a particularly expensive check, and it allows us to easily validate our assumptions about machine state being constant, and fix it if the state changes for some reason. plus, it insulates us a little bit from transitory issues with the values in the annotations, which obviously shouldn't happen, but we can trivially not rely as much on them and instead anchor ourselves in reality by removing this check. there might be other good reasons I'm not coming up with too.

thoughts?

/cc @jlebon @ashcrow

**Comment by jlebon** [comment]
Yeah, dropping that assumption and just always checking makes sense to me. Though if we end up going with option 3 in #97, this part will get obliterated anyway, right?

**Comment by sdemos** [comment]
the way I was envisioning it, the validation logic would stay the same in option 3, all that would change are the call sites of the validation function, so this change would still be required.

**Comment by jlebon** [comment]
Right, definitely in the "gate" case, you wouldn't want to stop at just annotation checking. :)
