### ISSUE TITLE
have the MCO gather bootstrap images

### ISSUE THREAD

**Issue by runcom** [openshift/machine-config-operator#988]
Today, [bootkube inspects the payload](https://github.com/openshift/installer/blob/720b4889bbf34872356dee0a60a49ecf122946c8/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template#L19) and [pass to the MCO bootstrap the images we need](https://github.com/openshift/installer/blob/720b4889bbf34872356dee0a60a49ecf122946c8/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template#L193).
This has been an ongoing hassle to have ratchet PRs all around to avoid breaking either component.
What we can do is having the MCO get the full payload image and inspect it ourselves to avoid the back and forth when adding/removing images for us. The [CVO for instance does that itself already](https://github.com/openshift/installer/blob/720b4889bbf34872356dee0a60a49ecf122946c8/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template#L64).

**Comment by abhinavdahiya** [comment]
one other solution is to ask for [config-map](https://github.com/openshift/machine-config-operator/blob/master/install/0000_80_machine-config-operator_02_images.configmap.yaml) file that already has all the images...

**Comment by runcom** [comment]
> one other solution is to ask for [config-map](https://github.com/openshift/machine-config-operator/blob/master/install/0000_80_machine-config-operator_02_images.configmap.yaml) file that already has all the images...

that would be cool as well and doesn't require anything to query the payload (the MCO doesn't have access to the host with podman to run it and gather images indeed)

**Comment by abhinavdahiya** [comment]
> The [CVO for instance does that itself already](https://github.com/openshift/installer/blob/720b4889bbf34872356dee0a60a49ecf122946c8/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template#L64).

CVO does that because `release-image is CVO` (release-image = cvo + release-manifests) and that's the solution for chicken-egg.

other operators like control-plane ones also have to deal with this, and there are plans on working with master team to get some standarization around the inputs to bootstrap-operators. cc @deads2k
