### ISSUE TITLE
MCC reporting unsupported platform when installing on vSphere

### ISSUE THREAD

**Issue by miabbott** [openshift/machine-config-operator#997]
**Description**

During a UPI install of Openshift 4.1 on vSphere, the MCC is reporting vSphere as an unsupported platform.

**Steps to reproduce the issue:**
1.  Perform UPI install of OpenShift 4.1 on vSphere
2.  Inspect MCC logs on bootstrap node
3.

**Describe the results you received:**

```
[root@bootstrap-0 ~]# crictl logs -f 2ad00effa3946
I0721 17:30:31.823340       1 bootstrap.go:40] Version: 4.1.6-201907101224-dirty (365c1cfd14de5b0e3b85e0fc815b0060f36ab955)
W0721 17:30:31.831657       1 render.go:127] Warning: the controller config referenced an unsupported platform: vsphere
W0721 17:30:31.843369       1 render.go:127] Warning: the controller config referenced an unsupported platform: vsphere
W0721 17:30:31.845925       1 render.go:127] Warning: the controller config referenced an unsupported platform: vsphere
W0721 17:30:31.847011       1 render.go:127] Warning: the controller config referenced an unsupported platform: vsphere
W0721 17:30:31.849637       1 render.go:127] Warning: the controller config referenced an unsupported platform: vsphere
W0721 17:30:31.852473       1 render.go:127] Warning: the controller config referenced an unsupported platform: vsphere
```

**Describe the results you expected:**

No warnings about vSphere as an unsupported platform

(filed on behalf of an email sent to aos-devel@redhat.com)

**Comment by ericavonb** [comment]
I'm unsure what the definition of "supported" is for the MCO, but assuming we _do_ support vsphere I put out a PR fixing this issue: https://github.com/openshift/machine-config-operator/pull/998

**Comment by kikisdeliveryservice** [comment]
Is vsphere fully supported? I've asked the person who added it to mco in the PR.. Also can this be made into a BZ since it will not get merged if correct otherwise @miabbott

**Comment by kikisdeliveryservice** [comment]
Some info here: https://github.com/openshift/machine-config-operator/pull/998#discussion_r305925408

This might be desired behavior, waiting for more info...

**Comment by miabbott** [comment]
@kikisdeliveryservice the original email points to our UPI docs for vSphere - https://docs.openshift.com/container-platform/4.1/installing/installing_vsphere/installing-vsphere.html#installation-vsphere-config-yaml_installing-vsphere

We certainly support using vSphere, but maybe there is an interaction (hinted at in that comment you linked) that is not supported and thus the error message is correct?  

I'll open a BZ regardless and see where this all goes.

**Comment by miabbott** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1732516
